// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"
	mock "github.com/stretchr/testify/mock"
)

// AgentTurnEvaluator is an autogenerated mock type for the AgentTurnEvaluator type.
type AgentTurnEvaluator struct {
	mock.Mock
}

func (_m *AgentTurnEvaluator) EvaluateArtifactQualityBar(ctx context.Context, req claims.QualityBarEvaluationRequest) (claims.QualityBarEvaluationResult, error) {
	ret := _m.Called(ctx, req)
	if len(ret) == 0 {
		panic("no return value specified for EvaluateArtifactQualityBar")
	}

	var r0 claims.QualityBarEvaluationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, claims.QualityBarEvaluationRequest) claims.QualityBarEvaluationResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(claims.QualityBarEvaluationResult)
	}
	if rf, ok := ret.Get(1).(func(context.Context, claims.QualityBarEvaluationRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}
