// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"
	mock "github.com/stretchr/testify/mock"
)

type DAGProcessorBackend struct{ mock.Mock }

func (_m *DAGProcessorBackend) HandleDAGOperation(ctx context.Context, req claims.DAGOperationRequest) (claims.DAGOperationArtifactData, error) {
	ret := _m.Called(ctx, req)
	var r0 claims.DAGOperationArtifactData
	if rf, ok := ret.Get(0).(func(context.Context, claims.DAGOperationRequest) claims.DAGOperationArtifactData); ok {
		r0 = rf(ctx, req)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(claims.DAGOperationArtifactData)
	}
	return r0, ret.Error(1)
}

type VFSProvisionerBackend struct{ mock.Mock }

func (_m *VFSProvisionerBackend) HandleVFSOperation(ctx context.Context, req claims.VFSOperationRequest) (claims.VFSOperationArtifactData, error) {
	ret := _m.Called(ctx, req)
	var r0 claims.VFSOperationArtifactData
	if rf, ok := ret.Get(0).(func(context.Context, claims.VFSOperationRequest) claims.VFSOperationArtifactData); ok {
		r0 = rf(ctx, req)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(claims.VFSOperationArtifactData)
	}
	return r0, ret.Error(1)
}

type ToolRuntimeBackend struct{ mock.Mock }

func (_m *ToolRuntimeBackend) HandleToolRuntimeExecution(ctx context.Context, req claims.ToolRuntimeExecutionRequest) (claims.ToolRuntimeExecutionArtifactData, error) {
	ret := _m.Called(ctx, req)
	var r0 claims.ToolRuntimeExecutionArtifactData
	if rf, ok := ret.Get(0).(func(context.Context, claims.ToolRuntimeExecutionRequest) claims.ToolRuntimeExecutionArtifactData); ok {
		r0 = rf(ctx, req)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(claims.ToolRuntimeExecutionArtifactData)
	}
	return r0, ret.Error(1)
}

type KnowledgeBackend struct{ mock.Mock }

func (_m *KnowledgeBackend) HandleKnowledgeOperation(ctx context.Context, req claims.KnowledgeOperationRequest) (claims.KnowledgeOperationArtifactData, error) {
	ret := _m.Called(ctx, req)
	var r0 claims.KnowledgeOperationArtifactData
	if rf, ok := ret.Get(0).(func(context.Context, claims.KnowledgeOperationRequest) claims.KnowledgeOperationArtifactData); ok {
		r0 = rf(ctx, req)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(claims.KnowledgeOperationArtifactData)
	}
	return r0, ret.Error(1)
}

type MemoryContinuityBackend struct{ mock.Mock }

func (_m *MemoryContinuityBackend) HandleMemoryContinuity(ctx context.Context, req claims.MemoryContinuityRequest) (claims.MemoryContinuityArtifactData, error) {
	ret := _m.Called(ctx, req)
	var r0 claims.MemoryContinuityArtifactData
	if rf, ok := ret.Get(0).(func(context.Context, claims.MemoryContinuityRequest) claims.MemoryContinuityArtifactData); ok {
		r0 = rf(ctx, req)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(claims.MemoryContinuityArtifactData)
	}
	return r0, ret.Error(1)
}

type DocumentBackend struct{ mock.Mock }

func (_m *DocumentBackend) HandleDocumentOperation(ctx context.Context, req claims.DocumentOperationRequest) (claims.DocumentOperationArtifactData, error) {
	ret := _m.Called(ctx, req)
	var r0 claims.DocumentOperationArtifactData
	if rf, ok := ret.Get(0).(func(context.Context, claims.DocumentOperationRequest) claims.DocumentOperationArtifactData); ok {
		r0 = rf(ctx, req)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(claims.DocumentOperationArtifactData)
	}
	return r0, ret.Error(1)
}

type GuardianBackend struct{ mock.Mock }

func (_m *GuardianBackend) HandleGuardianDecision(ctx context.Context, req claims.GuardianDecisionRequest) (claims.GuardianDecisionArtifactData, error) {
	ret := _m.Called(ctx, req)
	var r0 claims.GuardianDecisionArtifactData
	if rf, ok := ret.Get(0).(func(context.Context, claims.GuardianDecisionRequest) claims.GuardianDecisionArtifactData); ok {
		r0 = rf(ctx, req)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(claims.GuardianDecisionArtifactData)
	}
	return r0, ret.Error(1)
}

type ProviderGatewayBackend struct{ mock.Mock }

func (_m *ProviderGatewayBackend) HandleProviderGatewayCall(ctx context.Context, req claims.ProviderGatewayCallRequest) (claims.ProviderGatewayCallArtifactData, error) {
	ret := _m.Called(ctx, req)
	var r0 claims.ProviderGatewayCallArtifactData
	if rf, ok := ret.Get(0).(func(context.Context, claims.ProviderGatewayCallRequest) claims.ProviderGatewayCallArtifactData); ok {
		r0 = rf(ctx, req)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(claims.ProviderGatewayCallArtifactData)
	}
	return r0, ret.Error(1)
}

type ExternalAdapterBackend struct{ mock.Mock }

func (_m *ExternalAdapterBackend) HandleExternalAdapterEvent(ctx context.Context, req claims.ExternalAdapterEventRequest) (claims.ExternalAdapterEventArtifactData, error) {
	ret := _m.Called(ctx, req)
	var r0 claims.ExternalAdapterEventArtifactData
	if rf, ok := ret.Get(0).(func(context.Context, claims.ExternalAdapterEventRequest) claims.ExternalAdapterEventArtifactData); ok {
		r0 = rf(ctx, req)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(claims.ExternalAdapterEventArtifactData)
	}
	return r0, ret.Error(1)
}
