// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// ProviderGatewayBackend is an autogenerated mock type for the ProviderGatewayBackend type
type ProviderGatewayBackend struct {
	mock.Mock
}

type ProviderGatewayBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *ProviderGatewayBackend) EXPECT() *ProviderGatewayBackend_Expecter {
	return &ProviderGatewayBackend_Expecter{mock: &_m.Mock}
}

// HandleProviderGatewayCall provides a mock function with given fields: _a0, _a1
func (_m *ProviderGatewayBackend) HandleProviderGatewayCall(_a0 context.Context, _a1 claims.InfrastructureBackendRequest[claims.ProviderGatewayCallArtifactData]) (claims.ProviderGatewayCallArtifactData, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HandleProviderGatewayCall")
	}

	var r0 claims.ProviderGatewayCallArtifactData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, claims.InfrastructureBackendRequest[claims.ProviderGatewayCallArtifactData]) (claims.ProviderGatewayCallArtifactData, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, claims.InfrastructureBackendRequest[claims.ProviderGatewayCallArtifactData]) claims.ProviderGatewayCallArtifactData); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(claims.ProviderGatewayCallArtifactData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, claims.InfrastructureBackendRequest[claims.ProviderGatewayCallArtifactData]) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProviderGatewayBackend_HandleProviderGatewayCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleProviderGatewayCall'
type ProviderGatewayBackend_HandleProviderGatewayCall_Call struct {
	*mock.Call
}

// HandleProviderGatewayCall is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 claims.InfrastructureBackendRequest[claims.ProviderGatewayCallArtifactData]
func (_e *ProviderGatewayBackend_Expecter) HandleProviderGatewayCall(_a0 interface{}, _a1 interface{}) *ProviderGatewayBackend_HandleProviderGatewayCall_Call {
	return &ProviderGatewayBackend_HandleProviderGatewayCall_Call{Call: _e.mock.On("HandleProviderGatewayCall", _a0, _a1)}
}

func (_c *ProviderGatewayBackend_HandleProviderGatewayCall_Call) Run(run func(_a0 context.Context, _a1 claims.InfrastructureBackendRequest[claims.ProviderGatewayCallArtifactData])) *ProviderGatewayBackend_HandleProviderGatewayCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(claims.InfrastructureBackendRequest[claims.ProviderGatewayCallArtifactData]))
	})
	return _c
}

func (_c *ProviderGatewayBackend_HandleProviderGatewayCall_Call) Return(_a0 claims.ProviderGatewayCallArtifactData, _a1 error) *ProviderGatewayBackend_HandleProviderGatewayCall_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProviderGatewayBackend_HandleProviderGatewayCall_Call) RunAndReturn(run func(context.Context, claims.InfrastructureBackendRequest[claims.ProviderGatewayCallArtifactData]) (claims.ProviderGatewayCallArtifactData, error)) *ProviderGatewayBackend_HandleProviderGatewayCall_Call {
	_c.Call.Return(run)
	return _c
}

// NewProviderGatewayBackend creates a new instance of ProviderGatewayBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProviderGatewayBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProviderGatewayBackend {
	mock := &ProviderGatewayBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
