// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// AgentTurnEvaluator is an autogenerated mock type for the AgentTurnEvaluator type
type AgentTurnEvaluator struct {
	mock.Mock
}

type AgentTurnEvaluator_Expecter struct {
	mock *mock.Mock
}

func (_m *AgentTurnEvaluator) EXPECT() *AgentTurnEvaluator_Expecter {
	return &AgentTurnEvaluator_Expecter{mock: &_m.Mock}
}

// EvaluateArtifactQualityBar provides a mock function with given fields: ctx, req
func (_m *AgentTurnEvaluator) EvaluateArtifactQualityBar(ctx context.Context, req claims.QualityBarEvaluationRequest) (claims.QualityBarEvaluationResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EvaluateArtifactQualityBar")
	}

	var r0 claims.QualityBarEvaluationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, claims.QualityBarEvaluationRequest) (claims.QualityBarEvaluationResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, claims.QualityBarEvaluationRequest) claims.QualityBarEvaluationResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(claims.QualityBarEvaluationResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, claims.QualityBarEvaluationRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AgentTurnEvaluator_EvaluateArtifactQualityBar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvaluateArtifactQualityBar'
type AgentTurnEvaluator_EvaluateArtifactQualityBar_Call struct {
	*mock.Call
}

// EvaluateArtifactQualityBar is a helper method to define mock.On call
//   - ctx context.Context
//   - req claims.QualityBarEvaluationRequest
func (_e *AgentTurnEvaluator_Expecter) EvaluateArtifactQualityBar(ctx interface{}, req interface{}) *AgentTurnEvaluator_EvaluateArtifactQualityBar_Call {
	return &AgentTurnEvaluator_EvaluateArtifactQualityBar_Call{Call: _e.mock.On("EvaluateArtifactQualityBar", ctx, req)}
}

func (_c *AgentTurnEvaluator_EvaluateArtifactQualityBar_Call) Run(run func(ctx context.Context, req claims.QualityBarEvaluationRequest)) *AgentTurnEvaluator_EvaluateArtifactQualityBar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(claims.QualityBarEvaluationRequest))
	})
	return _c
}

func (_c *AgentTurnEvaluator_EvaluateArtifactQualityBar_Call) Return(_a0 claims.QualityBarEvaluationResult, _a1 error) *AgentTurnEvaluator_EvaluateArtifactQualityBar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AgentTurnEvaluator_EvaluateArtifactQualityBar_Call) RunAndReturn(run func(context.Context, claims.QualityBarEvaluationRequest) (claims.QualityBarEvaluationResult, error)) *AgentTurnEvaluator_EvaluateArtifactQualityBar_Call {
	_c.Call.Return(run)
	return _c
}

// NewAgentTurnEvaluator creates a new instance of AgentTurnEvaluator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAgentTurnEvaluator(t interface {
	mock.TestingT
	Cleanup(func())
}) *AgentTurnEvaluator {
	mock := &AgentTurnEvaluator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
