// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ExpectedToolArgumentRedactor is an autogenerated mock type for the ExpectedToolArgumentRedactor type
type ExpectedToolArgumentRedactor struct {
	mock.Mock
}

type ExpectedToolArgumentRedactor_Expecter struct {
	mock *mock.Mock
}

func (_m *ExpectedToolArgumentRedactor) EXPECT() *ExpectedToolArgumentRedactor_Expecter {
	return &ExpectedToolArgumentRedactor_Expecter{mock: &_m.Mock}
}

// RedactExpectedToolArguments provides a mock function with given fields: ctx, tool, args
func (_m *ExpectedToolArgumentRedactor) RedactExpectedToolArguments(ctx context.Context, tool string, args map[string]interface{}) (map[string]interface{}, error) {
	ret := _m.Called(ctx, tool, args)

	if len(ret) == 0 {
		panic("no return value specified for RedactExpectedToolArguments")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) (map[string]interface{}, error)); ok {
		return rf(ctx, tool, args)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) map[string]interface{}); ok {
		r0 = rf(ctx, tool, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, tool, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpectedToolArgumentRedactor_RedactExpectedToolArguments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RedactExpectedToolArguments'
type ExpectedToolArgumentRedactor_RedactExpectedToolArguments_Call struct {
	*mock.Call
}

// RedactExpectedToolArguments is a helper method to define mock.On call
//   - ctx context.Context
//   - tool string
//   - args map[string]interface{}
func (_e *ExpectedToolArgumentRedactor_Expecter) RedactExpectedToolArguments(ctx interface{}, tool interface{}, args interface{}) *ExpectedToolArgumentRedactor_RedactExpectedToolArguments_Call {
	return &ExpectedToolArgumentRedactor_RedactExpectedToolArguments_Call{Call: _e.mock.On("RedactExpectedToolArguments", ctx, tool, args)}
}

func (_c *ExpectedToolArgumentRedactor_RedactExpectedToolArguments_Call) Run(run func(ctx context.Context, tool string, args map[string]interface{})) *ExpectedToolArgumentRedactor_RedactExpectedToolArguments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *ExpectedToolArgumentRedactor_RedactExpectedToolArguments_Call) Return(_a0 map[string]interface{}, _a1 error) *ExpectedToolArgumentRedactor_RedactExpectedToolArguments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExpectedToolArgumentRedactor_RedactExpectedToolArguments_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) (map[string]interface{}, error)) *ExpectedToolArgumentRedactor_RedactExpectedToolArguments_Call {
	_c.Call.Return(run)
	return _c
}

// NewExpectedToolArgumentRedactor creates a new instance of ExpectedToolArgumentRedactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpectedToolArgumentRedactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpectedToolArgumentRedactor {
	mock := &ExpectedToolArgumentRedactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
