// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// AgentRefResolver is an autogenerated mock type for the AgentRefResolver type
type AgentRefResolver struct {
	mock.Mock
}

type AgentRefResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *AgentRefResolver) EXPECT() *AgentRefResolver_Expecter {
	return &AgentRefResolver_Expecter{mock: &_m.Mock}
}

// ResolveAgentRef provides a mock function with given fields: ctx, sessionID, agentID
func (_m *AgentRefResolver) ResolveAgentRef(ctx context.Context, sessionID string, agentID string) (claims.AgentRef, bool) {
	ret := _m.Called(ctx, sessionID, agentID)

	if len(ret) == 0 {
		panic("no return value specified for ResolveAgentRef")
	}

	var r0 claims.AgentRef
	var r1 bool
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (claims.AgentRef, bool)); ok {
		return rf(ctx, sessionID, agentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) claims.AgentRef); ok {
		r0 = rf(ctx, sessionID, agentID)
	} else {
		r0 = ret.Get(0).(claims.AgentRef)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = rf(ctx, sessionID, agentID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// AgentRefResolver_ResolveAgentRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveAgentRef'
type AgentRefResolver_ResolveAgentRef_Call struct {
	*mock.Call
}

// ResolveAgentRef is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID string
//   - agentID string
func (_e *AgentRefResolver_Expecter) ResolveAgentRef(ctx interface{}, sessionID interface{}, agentID interface{}) *AgentRefResolver_ResolveAgentRef_Call {
	return &AgentRefResolver_ResolveAgentRef_Call{Call: _e.mock.On("ResolveAgentRef", ctx, sessionID, agentID)}
}

func (_c *AgentRefResolver_ResolveAgentRef_Call) Run(run func(ctx context.Context, sessionID string, agentID string)) *AgentRefResolver_ResolveAgentRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AgentRefResolver_ResolveAgentRef_Call) Return(_a0 claims.AgentRef, _a1 bool) *AgentRefResolver_ResolveAgentRef_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AgentRefResolver_ResolveAgentRef_Call) RunAndReturn(run func(context.Context, string, string) (claims.AgentRef, bool)) *AgentRefResolver_ResolveAgentRef_Call {
	_c.Call.Return(run)
	return _c
}

// NewAgentRefResolver creates a new instance of AgentRefResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAgentRefResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *AgentRefResolver {
	mock := &AgentRefResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
