// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// ShutdownScope is an autogenerated mock type for the ShutdownScope type
type ShutdownScope struct {
	mock.Mock
}

type ShutdownScope_Expecter struct {
	mock *mock.Mock
}

func (_m *ShutdownScope) EXPECT() *ShutdownScope_Expecter {
	return &ShutdownScope_Expecter{mock: &_m.Mock}
}

// Shutdown provides a mock function with given fields: gracePeriod, hardDeadline
func (_m *ShutdownScope) Shutdown(gracePeriod time.Duration, hardDeadline time.Duration) error {
	ret := _m.Called(gracePeriod, hardDeadline)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(time.Duration, time.Duration) error); ok {
		r0 = rf(gracePeriod, hardDeadline)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ShutdownScope_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type ShutdownScope_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - gracePeriod time.Duration
//   - hardDeadline time.Duration
func (_e *ShutdownScope_Expecter) Shutdown(gracePeriod interface{}, hardDeadline interface{}) *ShutdownScope_Shutdown_Call {
	return &ShutdownScope_Shutdown_Call{Call: _e.mock.On("Shutdown", gracePeriod, hardDeadline)}
}

func (_c *ShutdownScope_Shutdown_Call) Run(run func(gracePeriod time.Duration, hardDeadline time.Duration)) *ShutdownScope_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(time.Duration), args[1].(time.Duration))
	})
	return _c
}

func (_c *ShutdownScope_Shutdown_Call) Return(_a0 error) *ShutdownScope_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ShutdownScope_Shutdown_Call) RunAndReturn(run func(time.Duration, time.Duration) error) *ShutdownScope_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// SignalShutdown provides a mock function with no fields
func (_m *ShutdownScope) SignalShutdown() {
	_m.Called()
}

// ShutdownScope_SignalShutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignalShutdown'
type ShutdownScope_SignalShutdown_Call struct {
	*mock.Call
}

// SignalShutdown is a helper method to define mock.On call
func (_e *ShutdownScope_Expecter) SignalShutdown() *ShutdownScope_SignalShutdown_Call {
	return &ShutdownScope_SignalShutdown_Call{Call: _e.mock.On("SignalShutdown")}
}

func (_c *ShutdownScope_SignalShutdown_Call) Run(run func()) *ShutdownScope_SignalShutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ShutdownScope_SignalShutdown_Call) Return() *ShutdownScope_SignalShutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *ShutdownScope_SignalShutdown_Call) RunAndReturn(run func()) *ShutdownScope_SignalShutdown_Call {
	_c.Run(run)
	return _c
}

// NewShutdownScope creates a new instance of ShutdownScope. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewShutdownScope(t interface {
	mock.TestingT
	Cleanup(func())
}) *ShutdownScope {
	mock := &ShutdownScope{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
