// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// ClaimsProjector is an autogenerated mock type for the ClaimsProjector type
type ClaimsProjector struct {
	mock.Mock
}

type ClaimsProjector_Expecter struct {
	mock *mock.Mock
}

func (_m *ClaimsProjector) EXPECT() *ClaimsProjector_Expecter {
	return &ClaimsProjector_Expecter{mock: &_m.Mock}
}

// Name provides a mock function with no fields
func (_m *ClaimsProjector) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ClaimsProjector_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type ClaimsProjector_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *ClaimsProjector_Expecter) Name() *ClaimsProjector_Name_Call {
	return &ClaimsProjector_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *ClaimsProjector_Name_Call) Run(run func()) *ClaimsProjector_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ClaimsProjector_Name_Call) Return(_a0 string) *ClaimsProjector_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClaimsProjector_Name_Call) RunAndReturn(run func() string) *ClaimsProjector_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Project provides a mock function with given fields: ctx, record, board
func (_m *ClaimsProjector) Project(ctx context.Context, record *claims.ClaimsOutboxRecord, board *claims.ClaimsBoard) error {
	ret := _m.Called(ctx, record, board)

	if len(ret) == 0 {
		panic("no return value specified for Project")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *claims.ClaimsOutboxRecord, *claims.ClaimsBoard) error); ok {
		r0 = rf(ctx, record, board)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClaimsProjector_Project_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Project'
type ClaimsProjector_Project_Call struct {
	*mock.Call
}

// Project is a helper method to define mock.On call
//   - ctx context.Context
//   - record *claims.ClaimsOutboxRecord
//   - board *claims.ClaimsBoard
func (_e *ClaimsProjector_Expecter) Project(ctx interface{}, record interface{}, board interface{}) *ClaimsProjector_Project_Call {
	return &ClaimsProjector_Project_Call{Call: _e.mock.On("Project", ctx, record, board)}
}

func (_c *ClaimsProjector_Project_Call) Run(run func(ctx context.Context, record *claims.ClaimsOutboxRecord, board *claims.ClaimsBoard)) *ClaimsProjector_Project_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*claims.ClaimsOutboxRecord), args[2].(*claims.ClaimsBoard))
	})
	return _c
}

func (_c *ClaimsProjector_Project_Call) Return(_a0 error) *ClaimsProjector_Project_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClaimsProjector_Project_Call) RunAndReturn(run func(context.Context, *claims.ClaimsOutboxRecord, *claims.ClaimsBoard) error) *ClaimsProjector_Project_Call {
	_c.Call.Return(run)
	return _c
}

// NewClaimsProjector creates a new instance of ClaimsProjector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaimsProjector(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClaimsProjector {
	mock := &ClaimsProjector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
