// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// VFSProvisionerBackend is an autogenerated mock type for the VFSProvisionerBackend type
type VFSProvisionerBackend struct {
	mock.Mock
}

type VFSProvisionerBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *VFSProvisionerBackend) EXPECT() *VFSProvisionerBackend_Expecter {
	return &VFSProvisionerBackend_Expecter{mock: &_m.Mock}
}

// HandleVFSOperation provides a mock function with given fields: _a0, _a1
func (_m *VFSProvisionerBackend) HandleVFSOperation(_a0 context.Context, _a1 claims.InfrastructureBackendRequest[claims.VFSOperationArtifactData]) (claims.VFSOperationArtifactData, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HandleVFSOperation")
	}

	var r0 claims.VFSOperationArtifactData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, claims.InfrastructureBackendRequest[claims.VFSOperationArtifactData]) (claims.VFSOperationArtifactData, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, claims.InfrastructureBackendRequest[claims.VFSOperationArtifactData]) claims.VFSOperationArtifactData); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(claims.VFSOperationArtifactData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, claims.InfrastructureBackendRequest[claims.VFSOperationArtifactData]) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VFSProvisionerBackend_HandleVFSOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleVFSOperation'
type VFSProvisionerBackend_HandleVFSOperation_Call struct {
	*mock.Call
}

// HandleVFSOperation is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 claims.InfrastructureBackendRequest[claims.VFSOperationArtifactData]
func (_e *VFSProvisionerBackend_Expecter) HandleVFSOperation(_a0 interface{}, _a1 interface{}) *VFSProvisionerBackend_HandleVFSOperation_Call {
	return &VFSProvisionerBackend_HandleVFSOperation_Call{Call: _e.mock.On("HandleVFSOperation", _a0, _a1)}
}

func (_c *VFSProvisionerBackend_HandleVFSOperation_Call) Run(run func(_a0 context.Context, _a1 claims.InfrastructureBackendRequest[claims.VFSOperationArtifactData])) *VFSProvisionerBackend_HandleVFSOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(claims.InfrastructureBackendRequest[claims.VFSOperationArtifactData]))
	})
	return _c
}

func (_c *VFSProvisionerBackend_HandleVFSOperation_Call) Return(_a0 claims.VFSOperationArtifactData, _a1 error) *VFSProvisionerBackend_HandleVFSOperation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VFSProvisionerBackend_HandleVFSOperation_Call) RunAndReturn(run func(context.Context, claims.InfrastructureBackendRequest[claims.VFSOperationArtifactData]) (claims.VFSOperationArtifactData, error)) *VFSProvisionerBackend_HandleVFSOperation_Call {
	_c.Call.Return(run)
	return _c
}

// NewVFSProvisionerBackend creates a new instance of VFSProvisionerBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVFSProvisionerBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *VFSProvisionerBackend {
	mock := &VFSProvisionerBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
