// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// DeltaBus is an autogenerated mock type for the DeltaBus type
type DeltaBus struct {
	mock.Mock
}

type DeltaBus_Expecter struct {
	mock *mock.Mock
}

func (_m *DeltaBus) EXPECT() *DeltaBus_Expecter {
	return &DeltaBus_Expecter{mock: &_m.Mock}
}

// PublishDelta provides a mock function with given fields: ctx, topic, delta
func (_m *DeltaBus) PublishDelta(ctx context.Context, topic string, delta claims.Delta) error {
	ret := _m.Called(ctx, topic, delta)

	if len(ret) == 0 {
		panic("no return value specified for PublishDelta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, claims.Delta) error); ok {
		r0 = rf(ctx, topic, delta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeltaBus_PublishDelta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishDelta'
type DeltaBus_PublishDelta_Call struct {
	*mock.Call
}

// PublishDelta is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - delta claims.Delta
func (_e *DeltaBus_Expecter) PublishDelta(ctx interface{}, topic interface{}, delta interface{}) *DeltaBus_PublishDelta_Call {
	return &DeltaBus_PublishDelta_Call{Call: _e.mock.On("PublishDelta", ctx, topic, delta)}
}

func (_c *DeltaBus_PublishDelta_Call) Run(run func(ctx context.Context, topic string, delta claims.Delta)) *DeltaBus_PublishDelta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(claims.Delta))
	})
	return _c
}

func (_c *DeltaBus_PublishDelta_Call) Return(_a0 error) *DeltaBus_PublishDelta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeltaBus_PublishDelta_Call) RunAndReturn(run func(context.Context, string, claims.Delta) error) *DeltaBus_PublishDelta_Call {
	_c.Call.Return(run)
	return _c
}

// SubscribeDelta provides a mock function with given fields: pattern, handler
func (_m *DeltaBus) SubscribeDelta(pattern string, handler claims.DeltaHandler) (claims.DeltaSubscription, error) {
	ret := _m.Called(pattern, handler)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeDelta")
	}

	var r0 claims.DeltaSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(string, claims.DeltaHandler) (claims.DeltaSubscription, error)); ok {
		return rf(pattern, handler)
	}
	if rf, ok := ret.Get(0).(func(string, claims.DeltaHandler) claims.DeltaSubscription); ok {
		r0 = rf(pattern, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(claims.DeltaSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(string, claims.DeltaHandler) error); ok {
		r1 = rf(pattern, handler)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeltaBus_SubscribeDelta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeDelta'
type DeltaBus_SubscribeDelta_Call struct {
	*mock.Call
}

// SubscribeDelta is a helper method to define mock.On call
//   - pattern string
//   - handler claims.DeltaHandler
func (_e *DeltaBus_Expecter) SubscribeDelta(pattern interface{}, handler interface{}) *DeltaBus_SubscribeDelta_Call {
	return &DeltaBus_SubscribeDelta_Call{Call: _e.mock.On("SubscribeDelta", pattern, handler)}
}

func (_c *DeltaBus_SubscribeDelta_Call) Run(run func(pattern string, handler claims.DeltaHandler)) *DeltaBus_SubscribeDelta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(claims.DeltaHandler))
	})
	return _c
}

func (_c *DeltaBus_SubscribeDelta_Call) Return(_a0 claims.DeltaSubscription, _a1 error) *DeltaBus_SubscribeDelta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DeltaBus_SubscribeDelta_Call) RunAndReturn(run func(string, claims.DeltaHandler) (claims.DeltaSubscription, error)) *DeltaBus_SubscribeDelta_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeltaBus creates a new instance of DeltaBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeltaBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeltaBus {
	mock := &DeltaBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
