// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	claims "github.com/adalundhe/sylk/core/claims"
	mock "github.com/stretchr/testify/mock"
)

// DeltaSubscriber is an autogenerated mock type for the DeltaSubscriber type
type DeltaSubscriber struct {
	mock.Mock
}

type DeltaSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *DeltaSubscriber) EXPECT() *DeltaSubscriber_Expecter {
	return &DeltaSubscriber_Expecter{mock: &_m.Mock}
}

// SubscribeDelta provides a mock function with given fields: pattern, handler
func (_m *DeltaSubscriber) SubscribeDelta(pattern string, handler claims.DeltaHandler) (claims.DeltaSubscription, error) {
	ret := _m.Called(pattern, handler)

	if len(ret) == 0 {
		panic("no return value specified for SubscribeDelta")
	}

	var r0 claims.DeltaSubscription
	var r1 error
	if rf, ok := ret.Get(0).(func(string, claims.DeltaHandler) (claims.DeltaSubscription, error)); ok {
		return rf(pattern, handler)
	}
	if rf, ok := ret.Get(0).(func(string, claims.DeltaHandler) claims.DeltaSubscription); ok {
		r0 = rf(pattern, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(claims.DeltaSubscription)
		}
	}

	if rf, ok := ret.Get(1).(func(string, claims.DeltaHandler) error); ok {
		r1 = rf(pattern, handler)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeltaSubscriber_SubscribeDelta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubscribeDelta'
type DeltaSubscriber_SubscribeDelta_Call struct {
	*mock.Call
}

// SubscribeDelta is a helper method to define mock.On call
//   - pattern string
//   - handler claims.DeltaHandler
func (_e *DeltaSubscriber_Expecter) SubscribeDelta(pattern interface{}, handler interface{}) *DeltaSubscriber_SubscribeDelta_Call {
	return &DeltaSubscriber_SubscribeDelta_Call{Call: _e.mock.On("SubscribeDelta", pattern, handler)}
}

func (_c *DeltaSubscriber_SubscribeDelta_Call) Run(run func(pattern string, handler claims.DeltaHandler)) *DeltaSubscriber_SubscribeDelta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(claims.DeltaHandler))
	})
	return _c
}

func (_c *DeltaSubscriber_SubscribeDelta_Call) Return(_a0 claims.DeltaSubscription, _a1 error) *DeltaSubscriber_SubscribeDelta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DeltaSubscriber_SubscribeDelta_Call) RunAndReturn(run func(string, claims.DeltaHandler) (claims.DeltaSubscription, error)) *DeltaSubscriber_SubscribeDelta_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeltaSubscriber creates a new instance of DeltaSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeltaSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeltaSubscriber {
	mock := &DeltaSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
