// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// DAGProcessorBackend is an autogenerated mock type for the DAGProcessorBackend type
type DAGProcessorBackend struct {
	mock.Mock
}

type DAGProcessorBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *DAGProcessorBackend) EXPECT() *DAGProcessorBackend_Expecter {
	return &DAGProcessorBackend_Expecter{mock: &_m.Mock}
}

// HandleDAGOperation provides a mock function with given fields: _a0, _a1
func (_m *DAGProcessorBackend) HandleDAGOperation(_a0 context.Context, _a1 claims.InfrastructureBackendRequest[claims.DAGOperationArtifactData]) (claims.DAGOperationArtifactData, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HandleDAGOperation")
	}

	var r0 claims.DAGOperationArtifactData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, claims.InfrastructureBackendRequest[claims.DAGOperationArtifactData]) (claims.DAGOperationArtifactData, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, claims.InfrastructureBackendRequest[claims.DAGOperationArtifactData]) claims.DAGOperationArtifactData); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(claims.DAGOperationArtifactData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, claims.InfrastructureBackendRequest[claims.DAGOperationArtifactData]) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DAGProcessorBackend_HandleDAGOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleDAGOperation'
type DAGProcessorBackend_HandleDAGOperation_Call struct {
	*mock.Call
}

// HandleDAGOperation is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 claims.InfrastructureBackendRequest[claims.DAGOperationArtifactData]
func (_e *DAGProcessorBackend_Expecter) HandleDAGOperation(_a0 interface{}, _a1 interface{}) *DAGProcessorBackend_HandleDAGOperation_Call {
	return &DAGProcessorBackend_HandleDAGOperation_Call{Call: _e.mock.On("HandleDAGOperation", _a0, _a1)}
}

func (_c *DAGProcessorBackend_HandleDAGOperation_Call) Run(run func(_a0 context.Context, _a1 claims.InfrastructureBackendRequest[claims.DAGOperationArtifactData])) *DAGProcessorBackend_HandleDAGOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(claims.InfrastructureBackendRequest[claims.DAGOperationArtifactData]))
	})
	return _c
}

func (_c *DAGProcessorBackend_HandleDAGOperation_Call) Return(_a0 claims.DAGOperationArtifactData, _a1 error) *DAGProcessorBackend_HandleDAGOperation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DAGProcessorBackend_HandleDAGOperation_Call) RunAndReturn(run func(context.Context, claims.InfrastructureBackendRequest[claims.DAGOperationArtifactData]) (claims.DAGOperationArtifactData, error)) *DAGProcessorBackend_HandleDAGOperation_Call {
	_c.Call.Return(run)
	return _c
}

// NewDAGProcessorBackend creates a new instance of DAGProcessorBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDAGProcessorBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *DAGProcessorBackend {
	mock := &DAGProcessorBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
