// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// ExpectedToolExecutor is an autogenerated mock type for the ExpectedToolExecutor type
type ExpectedToolExecutor struct {
	mock.Mock
}

type ExpectedToolExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *ExpectedToolExecutor) EXPECT() *ExpectedToolExecutor_Expecter {
	return &ExpectedToolExecutor_Expecter{mock: &_m.Mock}
}

// ExecuteExpectedTool provides a mock function with given fields: ctx, call
func (_m *ExpectedToolExecutor) ExecuteExpectedTool(ctx context.Context, call claims.ExpectedToolCall) (claims.ExpectedToolExecutionOutput, error) {
	ret := _m.Called(ctx, call)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteExpectedTool")
	}

	var r0 claims.ExpectedToolExecutionOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, claims.ExpectedToolCall) (claims.ExpectedToolExecutionOutput, error)); ok {
		return rf(ctx, call)
	}
	if rf, ok := ret.Get(0).(func(context.Context, claims.ExpectedToolCall) claims.ExpectedToolExecutionOutput); ok {
		r0 = rf(ctx, call)
	} else {
		r0 = ret.Get(0).(claims.ExpectedToolExecutionOutput)
	}

	if rf, ok := ret.Get(1).(func(context.Context, claims.ExpectedToolCall) error); ok {
		r1 = rf(ctx, call)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExpectedToolExecutor_ExecuteExpectedTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteExpectedTool'
type ExpectedToolExecutor_ExecuteExpectedTool_Call struct {
	*mock.Call
}

// ExecuteExpectedTool is a helper method to define mock.On call
//   - ctx context.Context
//   - call claims.ExpectedToolCall
func (_e *ExpectedToolExecutor_Expecter) ExecuteExpectedTool(ctx interface{}, call interface{}) *ExpectedToolExecutor_ExecuteExpectedTool_Call {
	return &ExpectedToolExecutor_ExecuteExpectedTool_Call{Call: _e.mock.On("ExecuteExpectedTool", ctx, call)}
}

func (_c *ExpectedToolExecutor_ExecuteExpectedTool_Call) Run(run func(ctx context.Context, call claims.ExpectedToolCall)) *ExpectedToolExecutor_ExecuteExpectedTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(claims.ExpectedToolCall))
	})
	return _c
}

func (_c *ExpectedToolExecutor_ExecuteExpectedTool_Call) Return(_a0 claims.ExpectedToolExecutionOutput, _a1 error) *ExpectedToolExecutor_ExecuteExpectedTool_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExpectedToolExecutor_ExecuteExpectedTool_Call) RunAndReturn(run func(context.Context, claims.ExpectedToolCall) (claims.ExpectedToolExecutionOutput, error)) *ExpectedToolExecutor_ExecuteExpectedTool_Call {
	_c.Call.Return(run)
	return _c
}

// NewExpectedToolExecutor creates a new instance of ExpectedToolExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpectedToolExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpectedToolExecutor {
	mock := &ExpectedToolExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
