// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// PendingContinuationRecoverer is an autogenerated mock type for the PendingContinuationRecoverer type
type PendingContinuationRecoverer struct {
	mock.Mock
}

type PendingContinuationRecoverer_Expecter struct {
	mock *mock.Mock
}

func (_m *PendingContinuationRecoverer) EXPECT() *PendingContinuationRecoverer_Expecter {
	return &PendingContinuationRecoverer_Expecter{mock: &_m.Mock}
}

// RecoverPendingContinuations provides a mock function with given fields: _a0
func (_m *PendingContinuationRecoverer) RecoverPendingContinuations(_a0 context.Context) int {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for RecoverPendingContinuations")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// PendingContinuationRecoverer_RecoverPendingContinuations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverPendingContinuations'
type PendingContinuationRecoverer_RecoverPendingContinuations_Call struct {
	*mock.Call
}

// RecoverPendingContinuations is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *PendingContinuationRecoverer_Expecter) RecoverPendingContinuations(_a0 interface{}) *PendingContinuationRecoverer_RecoverPendingContinuations_Call {
	return &PendingContinuationRecoverer_RecoverPendingContinuations_Call{Call: _e.mock.On("RecoverPendingContinuations", _a0)}
}

func (_c *PendingContinuationRecoverer_RecoverPendingContinuations_Call) Run(run func(_a0 context.Context)) *PendingContinuationRecoverer_RecoverPendingContinuations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PendingContinuationRecoverer_RecoverPendingContinuations_Call) Return(_a0 int) *PendingContinuationRecoverer_RecoverPendingContinuations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PendingContinuationRecoverer_RecoverPendingContinuations_Call) RunAndReturn(run func(context.Context) int) *PendingContinuationRecoverer_RecoverPendingContinuations_Call {
	_c.Call.Return(run)
	return _c
}

// NewPendingContinuationRecoverer creates a new instance of PendingContinuationRecoverer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPendingContinuationRecoverer(t interface {
	mock.TestingT
	Cleanup(func())
}) *PendingContinuationRecoverer {
	mock := &PendingContinuationRecoverer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
