// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// ToolRuntimeBackend is an autogenerated mock type for the ToolRuntimeBackend type
type ToolRuntimeBackend struct {
	mock.Mock
}

type ToolRuntimeBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *ToolRuntimeBackend) EXPECT() *ToolRuntimeBackend_Expecter {
	return &ToolRuntimeBackend_Expecter{mock: &_m.Mock}
}

// HandleToolRuntimeExecution provides a mock function with given fields: _a0, _a1
func (_m *ToolRuntimeBackend) HandleToolRuntimeExecution(_a0 context.Context, _a1 claims.InfrastructureBackendRequest[claims.ToolRuntimeExecutionArtifactData]) (claims.ToolRuntimeExecutionArtifactData, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HandleToolRuntimeExecution")
	}

	var r0 claims.ToolRuntimeExecutionArtifactData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, claims.InfrastructureBackendRequest[claims.ToolRuntimeExecutionArtifactData]) (claims.ToolRuntimeExecutionArtifactData, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, claims.InfrastructureBackendRequest[claims.ToolRuntimeExecutionArtifactData]) claims.ToolRuntimeExecutionArtifactData); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(claims.ToolRuntimeExecutionArtifactData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, claims.InfrastructureBackendRequest[claims.ToolRuntimeExecutionArtifactData]) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ToolRuntimeBackend_HandleToolRuntimeExecution_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleToolRuntimeExecution'
type ToolRuntimeBackend_HandleToolRuntimeExecution_Call struct {
	*mock.Call
}

// HandleToolRuntimeExecution is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 claims.InfrastructureBackendRequest[claims.ToolRuntimeExecutionArtifactData]
func (_e *ToolRuntimeBackend_Expecter) HandleToolRuntimeExecution(_a0 interface{}, _a1 interface{}) *ToolRuntimeBackend_HandleToolRuntimeExecution_Call {
	return &ToolRuntimeBackend_HandleToolRuntimeExecution_Call{Call: _e.mock.On("HandleToolRuntimeExecution", _a0, _a1)}
}

func (_c *ToolRuntimeBackend_HandleToolRuntimeExecution_Call) Run(run func(_a0 context.Context, _a1 claims.InfrastructureBackendRequest[claims.ToolRuntimeExecutionArtifactData])) *ToolRuntimeBackend_HandleToolRuntimeExecution_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(claims.InfrastructureBackendRequest[claims.ToolRuntimeExecutionArtifactData]))
	})
	return _c
}

func (_c *ToolRuntimeBackend_HandleToolRuntimeExecution_Call) Return(_a0 claims.ToolRuntimeExecutionArtifactData, _a1 error) *ToolRuntimeBackend_HandleToolRuntimeExecution_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ToolRuntimeBackend_HandleToolRuntimeExecution_Call) RunAndReturn(run func(context.Context, claims.InfrastructureBackendRequest[claims.ToolRuntimeExecutionArtifactData]) (claims.ToolRuntimeExecutionArtifactData, error)) *ToolRuntimeBackend_HandleToolRuntimeExecution_Call {
	_c.Call.Return(run)
	return _c
}

// NewToolRuntimeBackend creates a new instance of ToolRuntimeBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewToolRuntimeBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *ToolRuntimeBackend {
	mock := &ToolRuntimeBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
