// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// ExternalAdapterBackend is an autogenerated mock type for the ExternalAdapterBackend type
type ExternalAdapterBackend struct {
	mock.Mock
}

type ExternalAdapterBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *ExternalAdapterBackend) EXPECT() *ExternalAdapterBackend_Expecter {
	return &ExternalAdapterBackend_Expecter{mock: &_m.Mock}
}

// HandleExternalAdapterEvent provides a mock function with given fields: _a0, _a1
func (_m *ExternalAdapterBackend) HandleExternalAdapterEvent(_a0 context.Context, _a1 claims.InfrastructureBackendRequest[claims.ExternalAdapterEventArtifactData]) (claims.ExternalAdapterEventArtifactData, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HandleExternalAdapterEvent")
	}

	var r0 claims.ExternalAdapterEventArtifactData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, claims.InfrastructureBackendRequest[claims.ExternalAdapterEventArtifactData]) (claims.ExternalAdapterEventArtifactData, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, claims.InfrastructureBackendRequest[claims.ExternalAdapterEventArtifactData]) claims.ExternalAdapterEventArtifactData); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(claims.ExternalAdapterEventArtifactData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, claims.InfrastructureBackendRequest[claims.ExternalAdapterEventArtifactData]) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExternalAdapterBackend_HandleExternalAdapterEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleExternalAdapterEvent'
type ExternalAdapterBackend_HandleExternalAdapterEvent_Call struct {
	*mock.Call
}

// HandleExternalAdapterEvent is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 claims.InfrastructureBackendRequest[claims.ExternalAdapterEventArtifactData]
func (_e *ExternalAdapterBackend_Expecter) HandleExternalAdapterEvent(_a0 interface{}, _a1 interface{}) *ExternalAdapterBackend_HandleExternalAdapterEvent_Call {
	return &ExternalAdapterBackend_HandleExternalAdapterEvent_Call{Call: _e.mock.On("HandleExternalAdapterEvent", _a0, _a1)}
}

func (_c *ExternalAdapterBackend_HandleExternalAdapterEvent_Call) Run(run func(_a0 context.Context, _a1 claims.InfrastructureBackendRequest[claims.ExternalAdapterEventArtifactData])) *ExternalAdapterBackend_HandleExternalAdapterEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(claims.InfrastructureBackendRequest[claims.ExternalAdapterEventArtifactData]))
	})
	return _c
}

func (_c *ExternalAdapterBackend_HandleExternalAdapterEvent_Call) Return(_a0 claims.ExternalAdapterEventArtifactData, _a1 error) *ExternalAdapterBackend_HandleExternalAdapterEvent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExternalAdapterBackend_HandleExternalAdapterEvent_Call) RunAndReturn(run func(context.Context, claims.InfrastructureBackendRequest[claims.ExternalAdapterEventArtifactData]) (claims.ExternalAdapterEventArtifactData, error)) *ExternalAdapterBackend_HandleExternalAdapterEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewExternalAdapterBackend creates a new instance of ExternalAdapterBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExternalAdapterBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExternalAdapterBackend {
	mock := &ExternalAdapterBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
