// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// ServiceHandler is an autogenerated mock type for the ServiceHandler type
type ServiceHandler struct {
	mock.Mock
}

type ServiceHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceHandler) EXPECT() *ServiceHandler_Expecter {
	return &ServiceHandler_Expecter{mock: &_m.Mock}
}

// HandleServiceClaim provides a mock function with given fields: ctx, req
func (_m *ServiceHandler) HandleServiceClaim(ctx context.Context, req claims.ServiceClaimRequest) (claims.ServiceClaimResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for HandleServiceClaim")
	}

	var r0 claims.ServiceClaimResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, claims.ServiceClaimRequest) (claims.ServiceClaimResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, claims.ServiceClaimRequest) claims.ServiceClaimResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(claims.ServiceClaimResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, claims.ServiceClaimRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceHandler_HandleServiceClaim_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleServiceClaim'
type ServiceHandler_HandleServiceClaim_Call struct {
	*mock.Call
}

// HandleServiceClaim is a helper method to define mock.On call
//   - ctx context.Context
//   - req claims.ServiceClaimRequest
func (_e *ServiceHandler_Expecter) HandleServiceClaim(ctx interface{}, req interface{}) *ServiceHandler_HandleServiceClaim_Call {
	return &ServiceHandler_HandleServiceClaim_Call{Call: _e.mock.On("HandleServiceClaim", ctx, req)}
}

func (_c *ServiceHandler_HandleServiceClaim_Call) Run(run func(ctx context.Context, req claims.ServiceClaimRequest)) *ServiceHandler_HandleServiceClaim_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(claims.ServiceClaimRequest))
	})
	return _c
}

func (_c *ServiceHandler_HandleServiceClaim_Call) Return(_a0 claims.ServiceClaimResult, _a1 error) *ServiceHandler_HandleServiceClaim_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceHandler_HandleServiceClaim_Call) RunAndReturn(run func(context.Context, claims.ServiceClaimRequest) (claims.ServiceClaimResult, error)) *ServiceHandler_HandleServiceClaim_Call {
	_c.Call.Return(run)
	return _c
}

// NewServiceHandler creates a new instance of ServiceHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceHandler {
	mock := &ServiceHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
