// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// ArtifactLifecycleBusSink is an autogenerated mock type for the ArtifactLifecycleBusSink type
type ArtifactLifecycleBusSink struct {
	mock.Mock
}

type ArtifactLifecycleBusSink_Expecter struct {
	mock *mock.Mock
}

func (_m *ArtifactLifecycleBusSink) EXPECT() *ArtifactLifecycleBusSink_Expecter {
	return &ArtifactLifecycleBusSink_Expecter{mock: &_m.Mock}
}

// PublishArtifactLifecycle provides a mock function with given fields: ctx, event
func (_m *ArtifactLifecycleBusSink) PublishArtifactLifecycle(ctx context.Context, event claims.ArtifactLifecycleEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishArtifactLifecycle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, claims.ArtifactLifecycleEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ArtifactLifecycleBusSink_PublishArtifactLifecycle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishArtifactLifecycle'
type ArtifactLifecycleBusSink_PublishArtifactLifecycle_Call struct {
	*mock.Call
}

// PublishArtifactLifecycle is a helper method to define mock.On call
//   - ctx context.Context
//   - event claims.ArtifactLifecycleEvent
func (_e *ArtifactLifecycleBusSink_Expecter) PublishArtifactLifecycle(ctx interface{}, event interface{}) *ArtifactLifecycleBusSink_PublishArtifactLifecycle_Call {
	return &ArtifactLifecycleBusSink_PublishArtifactLifecycle_Call{Call: _e.mock.On("PublishArtifactLifecycle", ctx, event)}
}

func (_c *ArtifactLifecycleBusSink_PublishArtifactLifecycle_Call) Run(run func(ctx context.Context, event claims.ArtifactLifecycleEvent)) *ArtifactLifecycleBusSink_PublishArtifactLifecycle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(claims.ArtifactLifecycleEvent))
	})
	return _c
}

func (_c *ArtifactLifecycleBusSink_PublishArtifactLifecycle_Call) Return(_a0 error) *ArtifactLifecycleBusSink_PublishArtifactLifecycle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ArtifactLifecycleBusSink_PublishArtifactLifecycle_Call) RunAndReturn(run func(context.Context, claims.ArtifactLifecycleEvent) error) *ArtifactLifecycleBusSink_PublishArtifactLifecycle_Call {
	_c.Call.Return(run)
	return _c
}

// NewArtifactLifecycleBusSink creates a new instance of ArtifactLifecycleBusSink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArtifactLifecycleBusSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArtifactLifecycleBusSink {
	mock := &ArtifactLifecycleBusSink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
