// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// ValidationDispatcher is an autogenerated mock type for the ValidationDispatcher type
type ValidationDispatcher struct {
	mock.Mock
}

type ValidationDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *ValidationDispatcher) EXPECT() *ValidationDispatcher_Expecter {
	return &ValidationDispatcher_Expecter{mock: &_m.Mock}
}

// DispatchValidation provides a mock function with given fields: ctx, req
func (_m *ValidationDispatcher) DispatchValidation(ctx context.Context, req claims.ValidationDispatchRequest) (claims.ValidationDispatchResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DispatchValidation")
	}

	var r0 claims.ValidationDispatchResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, claims.ValidationDispatchRequest) (claims.ValidationDispatchResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, claims.ValidationDispatchRequest) claims.ValidationDispatchResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(claims.ValidationDispatchResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, claims.ValidationDispatchRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidationDispatcher_DispatchValidation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchValidation'
type ValidationDispatcher_DispatchValidation_Call struct {
	*mock.Call
}

// DispatchValidation is a helper method to define mock.On call
//   - ctx context.Context
//   - req claims.ValidationDispatchRequest
func (_e *ValidationDispatcher_Expecter) DispatchValidation(ctx interface{}, req interface{}) *ValidationDispatcher_DispatchValidation_Call {
	return &ValidationDispatcher_DispatchValidation_Call{Call: _e.mock.On("DispatchValidation", ctx, req)}
}

func (_c *ValidationDispatcher_DispatchValidation_Call) Run(run func(ctx context.Context, req claims.ValidationDispatchRequest)) *ValidationDispatcher_DispatchValidation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(claims.ValidationDispatchRequest))
	})
	return _c
}

func (_c *ValidationDispatcher_DispatchValidation_Call) Return(_a0 claims.ValidationDispatchResult, _a1 error) *ValidationDispatcher_DispatchValidation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ValidationDispatcher_DispatchValidation_Call) RunAndReturn(run func(context.Context, claims.ValidationDispatchRequest) (claims.ValidationDispatchResult, error)) *ValidationDispatcher_DispatchValidation_Call {
	_c.Call.Return(run)
	return _c
}

// NewValidationDispatcher creates a new instance of ValidationDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidationDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValidationDispatcher {
	mock := &ValidationDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
