// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// ScopeProvider is an autogenerated mock type for the ScopeProvider type
type ScopeProvider struct {
	mock.Mock
}

type ScopeProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *ScopeProvider) EXPECT() *ScopeProvider_Expecter {
	return &ScopeProvider_Expecter{mock: &_m.Mock}
}

// Go provides a mock function with given fields: description, timeout, fn
func (_m *ScopeProvider) Go(description string, timeout time.Duration, fn func(context.Context) error) error {
	ret := _m.Called(description, timeout, fn)

	if len(ret) == 0 {
		panic("no return value specified for Go")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, time.Duration, func(context.Context) error) error); ok {
		r0 = rf(description, timeout, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ScopeProvider_Go_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Go'
type ScopeProvider_Go_Call struct {
	*mock.Call
}

// Go is a helper method to define mock.On call
//   - description string
//   - timeout time.Duration
//   - fn func(context.Context) error
func (_e *ScopeProvider_Expecter) Go(description interface{}, timeout interface{}, fn interface{}) *ScopeProvider_Go_Call {
	return &ScopeProvider_Go_Call{Call: _e.mock.On("Go", description, timeout, fn)}
}

func (_c *ScopeProvider_Go_Call) Run(run func(description string, timeout time.Duration, fn func(context.Context) error)) *ScopeProvider_Go_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration), args[2].(func(context.Context) error))
	})
	return _c
}

func (_c *ScopeProvider_Go_Call) Return(_a0 error) *ScopeProvider_Go_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ScopeProvider_Go_Call) RunAndReturn(run func(string, time.Duration, func(context.Context) error) error) *ScopeProvider_Go_Call {
	_c.Call.Return(run)
	return _c
}

// NewScopeProvider creates a new instance of ScopeProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScopeProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScopeProvider {
	mock := &ScopeProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
