// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// KnowledgeBackend is an autogenerated mock type for the KnowledgeBackend type
type KnowledgeBackend struct {
	mock.Mock
}

type KnowledgeBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *KnowledgeBackend) EXPECT() *KnowledgeBackend_Expecter {
	return &KnowledgeBackend_Expecter{mock: &_m.Mock}
}

// HandleKnowledgeOperation provides a mock function with given fields: _a0, _a1
func (_m *KnowledgeBackend) HandleKnowledgeOperation(_a0 context.Context, _a1 claims.InfrastructureBackendRequest[claims.KnowledgeOperationArtifactData]) (claims.KnowledgeOperationArtifactData, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HandleKnowledgeOperation")
	}

	var r0 claims.KnowledgeOperationArtifactData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, claims.InfrastructureBackendRequest[claims.KnowledgeOperationArtifactData]) (claims.KnowledgeOperationArtifactData, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, claims.InfrastructureBackendRequest[claims.KnowledgeOperationArtifactData]) claims.KnowledgeOperationArtifactData); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(claims.KnowledgeOperationArtifactData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, claims.InfrastructureBackendRequest[claims.KnowledgeOperationArtifactData]) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// KnowledgeBackend_HandleKnowledgeOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleKnowledgeOperation'
type KnowledgeBackend_HandleKnowledgeOperation_Call struct {
	*mock.Call
}

// HandleKnowledgeOperation is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 claims.InfrastructureBackendRequest[claims.KnowledgeOperationArtifactData]
func (_e *KnowledgeBackend_Expecter) HandleKnowledgeOperation(_a0 interface{}, _a1 interface{}) *KnowledgeBackend_HandleKnowledgeOperation_Call {
	return &KnowledgeBackend_HandleKnowledgeOperation_Call{Call: _e.mock.On("HandleKnowledgeOperation", _a0, _a1)}
}

func (_c *KnowledgeBackend_HandleKnowledgeOperation_Call) Run(run func(_a0 context.Context, _a1 claims.InfrastructureBackendRequest[claims.KnowledgeOperationArtifactData])) *KnowledgeBackend_HandleKnowledgeOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(claims.InfrastructureBackendRequest[claims.KnowledgeOperationArtifactData]))
	})
	return _c
}

func (_c *KnowledgeBackend_HandleKnowledgeOperation_Call) Return(_a0 claims.KnowledgeOperationArtifactData, _a1 error) *KnowledgeBackend_HandleKnowledgeOperation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *KnowledgeBackend_HandleKnowledgeOperation_Call) RunAndReturn(run func(context.Context, claims.InfrastructureBackendRequest[claims.KnowledgeOperationArtifactData]) (claims.KnowledgeOperationArtifactData, error)) *KnowledgeBackend_HandleKnowledgeOperation_Call {
	_c.Call.Return(run)
	return _c
}

// NewKnowledgeBackend creates a new instance of KnowledgeBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKnowledgeBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *KnowledgeBackend {
	mock := &KnowledgeBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
