// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// TestamentGenerator is an autogenerated mock type for the TestamentGenerator type
type TestamentGenerator struct {
	mock.Mock
}

type TestamentGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *TestamentGenerator) EXPECT() *TestamentGenerator_Expecter {
	return &TestamentGenerator_Expecter{mock: &_m.Mock}
}

// GenerateTestamentAction provides a mock function with given fields: ctx, action, testaments, opts
func (_m *TestamentGenerator) GenerateTestamentAction(ctx context.Context, action claims.Action, testaments []claims.Testament, opts claims.GenerateTestamentActionOptions) (*claims.GeneratedTestamentAction, error) {
	ret := _m.Called(ctx, action, testaments, opts)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTestamentAction")
	}

	var r0 *claims.GeneratedTestamentAction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, claims.Action, []claims.Testament, claims.GenerateTestamentActionOptions) (*claims.GeneratedTestamentAction, error)); ok {
		return rf(ctx, action, testaments, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, claims.Action, []claims.Testament, claims.GenerateTestamentActionOptions) *claims.GeneratedTestamentAction); ok {
		r0 = rf(ctx, action, testaments, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*claims.GeneratedTestamentAction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, claims.Action, []claims.Testament, claims.GenerateTestamentActionOptions) error); ok {
		r1 = rf(ctx, action, testaments, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TestamentGenerator_GenerateTestamentAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTestamentAction'
type TestamentGenerator_GenerateTestamentAction_Call struct {
	*mock.Call
}

// GenerateTestamentAction is a helper method to define mock.On call
//   - ctx context.Context
//   - action claims.Action
//   - testaments []claims.Testament
//   - opts claims.GenerateTestamentActionOptions
func (_e *TestamentGenerator_Expecter) GenerateTestamentAction(ctx interface{}, action interface{}, testaments interface{}, opts interface{}) *TestamentGenerator_GenerateTestamentAction_Call {
	return &TestamentGenerator_GenerateTestamentAction_Call{Call: _e.mock.On("GenerateTestamentAction", ctx, action, testaments, opts)}
}

func (_c *TestamentGenerator_GenerateTestamentAction_Call) Run(run func(ctx context.Context, action claims.Action, testaments []claims.Testament, opts claims.GenerateTestamentActionOptions)) *TestamentGenerator_GenerateTestamentAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(claims.Action), args[2].([]claims.Testament), args[3].(claims.GenerateTestamentActionOptions))
	})
	return _c
}

func (_c *TestamentGenerator_GenerateTestamentAction_Call) Return(_a0 *claims.GeneratedTestamentAction, _a1 error) *TestamentGenerator_GenerateTestamentAction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TestamentGenerator_GenerateTestamentAction_Call) RunAndReturn(run func(context.Context, claims.Action, []claims.Testament, claims.GenerateTestamentActionOptions) (*claims.GeneratedTestamentAction, error)) *TestamentGenerator_GenerateTestamentAction_Call {
	_c.Call.Return(run)
	return _c
}

// NewTestamentGenerator creates a new instance of TestamentGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTestamentGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TestamentGenerator {
	mock := &TestamentGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
