// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// DeltaPublisher is an autogenerated mock type for the DeltaPublisher type
type DeltaPublisher struct {
	mock.Mock
}

type DeltaPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *DeltaPublisher) EXPECT() *DeltaPublisher_Expecter {
	return &DeltaPublisher_Expecter{mock: &_m.Mock}
}

// PublishDelta provides a mock function with given fields: ctx, topic, delta
func (_m *DeltaPublisher) PublishDelta(ctx context.Context, topic string, delta claims.Delta) error {
	ret := _m.Called(ctx, topic, delta)

	if len(ret) == 0 {
		panic("no return value specified for PublishDelta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, claims.Delta) error); ok {
		r0 = rf(ctx, topic, delta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeltaPublisher_PublishDelta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishDelta'
type DeltaPublisher_PublishDelta_Call struct {
	*mock.Call
}

// PublishDelta is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - delta claims.Delta
func (_e *DeltaPublisher_Expecter) PublishDelta(ctx interface{}, topic interface{}, delta interface{}) *DeltaPublisher_PublishDelta_Call {
	return &DeltaPublisher_PublishDelta_Call{Call: _e.mock.On("PublishDelta", ctx, topic, delta)}
}

func (_c *DeltaPublisher_PublishDelta_Call) Run(run func(ctx context.Context, topic string, delta claims.Delta)) *DeltaPublisher_PublishDelta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(claims.Delta))
	})
	return _c
}

func (_c *DeltaPublisher_PublishDelta_Call) Return(_a0 error) *DeltaPublisher_PublishDelta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeltaPublisher_PublishDelta_Call) RunAndReturn(run func(context.Context, string, claims.Delta) error) *DeltaPublisher_PublishDelta_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeltaPublisher creates a new instance of DeltaPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeltaPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeltaPublisher {
	mock := &DeltaPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
