// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DeltaSubscription is an autogenerated mock type for the DeltaSubscription type
type DeltaSubscription struct {
	mock.Mock
}

type DeltaSubscription_Expecter struct {
	mock *mock.Mock
}

func (_m *DeltaSubscription) EXPECT() *DeltaSubscription_Expecter {
	return &DeltaSubscription_Expecter{mock: &_m.Mock}
}

// Topic provides a mock function with no fields
func (_m *DeltaSubscription) Topic() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// DeltaSubscription_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type DeltaSubscription_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *DeltaSubscription_Expecter) Topic() *DeltaSubscription_Topic_Call {
	return &DeltaSubscription_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *DeltaSubscription_Topic_Call) Run(run func()) *DeltaSubscription_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DeltaSubscription_Topic_Call) Return(_a0 string) *DeltaSubscription_Topic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeltaSubscription_Topic_Call) RunAndReturn(run func() string) *DeltaSubscription_Topic_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function with no fields
func (_m *DeltaSubscription) Unsubscribe() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeltaSubscription_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type DeltaSubscription_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
func (_e *DeltaSubscription_Expecter) Unsubscribe() *DeltaSubscription_Unsubscribe_Call {
	return &DeltaSubscription_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe")}
}

func (_c *DeltaSubscription_Unsubscribe_Call) Run(run func()) *DeltaSubscription_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DeltaSubscription_Unsubscribe_Call) Return(_a0 error) *DeltaSubscription_Unsubscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DeltaSubscription_Unsubscribe_Call) RunAndReturn(run func() error) *DeltaSubscription_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewDeltaSubscription creates a new instance of DeltaSubscription. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeltaSubscription(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeltaSubscription {
	mock := &DeltaSubscription{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
