// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// DocumentBackend is an autogenerated mock type for the DocumentBackend type
type DocumentBackend struct {
	mock.Mock
}

type DocumentBackend_Expecter struct {
	mock *mock.Mock
}

func (_m *DocumentBackend) EXPECT() *DocumentBackend_Expecter {
	return &DocumentBackend_Expecter{mock: &_m.Mock}
}

// HandleDocumentOperation provides a mock function with given fields: _a0, _a1
func (_m *DocumentBackend) HandleDocumentOperation(_a0 context.Context, _a1 claims.InfrastructureBackendRequest[claims.DocumentOperationArtifactData]) (claims.DocumentOperationArtifactData, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for HandleDocumentOperation")
	}

	var r0 claims.DocumentOperationArtifactData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, claims.InfrastructureBackendRequest[claims.DocumentOperationArtifactData]) (claims.DocumentOperationArtifactData, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, claims.InfrastructureBackendRequest[claims.DocumentOperationArtifactData]) claims.DocumentOperationArtifactData); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(claims.DocumentOperationArtifactData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, claims.InfrastructureBackendRequest[claims.DocumentOperationArtifactData]) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DocumentBackend_HandleDocumentOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleDocumentOperation'
type DocumentBackend_HandleDocumentOperation_Call struct {
	*mock.Call
}

// HandleDocumentOperation is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 claims.InfrastructureBackendRequest[claims.DocumentOperationArtifactData]
func (_e *DocumentBackend_Expecter) HandleDocumentOperation(_a0 interface{}, _a1 interface{}) *DocumentBackend_HandleDocumentOperation_Call {
	return &DocumentBackend_HandleDocumentOperation_Call{Call: _e.mock.On("HandleDocumentOperation", _a0, _a1)}
}

func (_c *DocumentBackend_HandleDocumentOperation_Call) Run(run func(_a0 context.Context, _a1 claims.InfrastructureBackendRequest[claims.DocumentOperationArtifactData])) *DocumentBackend_HandleDocumentOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(claims.InfrastructureBackendRequest[claims.DocumentOperationArtifactData]))
	})
	return _c
}

func (_c *DocumentBackend_HandleDocumentOperation_Call) Return(_a0 claims.DocumentOperationArtifactData, _a1 error) *DocumentBackend_HandleDocumentOperation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DocumentBackend_HandleDocumentOperation_Call) RunAndReturn(run func(context.Context, claims.InfrastructureBackendRequest[claims.DocumentOperationArtifactData]) (claims.DocumentOperationArtifactData, error)) *DocumentBackend_HandleDocumentOperation_Call {
	_c.Call.Return(run)
	return _c
}

// NewDocumentBackend creates a new instance of DocumentBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDocumentBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *DocumentBackend {
	mock := &DocumentBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
