// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// ExpectedToolPolicy is an autogenerated mock type for the ExpectedToolPolicy type
type ExpectedToolPolicy struct {
	mock.Mock
}

type ExpectedToolPolicy_Expecter struct {
	mock *mock.Mock
}

func (_m *ExpectedToolPolicy) EXPECT() *ExpectedToolPolicy_Expecter {
	return &ExpectedToolPolicy_Expecter{mock: &_m.Mock}
}

// DecideExpectedTool provides a mock function with given fields: ctx, req
func (_m *ExpectedToolPolicy) DecideExpectedTool(ctx context.Context, req claims.ExpectedToolPolicyRequest) claims.ExpectedToolPolicyDecision {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for DecideExpectedTool")
	}

	var r0 claims.ExpectedToolPolicyDecision
	if rf, ok := ret.Get(0).(func(context.Context, claims.ExpectedToolPolicyRequest) claims.ExpectedToolPolicyDecision); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(claims.ExpectedToolPolicyDecision)
	}

	return r0
}

// ExpectedToolPolicy_DecideExpectedTool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecideExpectedTool'
type ExpectedToolPolicy_DecideExpectedTool_Call struct {
	*mock.Call
}

// DecideExpectedTool is a helper method to define mock.On call
//   - ctx context.Context
//   - req claims.ExpectedToolPolicyRequest
func (_e *ExpectedToolPolicy_Expecter) DecideExpectedTool(ctx interface{}, req interface{}) *ExpectedToolPolicy_DecideExpectedTool_Call {
	return &ExpectedToolPolicy_DecideExpectedTool_Call{Call: _e.mock.On("DecideExpectedTool", ctx, req)}
}

func (_c *ExpectedToolPolicy_DecideExpectedTool_Call) Run(run func(ctx context.Context, req claims.ExpectedToolPolicyRequest)) *ExpectedToolPolicy_DecideExpectedTool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(claims.ExpectedToolPolicyRequest))
	})
	return _c
}

func (_c *ExpectedToolPolicy_DecideExpectedTool_Call) Return(_a0 claims.ExpectedToolPolicyDecision) *ExpectedToolPolicy_DecideExpectedTool_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExpectedToolPolicy_DecideExpectedTool_Call) RunAndReturn(run func(context.Context, claims.ExpectedToolPolicyRequest) claims.ExpectedToolPolicyDecision) *ExpectedToolPolicy_DecideExpectedTool_Call {
	_c.Call.Return(run)
	return _c
}

// NewExpectedToolPolicy creates a new instance of ExpectedToolPolicy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExpectedToolPolicy(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExpectedToolPolicy {
	mock := &ExpectedToolPolicy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
