// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ClaimWorkCanceller is an autogenerated mock type for the ClaimWorkCanceller type
type ClaimWorkCanceller struct {
	mock.Mock
}

type ClaimWorkCanceller_Expecter struct {
	mock *mock.Mock
}

func (_m *ClaimWorkCanceller) EXPECT() *ClaimWorkCanceller_Expecter {
	return &ClaimWorkCanceller_Expecter{mock: &_m.Mock}
}

// CancelClaimWork provides a mock function with given fields: ctx, claimID, reason
func (_m *ClaimWorkCanceller) CancelClaimWork(ctx context.Context, claimID string, reason string) (bool, error) {
	ret := _m.Called(ctx, claimID, reason)

	if len(ret) == 0 {
		panic("no return value specified for CancelClaimWork")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, claimID, reason)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, claimID, reason)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, claimID, reason)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClaimWorkCanceller_CancelClaimWork_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelClaimWork'
type ClaimWorkCanceller_CancelClaimWork_Call struct {
	*mock.Call
}

// CancelClaimWork is a helper method to define mock.On call
//   - ctx context.Context
//   - claimID string
//   - reason string
func (_e *ClaimWorkCanceller_Expecter) CancelClaimWork(ctx interface{}, claimID interface{}, reason interface{}) *ClaimWorkCanceller_CancelClaimWork_Call {
	return &ClaimWorkCanceller_CancelClaimWork_Call{Call: _e.mock.On("CancelClaimWork", ctx, claimID, reason)}
}

func (_c *ClaimWorkCanceller_CancelClaimWork_Call) Run(run func(ctx context.Context, claimID string, reason string)) *ClaimWorkCanceller_CancelClaimWork_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ClaimWorkCanceller_CancelClaimWork_Call) Return(_a0 bool, _a1 error) *ClaimWorkCanceller_CancelClaimWork_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClaimWorkCanceller_CancelClaimWork_Call) RunAndReturn(run func(context.Context, string, string) (bool, error)) *ClaimWorkCanceller_CancelClaimWork_Call {
	_c.Call.Return(run)
	return _c
}

// NewClaimWorkCanceller creates a new instance of ClaimWorkCanceller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaimWorkCanceller(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClaimWorkCanceller {
	mock := &ClaimWorkCanceller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
