// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	claims "github.com/adalundhe/sylk/core/claims"
	mock "github.com/stretchr/testify/mock"
)

// DeltaPublisher is an autogenerated mock type for the DeltaPublisher type.
type DeltaPublisher struct{ mock.Mock }

func (_m *DeltaPublisher) PublishDelta(ctx context.Context, topic string, delta claims.Delta) error {
	ret := _m.Called(ctx, topic, delta)
	return ret.Error(0)
}

// DeltaSubscriber is an autogenerated mock type for the DeltaSubscriber type.
type DeltaSubscriber struct{ mock.Mock }

func (_m *DeltaSubscriber) SubscribeDelta(pattern string, handler claims.DeltaHandler) (claims.DeltaSubscription, error) {
	ret := _m.Called(pattern, handler)
	var r0 claims.DeltaSubscription
	if rf, ok := ret.Get(0).(func(string, claims.DeltaHandler) claims.DeltaSubscription); ok {
		r0 = rf(pattern, handler)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(claims.DeltaSubscription)
	}
	return r0, ret.Error(1)
}

// DeltaSubscription is an autogenerated mock type for the DeltaSubscription type.
type DeltaSubscription struct{ mock.Mock }

func (_m *DeltaSubscription) Topic() string {
	ret := _m.Called()
	return ret.String(0)
}

func (_m *DeltaSubscription) Unsubscribe() error {
	ret := _m.Called()
	return ret.Error(0)
}

// DeltaBus is an autogenerated mock type for the DeltaBus type.
type DeltaBus struct{ mock.Mock }

func (_m *DeltaBus) PublishDelta(ctx context.Context, topic string, delta claims.Delta) error {
	ret := _m.Called(ctx, topic, delta)
	return ret.Error(0)
}

func (_m *DeltaBus) SubscribeDelta(pattern string, handler claims.DeltaHandler) (claims.DeltaSubscription, error) {
	ret := _m.Called(pattern, handler)
	var r0 claims.DeltaSubscription
	if rf, ok := ret.Get(0).(func(string, claims.DeltaHandler) claims.DeltaSubscription); ok {
		r0 = rf(pattern, handler)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(claims.DeltaSubscription)
	}
	return r0, ret.Error(1)
}

// ClaimsProjector is an autogenerated mock type for the ClaimsProjector type.
type ClaimsProjector struct{ mock.Mock }

func (_m *ClaimsProjector) Name() string {
	ret := _m.Called()
	return ret.String(0)
}

func (_m *ClaimsProjector) Project(ctx context.Context, record *claims.ClaimsOutboxRecord, board *claims.ClaimsBoard) error {
	ret := _m.Called(ctx, record, board)
	return ret.Error(0)
}

// AgentRefResolver is an autogenerated mock type for the AgentRefResolver type.
type AgentRefResolver struct{ mock.Mock }

func (_m *AgentRefResolver) ResolveAgentRef(ctx context.Context, sessionID, agentID string) (claims.AgentRef, bool) {
	ret := _m.Called(ctx, sessionID, agentID)
	var r0 claims.AgentRef
	if rf, ok := ret.Get(0).(func(context.Context, string, string) claims.AgentRef); ok {
		r0 = rf(ctx, sessionID, agentID)
	} else {
		r0 = ret.Get(0).(claims.AgentRef)
	}
	return r0, ret.Bool(1)
}

// ClaimPostPolicy is an autogenerated mock type for the ClaimPostPolicy type.
type ClaimPostPolicy struct{ mock.Mock }

func (_m *ClaimPostPolicy) DecideClaimPost(ctx context.Context, req claims.ClaimPostPolicyRequest) claims.ClaimPostPolicyDecision {
	ret := _m.Called(ctx, req)
	if rf, ok := ret.Get(0).(func(context.Context, claims.ClaimPostPolicyRequest) claims.ClaimPostPolicyDecision); ok {
		return rf(ctx, req)
	}
	return ret.Get(0).(claims.ClaimPostPolicyDecision)
}

// ScopeProvider is an autogenerated mock type for the ScopeProvider type.
type ScopeProvider struct{ mock.Mock }

func (_m *ScopeProvider) Go(description string, timeout time.Duration, fn func(context.Context) error) error {
	ret := _m.Called(description, timeout, fn)
	return ret.Error(0)
}

// ServiceHandler is an autogenerated mock type for the ServiceHandler type.
type ServiceHandler struct{ mock.Mock }

func (_m *ServiceHandler) HandleServiceClaim(ctx context.Context, req claims.ServiceClaimRequest) (claims.ServiceClaimResult, error) {
	ret := _m.Called(ctx, req)
	var r0 claims.ServiceClaimResult
	if rf, ok := ret.Get(0).(func(context.Context, claims.ServiceClaimRequest) claims.ServiceClaimResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(claims.ServiceClaimResult)
	}
	return r0, ret.Error(1)
}

// ExpectedToolExecutor is an autogenerated mock type for the ExpectedToolExecutor type.
type ExpectedToolExecutor struct{ mock.Mock }

func (_m *ExpectedToolExecutor) ExecuteExpectedTool(ctx context.Context, call claims.ExpectedToolCall) (claims.ExpectedToolExecutionOutput, error) {
	ret := _m.Called(ctx, call)
	return ret.Get(0).(claims.ExpectedToolExecutionOutput), ret.Error(1)
}

// ExpectedToolPolicy is an autogenerated mock type for the ExpectedToolPolicy type.
type ExpectedToolPolicy struct{ mock.Mock }

func (_m *ExpectedToolPolicy) DecideExpectedTool(ctx context.Context, req claims.ExpectedToolPolicyRequest) claims.ExpectedToolPolicyDecision {
	ret := _m.Called(ctx, req)
	return ret.Get(0).(claims.ExpectedToolPolicyDecision)
}

// ExpectedToolArgumentRedactor is an autogenerated mock type for the ExpectedToolArgumentRedactor type.
type ExpectedToolArgumentRedactor struct{ mock.Mock }

func (_m *ExpectedToolArgumentRedactor) RedactExpectedToolArguments(ctx context.Context, tool string, args map[string]any) (map[string]any, error) {
	ret := _m.Called(ctx, tool, args)
	return ret.Get(0).(map[string]any), ret.Error(1)
}

// ValidationExpectedToolRemediationPoster is an autogenerated mock type for the ValidationExpectedToolRemediationPoster type.
type ValidationExpectedToolRemediationPoster struct{ mock.Mock }

func (_m *ValidationExpectedToolRemediationPoster) PostValidationExpectedToolRemediation(ctx context.Context, board *claims.ClaimsBoard, claim *claims.Claim, validation *claims.Validation, result *claims.ValidationExpectedToolExecutionResult) ([]string, error) {
	ret := _m.Called(ctx, board, claim, validation, result)
	return ret.Get(0).([]string), ret.Error(1)
}
