// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"
	mock "github.com/stretchr/testify/mock"
)

// ValidatorHandler is an autogenerated mock type for the ValidatorHandler type.
type ValidatorHandler struct {
	mock.Mock
}

func (_m *ValidatorHandler) ValidateArtifact(ctx context.Context, req claims.ValidatorHandlerRequest) (claims.ValidatorHandlerResult, error) {
	ret := _m.Called(ctx, req)
	if len(ret) == 0 {
		panic("no return value specified for ValidateArtifact")
	}

	var r0 claims.ValidatorHandlerResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, claims.ValidatorHandlerRequest) claims.ValidatorHandlerResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(claims.ValidatorHandlerResult)
	}
	if rf, ok := ret.Get(1).(func(context.Context, claims.ValidatorHandlerRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}
