// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"
	mock "github.com/stretchr/testify/mock"
)

// ValidationLifecycleBusSink is an autogenerated mock type for the ValidationLifecycleBusSink type.
type ValidationLifecycleBusSink struct {
	mock.Mock
}

func (_m *ValidationLifecycleBusSink) PublishValidationLifecycle(ctx context.Context, event claims.ValidationLifecycleEvent) error {
	ret := _m.Called(ctx, event)
	if len(ret) == 0 {
		panic("no return value specified for PublishValidationLifecycle")
	}
	if rf, ok := ret.Get(0).(func(context.Context, claims.ValidationLifecycleEvent) error); ok {
		return rf(ctx, event)
	}
	return ret.Error(0)
}
