// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	pool "github.com/adalundhe/sylk/core/pool"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PriorityPoolService is an autogenerated mock type for the PriorityPoolService type
type PriorityPoolService struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *PriorityPoolService) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Start provides a mock function with no fields
func (_m *PriorityPoolService) Start() {
	_m.Called()
}

// Stats provides a mock function with no fields
func (_m *PriorityPoolService) Stats() pool.PriorityPoolStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 pool.PriorityPoolStats
	if rf, ok := ret.Get(0).(func() pool.PriorityPoolStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(pool.PriorityPoolStats)
	}

	return r0
}

// Stop provides a mock function with no fields
func (_m *PriorityPoolService) Stop() {
	_m.Called()
}

// Submit provides a mock function with given fields: job
func (_m *PriorityPoolService) Submit(job *pool.PriorityJob) bool {
	ret := _m.Called(job)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*pool.PriorityJob) bool); ok {
		r0 = rf(job)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SubmitBlocking provides a mock function with given fields: job
func (_m *PriorityPoolService) SubmitBlocking(job *pool.PriorityJob) bool {
	ret := _m.Called(job)

	if len(ret) == 0 {
		panic("no return value specified for SubmitBlocking")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*pool.PriorityJob) bool); ok {
		r0 = rf(job)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// SubmitWithTimeout provides a mock function with given fields: job, timeout
func (_m *PriorityPoolService) SubmitWithTimeout(job *pool.PriorityJob, timeout time.Duration) bool {
	ret := _m.Called(job, timeout)

	if len(ret) == 0 {
		panic("no return value specified for SubmitWithTimeout")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*pool.PriorityJob, time.Duration) bool); ok {
		r0 = rf(job, timeout)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewPriorityPoolService creates a new instance of PriorityPoolService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPriorityPoolService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PriorityPoolService {
	mock := &PriorityPoolService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
