package academic

import (
	"strings"
	"testing"
)

func TestDefaultSystemPrompt_IncludesStructuredMarkdownFormattingGuidance(t *testing.T) {
	for _, want := range []string{
		"Assume your own background knowledge is incomplete by default.",
		"`web_search` is the default way to discover authoritative sources",
		"Once `web_search` surfaces a promising source",
		"Provider-native `web_search` is not just a title/snippet lookup",
		"When native `web_search` surfaces a clearly relevant, high-quality exact URL that you are about to carry forward as the decisive surfaced source",
		"Do not mechanically call `ground_source`, `web_fetch`, or `fetch_document` after every `web_search`.",
		"perform a source audit",
		"Confirm which cited URL is the decisive surfaced exact URL",
		"`ground_source` when you want Sylk to choose the fetch mode",
		"`web_fetch` for exact web pages or documentation pages",
		"`fetch_document` for PDFs, papers, benchmark reports, standards",
		"research multiple credible options before settling on one",
		"Do not begin substantial research by picking a winner.",
		"Identify the underlying domain or domains behind the request before narrowing to candidate answers.",
		"Build enough domain knowledge to reason inside that field",
		"research from the ground up before recommending anything",
		"authoritative primers, survey papers, review articles, standards, textbooks, professional society guidance, analyst or institutional research",
		"Use early searches to learn the field itself, not just to collect candidate options.",
		"Choose the evidence classes that matter for this domain",
		"Actively research the strongest negative case",
		"Treat self-authored, vendor-authored, or project-authored material as capability evidence first.",
		"seek independent corroboration or explicitly mark the conclusion as provisional and incomplete",
		"Do not rely on memory alone when the source could materially change the recommendation.",
		"prefer grounded quantitative evidence whenever feasible",
		"Do not quote percentages, benchmark results, incident rates, adoption figures, or study conclusions unless you actually inspected the underlying source in the current run",
		"include the measurement date and benchmark, study, or workload context",
		"treat the claim as qualitative or provisional instead of implying false precision",
		"Do not use unsupported adjectives such as",
		"Before sending any answer with citations or source links, perform a source audit",
		"prefer corroboration from multiple independently grounded sources whenever feasible",
		"find it and digest it",
		"evidence table, comparison matrix, or scored evaluation grid",
		"include a concrete architecture fragment, flow graph, or sequence sketch",
		"Aim for the depth of a top-tier internal research memo",
		"Perform your own technical analysis instead of only relaying source claims",
		"treat the response as incomplete unless it includes the following, when relevant",
		"evidence table, comparison matrix, or scored evaluation grid",
		"methodology digest, causal model, or risk register",
		"algorithm, formula, derivation, or math walkthrough",
		"a roundup, not research",
		"run a rigor audit against all of the following and treat every item as mandatory when relevant",
		"Competing options, counterarguments, and disconfirming evidence were examined",
		"Relevant evidence classes were covered or explicitly marked unavailable",
		"Confidence and certainty language were calibrated to evidence completeness",
		"Source bias, incentives, survivorship effects, and sampling bias were considered",
		"Write clear, readable markdown that a technical reader can immediately understand.",
		"Keep applicability and confidence easy to find, but do not let them displace the evidence",
		"Use proper markdown headings with a space after the heading markers",
		"Default structure for substantial recommendation answers",
		"Do not include a `Short Answer`, `Practical Shortlist`, or compressed winner section",
		"Decision Frame",
		"Evidence And Analysis",
		"they must still read like a thoughtful technical recommendation, not a stiff report template",
		"substantial research answers should be detailed enough to survive scrutiny from a senior engineer",
		"Do not write like a form with repeated `Applicability:` / `Confidence:` / `Why:` one-liners",
		"Do not open substantial externally sourced answers with a naked winner statement",
		"Do one explicit downside pass",
		"Do not let self-authored or vendor-authored sources carry a comparative conclusion by themselves",
		"keep the recommendation provisional rather than collapsing to a clean default",
		"Go one level deeper than a surface list of tools or options",
		"When comparing options, say which one you would actually choose and why the others lose",
		"Think like a PhD researcher or principal researcher evaluating design space",
		"include at least one proof-of-concept, prototype sketch, worked example, pseudo-interface, or architecture fragment",
		"Treat proof-of-concept examples as research/theoretical implementation sketches",
		"Do not stop at naming options, abstractions, or patterns; show how the preferred choice would actually look and behave",
		"When the recommendation depends on measured outcomes, surface the most decision-relevant grounded statistics",
		"When relevant studies, papers, systematic reviews, meta-analyses, professional research, institutional reports, or other field-defining material exist, actively look for them",
		"Do analysis, not just citation collection",
		"Do not end substantial research answers with generic variant menus or follow-up offers",
		"Do not let the `Summary / Decision Frame` collapse into a mini recommendation or `Short Answer`.",
		"## Decision Frame",
		"## Evidence And Analysis",
		"Architecture / System Design Implications",
		"## Recommendation",
		"## Fit For This Codebase",
		"## Caveats",
		"## Sources",
	} {
		if !strings.Contains(DefaultSystemPrompt, want) {
			t.Fatalf("default system prompt missing %q", want)
		}
	}
}

func TestAcademicConversationPrompt_IncludesScanFriendlyFormattingGuidance(t *testing.T) {
	for _, want := range []string{
		"For longer answers, use clean markdown sections",
		"Assume your own background knowledge is incomplete by default whenever current external facts",
		"`web_search` is the default way to discover authoritative sources for current and public claims",
		"Provider-native `web_search` is not just a title/snippet lookup",
		"Do not rely on memory alone when the source could materially change the recommendation.",
		"do not begin with a naked default recommendation",
		"Identify the underlying domain or domains behind the request before narrowing to candidate answers.",
		"Build enough domain knowledge to reason inside that field",
		"research from the ground up before recommending anything",
		"authoritative primers, survey papers, review articles, standards, textbooks, professional society guidance, analyst or institutional research",
		"Use early searches to learn the field itself, not just to collect candidate options.",
		"do not emit a `Short Answer`, shortlist, quick take, or final recommendation section until the evidence basis and comparison are established",
		"decision frame legible",
		"do not keep issuing more broad searches instead of examining it",
		"Once web_search surfaces a promising source, do not keep issuing more broad searches instead of examining it",
		"When native web_search surfaces a clearly relevant, high-quality exact URL that you are about to carry forward as the decisive surfaced source",
		"Do not mechanically call `ground_source`, `web_fetch`, or `fetch_document` after every web_search.",
		"`web_fetch` for exact web pages or documentation pages",
		"`fetch_document` for PDFs, papers, benchmark reports, standards",
		"confirm whether you are carrying forward a decisive surfaced exact URL from web_search",
		"Do not treat examining or grounding one URL from a site as permission to cite other URLs from the same site.",
		"corroborate them with multiple grounded sources whenever feasible",
		"Treat grounded evidence as immediately usable",
		"decision-relevant evidence classes for this domain",
		"look at multiple credible options before settling on one",
		"Do not stop after the first plausible answer unless the space is genuinely trivial.",
		"Do one explicit downside pass",
		"Treat self-authored, vendor-authored, or project-authored material as capability evidence first.",
		"seek independent corroboration or explicitly mark the conclusion as provisional and incomplete",
		"prefer grounded quantitative evidence whenever feasible",
		"back it with grounded, verifiable statistics whenever credible data exists",
		"decision-relevant measurable criteria for this domain",
		"Do not quote benchmark numbers, percentages, or study conclusions unless you actually inspected the source itself in the current run",
		"Confirm which cited URL is the decisive surfaced exact URL coming out of web_search",
		"note the source date and measurement context, and include sample size, workload shape, study design, or scope",
		"If the evidence is mostly qualitative, indirect, or stale, say so directly",
		"Do not justify a recommendation with vague phrases like",
		"Do not use unsupported adjectives such as",
		"build an explicit evaluation matrix that covers the criteria that actually matter to the decision",
		"release cadence, contributor or author activity, issue or defect backlog shape, support policy",
		"Popularity metrics are secondary indicators only; they do not prove superiority by themselves.",
		"Do not stop at surface positioning, abstracts, summaries, or snippets when deeper evidence is available.",
		"When relevant studies, papers, systematic reviews, meta-analyses, professional research, institutional reports, or other field-defining material exist, actively look for them",
		"When relevant literature exists, find it and digest it.",
		"include the strongest ones with digested summaries of method, findings, and limitations",
		"validate assumptions and hypotheses against the evidence",
		"source bias, sampling bias, survivorship bias, incentives, and threats to validity",
		"Treat recommendations without Librarian validation as incomplete.",
		"prefer side-by-side evidence tables, comparison matrices, methodology digests, risk registers, or architecture fragments",
		"Treat the answer as incomplete if it lacks the relevant structured artifact",
		"Make the relevant evidence classes explicit",
		"Do not give a shallow roundup that just names a winner",
		"Do not treat the answer as complete unless it includes multiple grounded sources for the important claims",
		"Do not treat the answer as complete unless it contains digested source synthesis",
		"validated assumptions or rejected hypotheses",
		"explicit limitations, bias risks, threats to validity, or weak spots in the evidence",
		"specialized, unfamiliar, or cross-domain topics include a clear domain frame",
		"Do not treat the answer as complete unless the important claims are backed by grounded sources",
		"Do not treat the answer as complete if relevant evidence classes were never checked or disclosed.",
		"Do not treat the answer as complete if the comparative conclusion is still driven mainly by self-authored or vendor-authored sources",
		"If benchmarks, measurements, datasets, or quantitative tradeoffs are materially relevant, surface them or explicitly say you could not validate them.",
		"surfaced-source grounding check: if the answer carries forward a decisive exact URL from web_search",
		"If the answer cites URLs, the decisive surfaced exact URL that carries the answer must have gone through the secured fetch path",
		"Do not treat the answer as complete if codebase-relevant recommendations were not validated against current codebase reality.",
		"Do not use high confidence unless multiple relevant evidence classes are covered",
		"Mandatory conversational rigor audit for substantial externally sourced answers",
		"Check whether important claims were corroborated across multiple grounded sources when feasible.",
		"Check whether the underlying domain or domains were identified and whether the field's core terminology, governing metrics, canonical sources, and evidence norms were mapped before narrowing to a conclusion.",
		"Check whether the answer evaluated competing hypotheses, alternatives, counterarguments, and disconfirming evidence.",
		"Check whether dataset quality, methodology quality, assumptions, and threats to validity were examined where relevant.",
		"Check whether source bias, incentives, survivorship effects, and sampling bias were considered where relevant.",
		"Check whether the relevant evidence classes were covered or explicitly marked unavailable",
		"Check whether confidence and certainty language were calibrated to evidence completeness",
		"Check whether codebase-relevant conclusions were validated against codebase reality and Librarian context.",
		"generic product or docs paraphrases",
		"unsupported adjectives standing in for evidence",
		"self-authored sources carrying a comparative conclusion by themselves",
		"Keep headings short and properly formatted.",
		"Prefer a small number of high-signal sections over sprawling outlines, but never compress away evidence, comparisons, caveats, or missing-data disclosure just to keep the answer short.",
		"Sound like you are thinking with the user, not filling out a recommendation form.",
		"After the evidence and comparison are established, make the recommendation explicit",
		"If multiple options are credible, explain why your preferred option beats the strongest alternative.",
		"Avoid laundry-list answers that read like scraped documentation summaries.",
		"Avoid closing substantial research answers with generic follow-up offers like \"If you want, I can ...\"",
		"Unless the user explicitly asks for brevity, answer with enough detail to justify the conclusion to another senior engineer or researcher.",
		"If the question is architectural, include system-design reasoning instead of stopping at component choice.",
		"Include a small proof-of-concept, prototype sketch, worked example, or pseudo-interface that shows how the preferred idea would work in practice.",
		"Keep that prototype at the level of research and theoretical implementation unless the user explicitly asks for production-ready code.",
		"For technology or design-choice questions, show what using the preferred option would actually look like instead of stopping at a named recommendation.",
		"When discussing architecture, reason from first principles and make the design legible to another senior engineer.",
		"Make the answer feel like a serious research memo or design note, not a thin executive summary.",
		"Do not sound promotional or summary-driven; sound like a staff-level researcher writing an internal technical memo.",
	} {
		if !strings.Contains(AcademicConversationPrompt, want) {
			t.Fatalf("conversation prompt missing %q", want)
		}
	}
}
