package claims

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestClaimsInfrastructureMockeryConfigNamesAllCrossPackageInterfaces(t *testing.T) {
	root := claimsRepoRoot(t)
	body := readClaimsFile(t, filepath.Join(root, ".mockery.yaml"))
	for _, name := range []string{
		"ValidationDispatcher",
		"ValidatorHandler",
		"AgentTurnEvaluator",
		"ArtifactLifecycleBusSink",
		"ValidationLifecycleBusSink",
		"ClaimsClock",
		"TestamentGenerator",
		"DeltaPublisher",
		"DeltaSubscriber",
		"DeltaSubscription",
		"DeltaBus",
		"ClaimsProjector",
		"AgentRefResolver",
		"ClaimPostPolicy",
		"ScopeProvider",
		"ServiceHandler",
		"ClaimPresentationSink",
		"ClaimArtifactSink",
	} {
		if !strings.Contains(body, "\n      "+name+":") && !strings.Contains(body, "\n      "+name+":\n") {
			t.Fatalf(".mockery.yaml missing claims infrastructure interface %s", name)
		}
	}
}

func TestClaimsInfrastructureGeneratedMocksCarryMockeryHeader(t *testing.T) {
	root := claimsRepoRoot(t)
	for _, rel := range []string{
		"core/claims/mocks/ValidationDispatcher.go",
		"core/claims/mocks/ValidatorHandler.go",
		"core/claims/mocks/OperationsInterfaces.go",
		"ui/bridge/mocks/ClaimPresentationSink.go",
		"ui/bridge/mocks/ClaimArtifactSink.go",
	} {
		body := readClaimsFile(t, filepath.Join(root, rel))
		if !strings.HasPrefix(body, "// Code generated by mockery. DO NOT EDIT.") {
			t.Fatalf("%s is missing mockery generated header", rel)
		}
	}
}

func claimsRepoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime caller unavailable")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(file), "..", ".."))
}

func readClaimsFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(data)
}
