// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CheckpointManager is an autogenerated mock type for the CheckpointManager type
type CheckpointManager struct {
	mock.Mock
}

// RestoreCheckpoint provides a mock function with given fields: pipelineID
func (_m *CheckpointManager) RestoreCheckpoint(pipelineID string) error {
	ret := _m.Called(pipelineID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreCheckpoint")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(pipelineID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCheckpointManager creates a new instance of CheckpointManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCheckpointManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *CheckpointManager {
	mock := &CheckpointManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
