// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GitManager is an autogenerated mock type for the GitManager type
type GitManager struct {
	mock.Mock
}

// CreateRevertCommit provides a mock function with given fields: pipelineID
func (_m *GitManager) CreateRevertCommit(pipelineID string) error {
	ret := _m.Called(pipelineID)

	if len(ret) == 0 {
		panic("no return value specified for CreateRevertCommit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(pipelineID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUnpushedCommits provides a mock function with given fields: pipelineID
func (_m *GitManager) GetUnpushedCommits(pipelineID string) (int, error) {
	ret := _m.Called(pipelineID)

	if len(ret) == 0 {
		panic("no return value specified for GetUnpushedCommits")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(pipelineID)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(pipelineID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pipelineID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HasPushedCommits provides a mock function with given fields: pipelineID
func (_m *GitManager) HasPushedCommits(pipelineID string) bool {
	ret := _m.Called(pipelineID)

	if len(ret) == 0 {
		panic("no return value specified for HasPushedCommits")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(pipelineID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ResetSoft provides a mock function with given fields: pipelineID, count
func (_m *GitManager) ResetSoft(pipelineID string, count int) error {
	ret := _m.Called(pipelineID, count)

	if len(ret) == 0 {
		panic("no return value specified for ResetSoft")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, int) error); ok {
		r0 = rf(pipelineID, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewGitManager creates a new instance of GitManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGitManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *GitManager {
	mock := &GitManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
