// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// StagingManager is an autogenerated mock type for the StagingManager type
type StagingManager struct {
	mock.Mock
}

// DiscardStaging provides a mock function with given fields: pipelineID
func (_m *StagingManager) DiscardStaging(pipelineID string) error {
	ret := _m.Called(pipelineID)

	if len(ret) == 0 {
		panic("no return value specified for DiscardStaging")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(pipelineID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetStagedFileCount provides a mock function with given fields: pipelineID
func (_m *StagingManager) GetStagedFileCount(pipelineID string) (int, error) {
	ret := _m.Called(pipelineID)

	if len(ret) == 0 {
		panic("no return value specified for GetStagedFileCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(pipelineID)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(pipelineID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pipelineID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStagingManager creates a new instance of StagingManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStagingManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *StagingManager {
	mock := &StagingManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
