// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"
	mock "github.com/stretchr/testify/mock"
)

type ClaimPresentationSink struct {
	mock.Mock
}

func (_m *ClaimPresentationSink) PublishClaimPresentation(ctx context.Context, claimID string, artifact *claims.Artifact) error {
	ret := _m.Called(ctx, claimID, artifact)
	if len(ret) == 0 {
		panic("no return value specified for PublishClaimPresentation")
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *claims.Artifact) error); ok {
		return rf(ctx, claimID, artifact)
	}
	return ret.Error(0)
}
