// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// ClaimPresentationSink is an autogenerated mock type for the ClaimPresentationSink type
type ClaimPresentationSink struct {
	mock.Mock
}

type ClaimPresentationSink_Expecter struct {
	mock *mock.Mock
}

func (_m *ClaimPresentationSink) EXPECT() *ClaimPresentationSink_Expecter {
	return &ClaimPresentationSink_Expecter{mock: &_m.Mock}
}

// PublishClaimPresentation provides a mock function with given fields: ctx, claimID, artifact
func (_m *ClaimPresentationSink) PublishClaimPresentation(ctx context.Context, claimID string, artifact *claims.Artifact) error {
	ret := _m.Called(ctx, claimID, artifact)

	if len(ret) == 0 {
		panic("no return value specified for PublishClaimPresentation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *claims.Artifact) error); ok {
		r0 = rf(ctx, claimID, artifact)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClaimPresentationSink_PublishClaimPresentation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishClaimPresentation'
type ClaimPresentationSink_PublishClaimPresentation_Call struct {
	*mock.Call
}

// PublishClaimPresentation is a helper method to define mock.On call
//   - ctx context.Context
//   - claimID string
//   - artifact *claims.Artifact
func (_e *ClaimPresentationSink_Expecter) PublishClaimPresentation(ctx interface{}, claimID interface{}, artifact interface{}) *ClaimPresentationSink_PublishClaimPresentation_Call {
	return &ClaimPresentationSink_PublishClaimPresentation_Call{Call: _e.mock.On("PublishClaimPresentation", ctx, claimID, artifact)}
}

func (_c *ClaimPresentationSink_PublishClaimPresentation_Call) Run(run func(ctx context.Context, claimID string, artifact *claims.Artifact)) *ClaimPresentationSink_PublishClaimPresentation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*claims.Artifact))
	})
	return _c
}

func (_c *ClaimPresentationSink_PublishClaimPresentation_Call) Return(_a0 error) *ClaimPresentationSink_PublishClaimPresentation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClaimPresentationSink_PublishClaimPresentation_Call) RunAndReturn(run func(context.Context, string, *claims.Artifact) error) *ClaimPresentationSink_PublishClaimPresentation_Call {
	_c.Call.Return(run)
	return _c
}

// NewClaimPresentationSink creates a new instance of ClaimPresentationSink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaimPresentationSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClaimPresentationSink {
	mock := &ClaimPresentationSink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
