// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	claims "github.com/adalundhe/sylk/core/claims"

	mock "github.com/stretchr/testify/mock"
)

// ClaimArtifactSink is an autogenerated mock type for the ClaimArtifactSink type
type ClaimArtifactSink struct {
	mock.Mock
}

type ClaimArtifactSink_Expecter struct {
	mock *mock.Mock
}

func (_m *ClaimArtifactSink) EXPECT() *ClaimArtifactSink_Expecter {
	return &ClaimArtifactSink_Expecter{mock: &_m.Mock}
}

// PublishClaimArtifact provides a mock function with given fields: ctx, claimID, artifact
func (_m *ClaimArtifactSink) PublishClaimArtifact(ctx context.Context, claimID string, artifact *claims.Artifact) error {
	ret := _m.Called(ctx, claimID, artifact)

	if len(ret) == 0 {
		panic("no return value specified for PublishClaimArtifact")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *claims.Artifact) error); ok {
		r0 = rf(ctx, claimID, artifact)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClaimArtifactSink_PublishClaimArtifact_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishClaimArtifact'
type ClaimArtifactSink_PublishClaimArtifact_Call struct {
	*mock.Call
}

// PublishClaimArtifact is a helper method to define mock.On call
//   - ctx context.Context
//   - claimID string
//   - artifact *claims.Artifact
func (_e *ClaimArtifactSink_Expecter) PublishClaimArtifact(ctx interface{}, claimID interface{}, artifact interface{}) *ClaimArtifactSink_PublishClaimArtifact_Call {
	return &ClaimArtifactSink_PublishClaimArtifact_Call{Call: _e.mock.On("PublishClaimArtifact", ctx, claimID, artifact)}
}

func (_c *ClaimArtifactSink_PublishClaimArtifact_Call) Run(run func(ctx context.Context, claimID string, artifact *claims.Artifact)) *ClaimArtifactSink_PublishClaimArtifact_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*claims.Artifact))
	})
	return _c
}

func (_c *ClaimArtifactSink_PublishClaimArtifact_Call) Return(_a0 error) *ClaimArtifactSink_PublishClaimArtifact_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClaimArtifactSink_PublishClaimArtifact_Call) RunAndReturn(run func(context.Context, string, *claims.Artifact) error) *ClaimArtifactSink_PublishClaimArtifact_Call {
	_c.Call.Return(run)
	return _c
}

// NewClaimArtifactSink creates a new instance of ClaimArtifactSink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClaimArtifactSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClaimArtifactSink {
	mock := &ClaimArtifactSink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
