// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	session "github.com/adalundhe/sylk/core/session"
	mock "github.com/stretchr/testify/mock"
)

// PersisterService is an autogenerated mock type for the PersisterService type
type PersisterService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *PersisterService) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with no fields
func (_m *PersisterService) List() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Load provides a mock function with given fields: id
func (_m *PersisterService) Load(id string) (*session.Session, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *session.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*session.Session, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *session.Session); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadAll provides a mock function with no fields
func (_m *PersisterService) LoadAll() ([]*session.Session, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadAll")
	}

	var r0 []*session.Session
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*session.Session, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*session.Session); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*session.Session)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: _a0
func (_m *PersisterService) Save(_a0 *session.Session) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*session.Session) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPersisterService creates a new instance of PersisterService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersisterService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PersisterService {
	mock := &PersisterService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
