// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	session "github.com/adalundhe/sylk/core/session"
	mock "github.com/stretchr/testify/mock"
)

// SessionManagerService is an autogenerated mock type for the SessionManagerService type
type SessionManagerService struct {
	mock.Mock
}

// Close provides a mock function with given fields: id
func (_m *SessionManagerService) Close(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CloseAll provides a mock function with no fields
func (_m *SessionManagerService) CloseAll() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Count provides a mock function with no fields
func (_m *SessionManagerService) Count() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, cfg
func (_m *SessionManagerService) Create(ctx context.Context, cfg session.Config) (*session.Session, error) {
	ret := _m.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *session.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, session.Config) (*session.Session, error)); ok {
		return rf(ctx, cfg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, session.Config) *session.Session); ok {
		r0 = rf(ctx, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, session.Config) error); ok {
		r1 = rf(ctx, cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: id
func (_m *SessionManagerService) Get(id string) (*session.Session, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *session.Session
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*session.Session, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *session.Session); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// GetActive provides a mock function with no fields
func (_m *SessionManagerService) GetActive() (*session.Session, bool) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActive")
	}

	var r0 *session.Session
	var r1 bool
	if rf, ok := ret.Get(0).(func() (*session.Session, bool)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *session.Session); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.Session)
		}
	}

	if rf, ok := ret.Get(1).(func() bool); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// List provides a mock function with no fields
func (_m *SessionManagerService) List() []*session.Session {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*session.Session
	if rf, ok := ret.Get(0).(func() []*session.Session); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*session.Session)
		}
	}

	return r0
}

// LoadSessions provides a mock function with no fields
func (_m *SessionManagerService) LoadSessions() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Pause provides a mock function with given fields: id
func (_m *SessionManagerService) Pause(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Pause")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Restore provides a mock function with given fields: id
func (_m *SessionManagerService) Restore(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Resume provides a mock function with given fields: id
func (_m *SessionManagerService) Resume(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetPersister provides a mock function with given fields: p
func (_m *SessionManagerService) SetPersister(p session.Persister) {
	_m.Called(p)
}

// Shutdown provides a mock function with no fields
func (_m *SessionManagerService) Shutdown() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stats provides a mock function with no fields
func (_m *SessionManagerService) Stats() session.ManagerStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 session.ManagerStats
	if rf, ok := ret.Get(0).(func() session.ManagerStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(session.ManagerStats)
	}

	return r0
}

// Subscribe provides a mock function with given fields: handler
func (_m *SessionManagerService) Subscribe(handler session.EventHandler) func() {
	ret := _m.Called(handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 func()
	if rf, ok := ret.Get(0).(func(session.EventHandler) func()); ok {
		r0 = rf(handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	return r0
}

// Suspend provides a mock function with given fields: id
func (_m *SessionManagerService) Suspend(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Suspend")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Switch provides a mock function with given fields: id
func (_m *SessionManagerService) Switch(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Switch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSessionManagerService creates a new instance of SessionManagerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionManagerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionManagerService {
	mock := &SessionManagerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
