// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	archivalist "github.com/adalundhe/sylk/agents/archivalist"
	mock "github.com/stretchr/testify/mock"
)

// MockRegistry is an autogenerated mock type for the RegistryService type
type MockRegistry struct {
	mock.Mock
}

type MockRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistry) EXPECT() *MockRegistry_Expecter {
	return &MockRegistry_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: id
func (_m *MockRegistry) Get(id string) *archivalist.RegisteredAgent {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *archivalist.RegisteredAgent
	if rf, ok := ret.Get(0).(func(string) *archivalist.RegisteredAgent); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*archivalist.RegisteredAgent)
		}
	}

	return r0
}

// MockRegistry_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRegistry_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *MockRegistry_Expecter) Get(id interface{}) *MockRegistry_Get_Call {
	return &MockRegistry_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockRegistry_Get_Call) Run(run func(id string)) *MockRegistry_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistry_Get_Call) Return(_a0 *archivalist.RegisteredAgent) *MockRegistry_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_Get_Call) RunAndReturn(run func(string) *archivalist.RegisteredAgent) *MockRegistry_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveAgents provides a mock function with no fields
func (_m *MockRegistry) GetActiveAgents() []*archivalist.RegisteredAgent {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActiveAgents")
	}

	var r0 []*archivalist.RegisteredAgent
	if rf, ok := ret.Get(0).(func() []*archivalist.RegisteredAgent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*archivalist.RegisteredAgent)
		}
	}

	return r0
}

// MockRegistry_GetActiveAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveAgents'
type MockRegistry_GetActiveAgents_Call struct {
	*mock.Call
}

// GetActiveAgents is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) GetActiveAgents() *MockRegistry_GetActiveAgents_Call {
	return &MockRegistry_GetActiveAgents_Call{Call: _e.mock.On("GetActiveAgents")}
}

func (_c *MockRegistry_GetActiveAgents_Call) Run(run func()) *MockRegistry_GetActiveAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_GetActiveAgents_Call) Return(_a0 []*archivalist.RegisteredAgent) *MockRegistry_GetActiveAgents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_GetActiveAgents_Call) RunAndReturn(run func() []*archivalist.RegisteredAgent) *MockRegistry_GetActiveAgents_Call {
	_c.Call.Return(run)
	return _c
}

// GetAgentHierarchy provides a mock function with given fields: id
func (_m *MockRegistry) GetAgentHierarchy(id string) []*archivalist.RegisteredAgent {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetAgentHierarchy")
	}

	var r0 []*archivalist.RegisteredAgent
	if rf, ok := ret.Get(0).(func(string) []*archivalist.RegisteredAgent); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*archivalist.RegisteredAgent)
		}
	}

	return r0
}

// MockRegistry_GetAgentHierarchy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgentHierarchy'
type MockRegistry_GetAgentHierarchy_Call struct {
	*mock.Call
}

// GetAgentHierarchy is a helper method to define mock.On call
//   - id string
func (_e *MockRegistry_Expecter) GetAgentHierarchy(id interface{}) *MockRegistry_GetAgentHierarchy_Call {
	return &MockRegistry_GetAgentHierarchy_Call{Call: _e.mock.On("GetAgentHierarchy", id)}
}

func (_c *MockRegistry_GetAgentHierarchy_Call) Run(run func(id string)) *MockRegistry_GetAgentHierarchy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistry_GetAgentHierarchy_Call) Return(_a0 []*archivalist.RegisteredAgent) *MockRegistry_GetAgentHierarchy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_GetAgentHierarchy_Call) RunAndReturn(run func(string) []*archivalist.RegisteredAgent) *MockRegistry_GetAgentHierarchy_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: name
func (_m *MockRegistry) GetByName(name string) *archivalist.RegisteredAgent {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *archivalist.RegisteredAgent
	if rf, ok := ret.Get(0).(func(string) *archivalist.RegisteredAgent); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*archivalist.RegisteredAgent)
		}
	}

	return r0
}

// MockRegistry_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockRegistry_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - name string
func (_e *MockRegistry_Expecter) GetByName(name interface{}) *MockRegistry_GetByName_Call {
	return &MockRegistry_GetByName_Call{Call: _e.mock.On("GetByName", name)}
}

func (_c *MockRegistry_GetByName_Call) Run(run func(name string)) *MockRegistry_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistry_GetByName_Call) Return(_a0 *archivalist.RegisteredAgent) *MockRegistry_GetByName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_GetByName_Call) RunAndReturn(run func(string) *archivalist.RegisteredAgent) *MockRegistry_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySession provides a mock function with given fields: sessionID
func (_m *MockRegistry) GetBySession(sessionID string) []*archivalist.RegisteredAgent {
	ret := _m.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySession")
	}

	var r0 []*archivalist.RegisteredAgent
	if rf, ok := ret.Get(0).(func(string) []*archivalist.RegisteredAgent); ok {
		r0 = rf(sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*archivalist.RegisteredAgent)
		}
	}

	return r0
}

// MockRegistry_GetBySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySession'
type MockRegistry_GetBySession_Call struct {
	*mock.Call
}

// GetBySession is a helper method to define mock.On call
//   - sessionID string
func (_e *MockRegistry_Expecter) GetBySession(sessionID interface{}) *MockRegistry_GetBySession_Call {
	return &MockRegistry_GetBySession_Call{Call: _e.mock.On("GetBySession", sessionID)}
}

func (_c *MockRegistry_GetBySession_Call) Run(run func(sessionID string)) *MockRegistry_GetBySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistry_GetBySession_Call) Return(_a0 []*archivalist.RegisteredAgent) *MockRegistry_GetBySession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_GetBySession_Call) RunAndReturn(run func(string) []*archivalist.RegisteredAgent) *MockRegistry_GetBySession_Call {
	_c.Call.Return(run)
	return _c
}

// GetDescendants provides a mock function with given fields: id
func (_m *MockRegistry) GetDescendants(id string) []*archivalist.RegisteredAgent {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetDescendants")
	}

	var r0 []*archivalist.RegisteredAgent
	if rf, ok := ret.Get(0).(func(string) []*archivalist.RegisteredAgent); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*archivalist.RegisteredAgent)
		}
	}

	return r0
}

// MockRegistry_GetDescendants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDescendants'
type MockRegistry_GetDescendants_Call struct {
	*mock.Call
}

// GetDescendants is a helper method to define mock.On call
//   - id string
func (_e *MockRegistry_Expecter) GetDescendants(id interface{}) *MockRegistry_GetDescendants_Call {
	return &MockRegistry_GetDescendants_Call{Call: _e.mock.On("GetDescendants", id)}
}

func (_c *MockRegistry_GetDescendants_Call) Run(run func(id string)) *MockRegistry_GetDescendants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistry_GetDescendants_Call) Return(_a0 []*archivalist.RegisteredAgent) *MockRegistry_GetDescendants_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_GetDescendants_Call) RunAndReturn(run func(string) []*archivalist.RegisteredAgent) *MockRegistry_GetDescendants_Call {
	_c.Call.Return(run)
	return _c
}

// GetGlobalClock provides a mock function with no fields
func (_m *MockRegistry) GetGlobalClock() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetGlobalClock")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// MockRegistry_GetGlobalClock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGlobalClock'
type MockRegistry_GetGlobalClock_Call struct {
	*mock.Call
}

// GetGlobalClock is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) GetGlobalClock() *MockRegistry_GetGlobalClock_Call {
	return &MockRegistry_GetGlobalClock_Call{Call: _e.mock.On("GetGlobalClock")}
}

func (_c *MockRegistry_GetGlobalClock_Call) Run(run func()) *MockRegistry_GetGlobalClock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_GetGlobalClock_Call) Return(_a0 uint64) *MockRegistry_GetGlobalClock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_GetGlobalClock_Call) RunAndReturn(run func() uint64) *MockRegistry_GetGlobalClock_Call {
	_c.Call.Return(run)
	return _c
}

// GetRootAgent provides a mock function with given fields: id
func (_m *MockRegistry) GetRootAgent(id string) *archivalist.RegisteredAgent {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetRootAgent")
	}

	var r0 *archivalist.RegisteredAgent
	if rf, ok := ret.Get(0).(func(string) *archivalist.RegisteredAgent); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*archivalist.RegisteredAgent)
		}
	}

	return r0
}

// MockRegistry_GetRootAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRootAgent'
type MockRegistry_GetRootAgent_Call struct {
	*mock.Call
}

// GetRootAgent is a helper method to define mock.On call
//   - id string
func (_e *MockRegistry_Expecter) GetRootAgent(id interface{}) *MockRegistry_GetRootAgent_Call {
	return &MockRegistry_GetRootAgent_Call{Call: _e.mock.On("GetRootAgent", id)}
}

func (_c *MockRegistry_GetRootAgent_Call) Run(run func(id string)) *MockRegistry_GetRootAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistry_GetRootAgent_Call) Return(_a0 *archivalist.RegisteredAgent) *MockRegistry_GetRootAgent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_GetRootAgent_Call) RunAndReturn(run func(string) *archivalist.RegisteredAgent) *MockRegistry_GetRootAgent_Call {
	_c.Call.Return(run)
	return _c
}

// GetStats provides a mock function with no fields
func (_m *MockRegistry) GetStats() archivalist.RegistryStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 archivalist.RegistryStats
	if rf, ok := ret.Get(0).(func() archivalist.RegistryStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(archivalist.RegistryStats)
	}

	return r0
}

// MockRegistry_GetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStats'
type MockRegistry_GetStats_Call struct {
	*mock.Call
}

// GetStats is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) GetStats() *MockRegistry_GetStats_Call {
	return &MockRegistry_GetStats_Call{Call: _e.mock.On("GetStats")}
}

func (_c *MockRegistry_GetStats_Call) Run(run func()) *MockRegistry_GetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_GetStats_Call) Return(_a0 archivalist.RegistryStats) *MockRegistry_GetStats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_GetStats_Call) RunAndReturn(run func() archivalist.RegistryStats) *MockRegistry_GetStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersion provides a mock function with no fields
func (_m *MockRegistry) GetVersion() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVersion")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockRegistry_GetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersion'
type MockRegistry_GetVersion_Call struct {
	*mock.Call
}

// GetVersion is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) GetVersion() *MockRegistry_GetVersion_Call {
	return &MockRegistry_GetVersion_Call{Call: _e.mock.On("GetVersion")}
}

func (_c *MockRegistry_GetVersion_Call) Run(run func()) *MockRegistry_GetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_GetVersion_Call) Return(_a0 string) *MockRegistry_GetVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_GetVersion_Call) RunAndReturn(run func() string) *MockRegistry_GetVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersionDelta provides a mock function with given fields: v
func (_m *MockRegistry) GetVersionDelta(v string) (int64, error) {
	ret := _m.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for GetVersionDelta")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(v)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(v)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegistry_GetVersionDelta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersionDelta'
type MockRegistry_GetVersionDelta_Call struct {
	*mock.Call
}

// GetVersionDelta is a helper method to define mock.On call
//   - v string
func (_e *MockRegistry_Expecter) GetVersionDelta(v interface{}) *MockRegistry_GetVersionDelta_Call {
	return &MockRegistry_GetVersionDelta_Call{Call: _e.mock.On("GetVersionDelta", v)}
}

func (_c *MockRegistry_GetVersionDelta_Call) Run(run func(v string)) *MockRegistry_GetVersionDelta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistry_GetVersionDelta_Call) Return(_a0 int64, _a1 error) *MockRegistry_GetVersionDelta_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegistry_GetVersionDelta_Call) RunAndReturn(run func(string) (int64, error)) *MockRegistry_GetVersionDelta_Call {
	_c.Call.Return(run)
	return _c
}

// GetVersionNumber provides a mock function with no fields
func (_m *MockRegistry) GetVersionNumber() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVersionNumber")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// MockRegistry_GetVersionNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVersionNumber'
type MockRegistry_GetVersionNumber_Call struct {
	*mock.Call
}

// GetVersionNumber is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) GetVersionNumber() *MockRegistry_GetVersionNumber_Call {
	return &MockRegistry_GetVersionNumber_Call{Call: _e.mock.On("GetVersionNumber")}
}

func (_c *MockRegistry_GetVersionNumber_Call) Run(run func()) *MockRegistry_GetVersionNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_GetVersionNumber_Call) Return(_a0 uint64) *MockRegistry_GetVersionNumber_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_GetVersionNumber_Call) RunAndReturn(run func() uint64) *MockRegistry_GetVersionNumber_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementGlobalClock provides a mock function with no fields
func (_m *MockRegistry) IncrementGlobalClock() uint64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IncrementGlobalClock")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func() uint64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// MockRegistry_IncrementGlobalClock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementGlobalClock'
type MockRegistry_IncrementGlobalClock_Call struct {
	*mock.Call
}

// IncrementGlobalClock is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) IncrementGlobalClock() *MockRegistry_IncrementGlobalClock_Call {
	return &MockRegistry_IncrementGlobalClock_Call{Call: _e.mock.On("IncrementGlobalClock")}
}

func (_c *MockRegistry_IncrementGlobalClock_Call) Run(run func()) *MockRegistry_IncrementGlobalClock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_IncrementGlobalClock_Call) Return(_a0 uint64) *MockRegistry_IncrementGlobalClock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_IncrementGlobalClock_Call) RunAndReturn(run func() uint64) *MockRegistry_IncrementGlobalClock_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementVersion provides a mock function with no fields
func (_m *MockRegistry) IncrementVersion() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IncrementVersion")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockRegistry_IncrementVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementVersion'
type MockRegistry_IncrementVersion_Call struct {
	*mock.Call
}

// IncrementVersion is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) IncrementVersion() *MockRegistry_IncrementVersion_Call {
	return &MockRegistry_IncrementVersion_Call{Call: _e.mock.On("IncrementVersion")}
}

func (_c *MockRegistry_IncrementVersion_Call) Run(run func()) *MockRegistry_IncrementVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_IncrementVersion_Call) Return(_a0 string) *MockRegistry_IncrementVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_IncrementVersion_Call) RunAndReturn(run func() string) *MockRegistry_IncrementVersion_Call {
	_c.Call.Return(run)
	return _c
}

// IsVersionCurrent provides a mock function with given fields: v
func (_m *MockRegistry) IsVersionCurrent(v string) bool {
	ret := _m.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for IsVersionCurrent")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockRegistry_IsVersionCurrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsVersionCurrent'
type MockRegistry_IsVersionCurrent_Call struct {
	*mock.Call
}

// IsVersionCurrent is a helper method to define mock.On call
//   - v string
func (_e *MockRegistry_Expecter) IsVersionCurrent(v interface{}) *MockRegistry_IsVersionCurrent_Call {
	return &MockRegistry_IsVersionCurrent_Call{Call: _e.mock.On("IsVersionCurrent", v)}
}

func (_c *MockRegistry_IsVersionCurrent_Call) Run(run func(v string)) *MockRegistry_IsVersionCurrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistry_IsVersionCurrent_Call) Return(_a0 bool) *MockRegistry_IsVersionCurrent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_IsVersionCurrent_Call) RunAndReturn(run func(string) bool) *MockRegistry_IsVersionCurrent_Call {
	_c.Call.Return(run)
	return _c
}

// ParseVersion provides a mock function with given fields: v
func (_m *MockRegistry) ParseVersion(v string) (uint64, error) {
	ret := _m.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for ParseVersion")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (uint64, error)); ok {
		return rf(v)
	}
	if rf, ok := ret.Get(0).(func(string) uint64); ok {
		r0 = rf(v)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(v)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegistry_ParseVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseVersion'
type MockRegistry_ParseVersion_Call struct {
	*mock.Call
}

// ParseVersion is a helper method to define mock.On call
//   - v string
func (_e *MockRegistry_Expecter) ParseVersion(v interface{}) *MockRegistry_ParseVersion_Call {
	return &MockRegistry_ParseVersion_Call{Call: _e.mock.On("ParseVersion", v)}
}

func (_c *MockRegistry_ParseVersion_Call) Run(run func(v string)) *MockRegistry_ParseVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistry_ParseVersion_Call) Return(_a0 uint64, _a1 error) *MockRegistry_ParseVersion_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegistry_ParseVersion_Call) RunAndReturn(run func(string) (uint64, error)) *MockRegistry_ParseVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: name, sessionID, parentID, source
func (_m *MockRegistry) Register(name string, sessionID string, parentID string, source archivalist.SourceModel) (*archivalist.RegisteredAgent, error) {
	ret := _m.Called(name, sessionID, parentID, source)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *archivalist.RegisteredAgent
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, archivalist.SourceModel) (*archivalist.RegisteredAgent, error)); ok {
		return rf(name, sessionID, parentID, source)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, archivalist.SourceModel) *archivalist.RegisteredAgent); ok {
		r0 = rf(name, sessionID, parentID, source)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*archivalist.RegisteredAgent)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, archivalist.SourceModel) error); ok {
		r1 = rf(name, sessionID, parentID, source)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRegistry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockRegistry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - name string
//   - sessionID string
//   - parentID string
//   - source archivalist.SourceModel
func (_e *MockRegistry_Expecter) Register(name interface{}, sessionID interface{}, parentID interface{}, source interface{}) *MockRegistry_Register_Call {
	return &MockRegistry_Register_Call{Call: _e.mock.On("Register", name, sessionID, parentID, source)}
}

func (_c *MockRegistry_Register_Call) Run(run func(name string, sessionID string, parentID string, source archivalist.SourceModel)) *MockRegistry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(archivalist.SourceModel))
	})
	return _c
}

func (_c *MockRegistry_Register_Call) Return(_a0 *archivalist.RegisteredAgent, _a1 error) *MockRegistry_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRegistry_Register_Call) RunAndReturn(run func(string, string, string, archivalist.SourceModel) (*archivalist.RegisteredAgent, error)) *MockRegistry_Register_Call {
	_c.Call.Return(run)
	return _c
}

// SyncClock provides a mock function with given fields: id, incomingClock
func (_m *MockRegistry) SyncClock(id string, incomingClock uint64) uint64 {
	ret := _m.Called(id, incomingClock)

	if len(ret) == 0 {
		panic("no return value specified for SyncClock")
	}

	var r0 uint64
	if rf, ok := ret.Get(0).(func(string, uint64) uint64); ok {
		r0 = rf(id, incomingClock)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	return r0
}

// MockRegistry_SyncClock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncClock'
type MockRegistry_SyncClock_Call struct {
	*mock.Call
}

// SyncClock is a helper method to define mock.On call
//   - id string
//   - incomingClock uint64
func (_e *MockRegistry_Expecter) SyncClock(id interface{}, incomingClock interface{}) *MockRegistry_SyncClock_Call {
	return &MockRegistry_SyncClock_Call{Call: _e.mock.On("SyncClock", id, incomingClock)}
}

func (_c *MockRegistry_SyncClock_Call) Run(run func(id string, incomingClock uint64)) *MockRegistry_SyncClock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(uint64))
	})
	return _c
}

func (_c *MockRegistry_SyncClock_Call) Return(_a0 uint64) *MockRegistry_SyncClock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_SyncClock_Call) RunAndReturn(run func(string, uint64) uint64) *MockRegistry_SyncClock_Call {
	_c.Call.Return(run)
	return _c
}

// Touch provides a mock function with given fields: id
func (_m *MockRegistry) Touch(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Touch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegistry_Touch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Touch'
type MockRegistry_Touch_Call struct {
	*mock.Call
}

// Touch is a helper method to define mock.On call
//   - id string
func (_e *MockRegistry_Expecter) Touch(id interface{}) *MockRegistry_Touch_Call {
	return &MockRegistry_Touch_Call{Call: _e.mock.On("Touch", id)}
}

func (_c *MockRegistry_Touch_Call) Run(run func(id string)) *MockRegistry_Touch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistry_Touch_Call) Return(_a0 error) *MockRegistry_Touch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_Touch_Call) RunAndReturn(run func(string) error) *MockRegistry_Touch_Call {
	_c.Call.Return(run)
	return _c
}

// Unregister provides a mock function with given fields: id
func (_m *MockRegistry) Unregister(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Unregister")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegistry_Unregister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unregister'
type MockRegistry_Unregister_Call struct {
	*mock.Call
}

// Unregister is a helper method to define mock.On call
//   - id string
func (_e *MockRegistry_Expecter) Unregister(id interface{}) *MockRegistry_Unregister_Call {
	return &MockRegistry_Unregister_Call{Call: _e.mock.On("Unregister", id)}
}

func (_c *MockRegistry_Unregister_Call) Run(run func(id string)) *MockRegistry_Unregister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistry_Unregister_Call) Return(_a0 error) *MockRegistry_Unregister_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_Unregister_Call) RunAndReturn(run func(string) error) *MockRegistry_Unregister_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatuses provides a mock function with no fields
func (_m *MockRegistry) UpdateStatuses() {
	_m.Called()
}

// MockRegistry_UpdateStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatuses'
type MockRegistry_UpdateStatuses_Call struct {
	*mock.Call
}

// UpdateStatuses is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) UpdateStatuses() *MockRegistry_UpdateStatuses_Call {
	return &MockRegistry_UpdateStatuses_Call{Call: _e.mock.On("UpdateStatuses")}
}

func (_c *MockRegistry_UpdateStatuses_Call) Run(run func()) *MockRegistry_UpdateStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_UpdateStatuses_Call) Return() *MockRegistry_UpdateStatuses_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRegistry_UpdateStatuses_Call) RunAndReturn(run func()) *MockRegistry_UpdateStatuses_Call {
	_c.Run(run)
	return _c
}

// UpdateVersion provides a mock function with given fields: id, version
func (_m *MockRegistry) UpdateVersion(id string, version string) error {
	ret := _m.Called(id, version)

	if len(ret) == 0 {
		panic("no return value specified for UpdateVersion")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRegistry_UpdateVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateVersion'
type MockRegistry_UpdateVersion_Call struct {
	*mock.Call
}

// UpdateVersion is a helper method to define mock.On call
//   - id string
//   - version string
func (_e *MockRegistry_Expecter) UpdateVersion(id interface{}, version interface{}) *MockRegistry_UpdateVersion_Call {
	return &MockRegistry_UpdateVersion_Call{Call: _e.mock.On("UpdateVersion", id, version)}
}

func (_c *MockRegistry_UpdateVersion_Call) Run(run func(id string, version string)) *MockRegistry_UpdateVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockRegistry_UpdateVersion_Call) Return(_a0 error) *MockRegistry_UpdateVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_UpdateVersion_Call) RunAndReturn(run func(string, string) error) *MockRegistry_UpdateVersion_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
