// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	archivalist "github.com/adalundhe/sylk/agents/archivalist"
	mock "github.com/stretchr/testify/mock"
)

// MockArchive is an autogenerated mock type for the ArchiveService type
type MockArchive struct {
	mock.Mock
}

type MockArchive_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArchive) EXPECT() *MockArchive_Expecter {
	return &MockArchive_Expecter{mock: &_m.Mock}
}

// ArchiveEntries provides a mock function with given fields: entries
func (_m *MockArchive) ArchiveEntries(entries []*archivalist.Entry) error {
	ret := _m.Called(entries)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveEntries")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*archivalist.Entry) error); ok {
		r0 = rf(entries)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockArchive_ArchiveEntries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveEntries'
type MockArchive_ArchiveEntries_Call struct {
	*mock.Call
}

// ArchiveEntries is a helper method to define mock.On call
//   - entries []*archivalist.Entry
func (_e *MockArchive_Expecter) ArchiveEntries(entries interface{}) *MockArchive_ArchiveEntries_Call {
	return &MockArchive_ArchiveEntries_Call{Call: _e.mock.On("ArchiveEntries", entries)}
}

func (_c *MockArchive_ArchiveEntries_Call) Run(run func(entries []*archivalist.Entry)) *MockArchive_ArchiveEntries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*archivalist.Entry))
	})
	return _c
}

func (_c *MockArchive_ArchiveEntries_Call) Return(_a0 error) *MockArchive_ArchiveEntries_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArchive_ArchiveEntries_Call) RunAndReturn(run func([]*archivalist.Entry) error) *MockArchive_ArchiveEntries_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockArchive) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockArchive_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockArchive_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockArchive_Expecter) Close() *MockArchive_Close_Call {
	return &MockArchive_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockArchive_Close_Call) Run(run func()) *MockArchive_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArchive_Close_Call) Return(_a0 error) *MockArchive_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArchive_Close_Call) RunAndReturn(run func() error) *MockArchive_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntry provides a mock function with given fields: id
func (_m *MockArchive) GetEntry(id string) (*archivalist.Entry, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetEntry")
	}

	var r0 *archivalist.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*archivalist.Entry, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *archivalist.Entry); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*archivalist.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArchive_GetEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntry'
type MockArchive_GetEntry_Call struct {
	*mock.Call
}

// GetEntry is a helper method to define mock.On call
//   - id string
func (_e *MockArchive_Expecter) GetEntry(id interface{}) *MockArchive_GetEntry_Call {
	return &MockArchive_GetEntry_Call{Call: _e.mock.On("GetEntry", id)}
}

func (_c *MockArchive_GetEntry_Call) Run(run func(id string)) *MockArchive_GetEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockArchive_GetEntry_Call) Return(_a0 *archivalist.Entry, _a1 error) *MockArchive_GetEntry_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockArchive_GetEntry_Call) RunAndReturn(run func(string) (*archivalist.Entry, error)) *MockArchive_GetEntry_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentSessions provides a mock function with given fields: limit
func (_m *MockArchive) GetRecentSessions(limit int) ([]*archivalist.Session, error) {
	ret := _m.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentSessions")
	}

	var r0 []*archivalist.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]*archivalist.Session, error)); ok {
		return rf(limit)
	}
	if rf, ok := ret.Get(0).(func(int) []*archivalist.Session); ok {
		r0 = rf(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*archivalist.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArchive_GetRecentSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentSessions'
type MockArchive_GetRecentSessions_Call struct {
	*mock.Call
}

// GetRecentSessions is a helper method to define mock.On call
//   - limit int
func (_e *MockArchive_Expecter) GetRecentSessions(limit interface{}) *MockArchive_GetRecentSessions_Call {
	return &MockArchive_GetRecentSessions_Call{Call: _e.mock.On("GetRecentSessions", limit)}
}

func (_c *MockArchive_GetRecentSessions_Call) Run(run func(limit int)) *MockArchive_GetRecentSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockArchive_GetRecentSessions_Call) Return(_a0 []*archivalist.Session, _a1 error) *MockArchive_GetRecentSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockArchive_GetRecentSessions_Call) RunAndReturn(run func(int) ([]*archivalist.Session, error)) *MockArchive_GetRecentSessions_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function with given fields: id
func (_m *MockArchive) GetSession(id string) (*archivalist.Session, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 *archivalist.Session
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*archivalist.Session, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *archivalist.Session); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*archivalist.Session)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArchive_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockArchive_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - id string
func (_e *MockArchive_Expecter) GetSession(id interface{}) *MockArchive_GetSession_Call {
	return &MockArchive_GetSession_Call{Call: _e.mock.On("GetSession", id)}
}

func (_c *MockArchive_GetSession_Call) Run(run func(id string)) *MockArchive_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockArchive_GetSession_Call) Return(_a0 *archivalist.Session, _a1 error) *MockArchive_GetSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockArchive_GetSession_Call) RunAndReturn(run func(string) (*archivalist.Session, error)) *MockArchive_GetSession_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: q
func (_m *MockArchive) Query(q archivalist.ArchiveQuery) ([]*archivalist.Entry, error) {
	ret := _m.Called(q)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []*archivalist.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(archivalist.ArchiveQuery) ([]*archivalist.Entry, error)); ok {
		return rf(q)
	}
	if rf, ok := ret.Get(0).(func(archivalist.ArchiveQuery) []*archivalist.Entry); ok {
		r0 = rf(q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*archivalist.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(archivalist.ArchiveQuery) error); ok {
		r1 = rf(q)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArchive_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockArchive_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - q archivalist.ArchiveQuery
func (_e *MockArchive_Expecter) Query(q interface{}) *MockArchive_Query_Call {
	return &MockArchive_Query_Call{Call: _e.mock.On("Query", q)}
}

func (_c *MockArchive_Query_Call) Run(run func(q archivalist.ArchiveQuery)) *MockArchive_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(archivalist.ArchiveQuery))
	})
	return _c
}

func (_c *MockArchive_Query_Call) Return(_a0 []*archivalist.Entry, _a1 error) *MockArchive_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockArchive_Query_Call) RunAndReturn(run func(archivalist.ArchiveQuery) ([]*archivalist.Entry, error)) *MockArchive_Query_Call {
	_c.Call.Return(run)
	return _c
}

// SaveSession provides a mock function with given fields: session
func (_m *MockArchive) SaveSession(session *archivalist.Session) error {
	ret := _m.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for SaveSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*archivalist.Session) error); ok {
		r0 = rf(session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockArchive_SaveSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveSession'
type MockArchive_SaveSession_Call struct {
	*mock.Call
}

// SaveSession is a helper method to define mock.On call
//   - session *archivalist.Session
func (_e *MockArchive_Expecter) SaveSession(session interface{}) *MockArchive_SaveSession_Call {
	return &MockArchive_SaveSession_Call{Call: _e.mock.On("SaveSession", session)}
}

func (_c *MockArchive_SaveSession_Call) Run(run func(session *archivalist.Session)) *MockArchive_SaveSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*archivalist.Session))
	})
	return _c
}

func (_c *MockArchive_SaveSession_Call) Return(_a0 error) *MockArchive_SaveSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArchive_SaveSession_Call) RunAndReturn(run func(*archivalist.Session) error) *MockArchive_SaveSession_Call {
	_c.Call.Return(run)
	return _c
}

// SearchText provides a mock function with given fields: text, limit
func (_m *MockArchive) SearchText(text string, limit int) ([]*archivalist.Entry, error) {
	ret := _m.Called(text, limit)

	if len(ret) == 0 {
		panic("no return value specified for SearchText")
	}

	var r0 []*archivalist.Entry
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]*archivalist.Entry, error)); ok {
		return rf(text, limit)
	}
	if rf, ok := ret.Get(0).(func(string, int) []*archivalist.Entry); ok {
		r0 = rf(text, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*archivalist.Entry)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(text, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArchive_SearchText_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchText'
type MockArchive_SearchText_Call struct {
	*mock.Call
}

// SearchText is a helper method to define mock.On call
//   - text string
//   - limit int
func (_e *MockArchive_Expecter) SearchText(text interface{}, limit interface{}) *MockArchive_SearchText_Call {
	return &MockArchive_SearchText_Call{Call: _e.mock.On("SearchText", text, limit)}
}

func (_c *MockArchive_SearchText_Call) Run(run func(text string, limit int)) *MockArchive_SearchText_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(int))
	})
	return _c
}

func (_c *MockArchive_SearchText_Call) Return(_a0 []*archivalist.Entry, _a1 error) *MockArchive_SearchText_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockArchive_SearchText_Call) RunAndReturn(run func(string, int) ([]*archivalist.Entry, error)) *MockArchive_SearchText_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function with no fields
func (_m *MockArchive) Stats() (map[string]int, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]int, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArchive_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockArchive_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockArchive_Expecter) Stats() *MockArchive_Stats_Call {
	return &MockArchive_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockArchive_Stats_Call) Run(run func()) *MockArchive_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArchive_Stats_Call) Return(_a0 map[string]int, _a1 error) *MockArchive_Stats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockArchive_Stats_Call) RunAndReturn(run func() (map[string]int, error)) *MockArchive_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockArchive creates a new instance of MockArchive. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArchive(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArchive {
	mock := &MockArchive{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
