// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	json "encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// MockToolHandler is an autogenerated mock type for the ToolHandlerService type
type MockToolHandler struct {
	mock.Mock
}

type MockToolHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockToolHandler) EXPECT() *MockToolHandler_Expecter {
	return &MockToolHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx, toolName, input
func (_m *MockToolHandler) Handle(ctx context.Context, toolName string, input json.RawMessage) (string, error) {
	ret := _m.Called(ctx, toolName, input)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, json.RawMessage) (string, error)); ok {
		return rf(ctx, toolName, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, json.RawMessage) string); ok {
		r0 = rf(ctx, toolName, input)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, json.RawMessage) error); ok {
		r1 = rf(ctx, toolName, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockToolHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockToolHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - toolName string
//   - input json.RawMessage
func (_e *MockToolHandler_Expecter) Handle(ctx interface{}, toolName interface{}, input interface{}) *MockToolHandler_Handle_Call {
	return &MockToolHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, toolName, input)}
}

func (_c *MockToolHandler_Handle_Call) Run(run func(ctx context.Context, toolName string, input json.RawMessage)) *MockToolHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(json.RawMessage))
	})
	return _c
}

func (_c *MockToolHandler_Handle_Call) Return(_a0 string, _a1 error) *MockToolHandler_Handle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockToolHandler_Handle_Call) RunAndReturn(run func(context.Context, string, json.RawMessage) (string, error)) *MockToolHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockToolHandler creates a new instance of MockToolHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockToolHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockToolHandler {
	mock := &MockToolHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
