// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	archivalist "github.com/adalundhe/sylk/agents/archivalist"
	mock "github.com/stretchr/testify/mock"
)

// MockEmbeddingStore is an autogenerated mock type for the EmbeddingStoreService type
type MockEmbeddingStore struct {
	mock.Mock
}

type MockEmbeddingStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbeddingStore) EXPECT() *MockEmbeddingStore_Expecter {
	return &MockEmbeddingStore_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockEmbeddingStore) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmbeddingStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockEmbeddingStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockEmbeddingStore_Expecter) Close() *MockEmbeddingStore_Close_Call {
	return &MockEmbeddingStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockEmbeddingStore_Close_Call) Run(run func()) *MockEmbeddingStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEmbeddingStore_Close_Call) Return(_a0 error) *MockEmbeddingStore_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmbeddingStore_Close_Call) RunAndReturn(run func() error) *MockEmbeddingStore_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBySession provides a mock function with given fields: sessionID
func (_m *MockEmbeddingStore) DeleteBySession(sessionID string) error {
	ret := _m.Called(sessionID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBySession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(sessionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmbeddingStore_DeleteBySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBySession'
type MockEmbeddingStore_DeleteBySession_Call struct {
	*mock.Call
}

// DeleteBySession is a helper method to define mock.On call
//   - sessionID string
func (_e *MockEmbeddingStore_Expecter) DeleteBySession(sessionID interface{}) *MockEmbeddingStore_DeleteBySession_Call {
	return &MockEmbeddingStore_DeleteBySession_Call{Call: _e.mock.On("DeleteBySession", sessionID)}
}

func (_c *MockEmbeddingStore_DeleteBySession_Call) Run(run func(sessionID string)) *MockEmbeddingStore_DeleteBySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEmbeddingStore_DeleteBySession_Call) Return(_a0 error) *MockEmbeddingStore_DeleteBySession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmbeddingStore_DeleteBySession_Call) RunAndReturn(run func(string) error) *MockEmbeddingStore_DeleteBySession_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: id
func (_m *MockEmbeddingStore) Get(id string) (*archivalist.EmbeddingEntry, []float32, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *archivalist.EmbeddingEntry
	var r1 []float32
	var r2 bool
	if rf, ok := ret.Get(0).(func(string) (*archivalist.EmbeddingEntry, []float32, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *archivalist.EmbeddingEntry); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*archivalist.EmbeddingEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) []float32); ok {
		r1 = rf(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]float32)
		}
	}

	if rf, ok := ret.Get(2).(func(string) bool); ok {
		r2 = rf(id)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// MockEmbeddingStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockEmbeddingStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *MockEmbeddingStore_Expecter) Get(id interface{}) *MockEmbeddingStore_Get_Call {
	return &MockEmbeddingStore_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockEmbeddingStore_Get_Call) Run(run func(id string)) *MockEmbeddingStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEmbeddingStore_Get_Call) Return(_a0 *archivalist.EmbeddingEntry, _a1 []float32, _a2 bool) *MockEmbeddingStore_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockEmbeddingStore_Get_Call) RunAndReturn(run func(string) (*archivalist.EmbeddingEntry, []float32, bool)) *MockEmbeddingStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// SearchSimilar provides a mock function with given fields: query, opts
func (_m *MockEmbeddingStore) SearchSimilar(query []float32, opts archivalist.SearchOptions) ([]*archivalist.ScoredEntry, error) {
	ret := _m.Called(query, opts)

	if len(ret) == 0 {
		panic("no return value specified for SearchSimilar")
	}

	var r0 []*archivalist.ScoredEntry
	var r1 error
	if rf, ok := ret.Get(0).(func([]float32, archivalist.SearchOptions) ([]*archivalist.ScoredEntry, error)); ok {
		return rf(query, opts)
	}
	if rf, ok := ret.Get(0).(func([]float32, archivalist.SearchOptions) []*archivalist.ScoredEntry); ok {
		r0 = rf(query, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*archivalist.ScoredEntry)
		}
	}

	if rf, ok := ret.Get(1).(func([]float32, archivalist.SearchOptions) error); ok {
		r1 = rf(query, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmbeddingStore_SearchSimilar_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchSimilar'
type MockEmbeddingStore_SearchSimilar_Call struct {
	*mock.Call
}

// SearchSimilar is a helper method to define mock.On call
//   - query []float32
//   - opts archivalist.SearchOptions
func (_e *MockEmbeddingStore_Expecter) SearchSimilar(query interface{}, opts interface{}) *MockEmbeddingStore_SearchSimilar_Call {
	return &MockEmbeddingStore_SearchSimilar_Call{Call: _e.mock.On("SearchSimilar", query, opts)}
}

func (_c *MockEmbeddingStore_SearchSimilar_Call) Run(run func(query []float32, opts archivalist.SearchOptions)) *MockEmbeddingStore_SearchSimilar_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]float32), args[1].(archivalist.SearchOptions))
	})
	return _c
}

func (_c *MockEmbeddingStore_SearchSimilar_Call) Return(_a0 []*archivalist.ScoredEntry, _a1 error) *MockEmbeddingStore_SearchSimilar_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmbeddingStore_SearchSimilar_Call) RunAndReturn(run func([]float32, archivalist.SearchOptions) ([]*archivalist.ScoredEntry, error)) *MockEmbeddingStore_SearchSimilar_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function with no fields
func (_m *MockEmbeddingStore) Stats() archivalist.EmbeddingStoreStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 archivalist.EmbeddingStoreStats
	if rf, ok := ret.Get(0).(func() archivalist.EmbeddingStoreStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(archivalist.EmbeddingStoreStats)
	}

	return r0
}

// MockEmbeddingStore_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockEmbeddingStore_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockEmbeddingStore_Expecter) Stats() *MockEmbeddingStore_Stats_Call {
	return &MockEmbeddingStore_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockEmbeddingStore_Stats_Call) Run(run func()) *MockEmbeddingStore_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEmbeddingStore_Stats_Call) Return(_a0 archivalist.EmbeddingStoreStats) *MockEmbeddingStore_Stats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmbeddingStore_Stats_Call) RunAndReturn(run func() archivalist.EmbeddingStoreStats) *MockEmbeddingStore_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: entry, embedding
func (_m *MockEmbeddingStore) Store(entry *archivalist.EmbeddingEntry, embedding []float32) error {
	ret := _m.Called(entry, embedding)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*archivalist.EmbeddingEntry, []float32) error); ok {
		r0 = rf(entry, embedding)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEmbeddingStore_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type MockEmbeddingStore_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - entry *archivalist.EmbeddingEntry
//   - embedding []float32
func (_e *MockEmbeddingStore_Expecter) Store(entry interface{}, embedding interface{}) *MockEmbeddingStore_Store_Call {
	return &MockEmbeddingStore_Store_Call{Call: _e.mock.On("Store", entry, embedding)}
}

func (_c *MockEmbeddingStore_Store_Call) Run(run func(entry *archivalist.EmbeddingEntry, embedding []float32)) *MockEmbeddingStore_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*archivalist.EmbeddingEntry), args[1].([]float32))
	})
	return _c
}

func (_c *MockEmbeddingStore_Store_Call) Return(_a0 error) *MockEmbeddingStore_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEmbeddingStore_Store_Call) RunAndReturn(run func(*archivalist.EmbeddingEntry, []float32) error) *MockEmbeddingStore_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmbeddingStore creates a new instance of MockEmbeddingStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbeddingStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbeddingStore {
	mock := &MockEmbeddingStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
