// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	archivalist "github.com/adalundhe/sylk/agents/archivalist"

	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the ClientService type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GenerateSummary provides a mock function with given fields: ctx, content
func (_m *MockClient) GenerateSummary(ctx context.Context, content string) (*archivalist.GeneratedSummary, error) {
	ret := _m.Called(ctx, content)

	if len(ret) == 0 {
		panic("no return value specified for GenerateSummary")
	}

	var r0 *archivalist.GeneratedSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*archivalist.GeneratedSummary, error)); ok {
		return rf(ctx, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *archivalist.GeneratedSummary); ok {
		r0 = rf(ctx, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*archivalist.GeneratedSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GenerateSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSummary'
type MockClient_GenerateSummary_Call struct {
	*mock.Call
}

// GenerateSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - content string
func (_e *MockClient_Expecter) GenerateSummary(ctx interface{}, content interface{}) *MockClient_GenerateSummary_Call {
	return &MockClient_GenerateSummary_Call{Call: _e.mock.On("GenerateSummary", ctx, content)}
}

func (_c *MockClient_GenerateSummary_Call) Run(run func(ctx context.Context, content string)) *MockClient_GenerateSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GenerateSummary_Call) Return(_a0 *archivalist.GeneratedSummary, _a1 error) *MockClient_GenerateSummary_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GenerateSummary_Call) RunAndReturn(run func(context.Context, string) (*archivalist.GeneratedSummary, error)) *MockClient_GenerateSummary_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateSummaryFromSubmissions provides a mock function with given fields: ctx, submissions
func (_m *MockClient) GenerateSummaryFromSubmissions(ctx context.Context, submissions []archivalist.Submission) (*archivalist.GeneratedSummary, error) {
	ret := _m.Called(ctx, submissions)

	if len(ret) == 0 {
		panic("no return value specified for GenerateSummaryFromSubmissions")
	}

	var r0 *archivalist.GeneratedSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []archivalist.Submission) (*archivalist.GeneratedSummary, error)); ok {
		return rf(ctx, submissions)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []archivalist.Submission) *archivalist.GeneratedSummary); ok {
		r0 = rf(ctx, submissions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*archivalist.GeneratedSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []archivalist.Submission) error); ok {
		r1 = rf(ctx, submissions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GenerateSummaryFromSubmissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateSummaryFromSubmissions'
type MockClient_GenerateSummaryFromSubmissions_Call struct {
	*mock.Call
}

// GenerateSummaryFromSubmissions is a helper method to define mock.On call
//   - ctx context.Context
//   - submissions []archivalist.Submission
func (_e *MockClient_Expecter) GenerateSummaryFromSubmissions(ctx interface{}, submissions interface{}) *MockClient_GenerateSummaryFromSubmissions_Call {
	return &MockClient_GenerateSummaryFromSubmissions_Call{Call: _e.mock.On("GenerateSummaryFromSubmissions", ctx, submissions)}
}

func (_c *MockClient_GenerateSummaryFromSubmissions_Call) Run(run func(ctx context.Context, submissions []archivalist.Submission)) *MockClient_GenerateSummaryFromSubmissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]archivalist.Submission))
	})
	return _c
}

func (_c *MockClient_GenerateSummaryFromSubmissions_Call) Return(_a0 *archivalist.GeneratedSummary, _a1 error) *MockClient_GenerateSummaryFromSubmissions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GenerateSummaryFromSubmissions_Call) RunAndReturn(run func(context.Context, []archivalist.Submission) (*archivalist.GeneratedSummary, error)) *MockClient_GenerateSummaryFromSubmissions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
