// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	archivalist "github.com/adalundhe/sylk/agents/archivalist"

	mock "github.com/stretchr/testify/mock"
)

// MockSemanticRetriever is an autogenerated mock type for the SemanticRetrieverService type
type MockSemanticRetriever struct {
	mock.Mock
}

type MockSemanticRetriever_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSemanticRetriever) EXPECT() *MockSemanticRetriever_Expecter {
	return &MockSemanticRetriever_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockSemanticRetriever) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSemanticRetriever_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSemanticRetriever_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockSemanticRetriever_Expecter) Close() *MockSemanticRetriever_Close_Call {
	return &MockSemanticRetriever_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockSemanticRetriever_Close_Call) Run(run func()) *MockSemanticRetriever_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSemanticRetriever_Close_Call) Return(_a0 error) *MockSemanticRetriever_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSemanticRetriever_Close_Call) RunAndReturn(run func() error) *MockSemanticRetriever_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockSemanticRetriever) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSemanticRetriever_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSemanticRetriever_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSemanticRetriever_Expecter) Delete(ctx interface{}, id interface{}) *MockSemanticRetriever_Delete_Call {
	return &MockSemanticRetriever_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSemanticRetriever_Delete_Call) Run(run func(ctx context.Context, id string)) *MockSemanticRetriever_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSemanticRetriever_Delete_Call) Return(_a0 error) *MockSemanticRetriever_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSemanticRetriever_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockSemanticRetriever_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Index provides a mock function with given fields: ctx, id, content, category, contentType, sessionID, metadata
func (_m *MockSemanticRetriever) Index(ctx context.Context, id string, content string, category string, contentType string, sessionID string, metadata map[string]interface{}) error {
	ret := _m.Called(ctx, id, content, category, contentType, sessionID, metadata)

	if len(ret) == 0 {
		panic("no return value specified for Index")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, id, content, category, contentType, sessionID, metadata)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSemanticRetriever_Index_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Index'
type MockSemanticRetriever_Index_Call struct {
	*mock.Call
}

// Index is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - content string
//   - category string
//   - contentType string
//   - sessionID string
//   - metadata map[string]interface{}
func (_e *MockSemanticRetriever_Expecter) Index(ctx interface{}, id interface{}, content interface{}, category interface{}, contentType interface{}, sessionID interface{}, metadata interface{}) *MockSemanticRetriever_Index_Call {
	return &MockSemanticRetriever_Index_Call{Call: _e.mock.On("Index", ctx, id, content, category, contentType, sessionID, metadata)}
}

func (_c *MockSemanticRetriever_Index_Call) Run(run func(ctx context.Context, id string, content string, category string, contentType string, sessionID string, metadata map[string]interface{})) *MockSemanticRetriever_Index_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(map[string]interface{}))
	})
	return _c
}

func (_c *MockSemanticRetriever_Index_Call) Return(_a0 error) *MockSemanticRetriever_Index_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSemanticRetriever_Index_Call) RunAndReturn(run func(context.Context, string, string, string, string, string, map[string]interface{}) error) *MockSemanticRetriever_Index_Call {
	_c.Call.Return(run)
	return _c
}

// Retrieve provides a mock function with given fields: ctx, query, opts
func (_m *MockSemanticRetriever) Retrieve(ctx context.Context, query string, opts archivalist.RetrievalOptions) ([]*archivalist.RetrievalResult, error) {
	ret := _m.Called(ctx, query, opts)

	if len(ret) == 0 {
		panic("no return value specified for Retrieve")
	}

	var r0 []*archivalist.RetrievalResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, archivalist.RetrievalOptions) ([]*archivalist.RetrievalResult, error)); ok {
		return rf(ctx, query, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, archivalist.RetrievalOptions) []*archivalist.RetrievalResult); ok {
		r0 = rf(ctx, query, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*archivalist.RetrievalResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, archivalist.RetrievalOptions) error); ok {
		r1 = rf(ctx, query, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSemanticRetriever_Retrieve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Retrieve'
type MockSemanticRetriever_Retrieve_Call struct {
	*mock.Call
}

// Retrieve is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - opts archivalist.RetrievalOptions
func (_e *MockSemanticRetriever_Expecter) Retrieve(ctx interface{}, query interface{}, opts interface{}) *MockSemanticRetriever_Retrieve_Call {
	return &MockSemanticRetriever_Retrieve_Call{Call: _e.mock.On("Retrieve", ctx, query, opts)}
}

func (_c *MockSemanticRetriever_Retrieve_Call) Run(run func(ctx context.Context, query string, opts archivalist.RetrievalOptions)) *MockSemanticRetriever_Retrieve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(archivalist.RetrievalOptions))
	})
	return _c
}

func (_c *MockSemanticRetriever_Retrieve_Call) Return(_a0 []*archivalist.RetrievalResult, _a1 error) *MockSemanticRetriever_Retrieve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSemanticRetriever_Retrieve_Call) RunAndReturn(run func(context.Context, string, archivalist.RetrievalOptions) ([]*archivalist.RetrievalResult, error)) *MockSemanticRetriever_Retrieve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSemanticRetriever creates a new instance of MockSemanticRetriever. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSemanticRetriever(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSemanticRetriever {
	mock := &MockSemanticRetriever{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
