// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	archivalist "github.com/adalundhe/sylk/agents/archivalist"
	mock "github.com/stretchr/testify/mock"
)

// MockMemoryManager is an autogenerated mock type for the MemoryManagerService type
type MockMemoryManager struct {
	mock.Mock
}

type MockMemoryManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMemoryManager) EXPECT() *MockMemoryManager_Expecter {
	return &MockMemoryManager_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: item
func (_m *MockMemoryManager) Add(item *archivalist.MemoryItem) error {
	ret := _m.Called(item)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*archivalist.MemoryItem) error); ok {
		r0 = rf(item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMemoryManager_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockMemoryManager_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - item *archivalist.MemoryItem
func (_e *MockMemoryManager_Expecter) Add(item interface{}) *MockMemoryManager_Add_Call {
	return &MockMemoryManager_Add_Call{Call: _e.mock.On("Add", item)}
}

func (_c *MockMemoryManager_Add_Call) Run(run func(item *archivalist.MemoryItem)) *MockMemoryManager_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*archivalist.MemoryItem))
	})
	return _c
}

func (_c *MockMemoryManager_Add_Call) Return(_a0 error) *MockMemoryManager_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemoryManager_Add_Call) RunAndReturn(run func(*archivalist.MemoryItem) error) *MockMemoryManager_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Demote provides a mock function with given fields: id
func (_m *MockMemoryManager) Demote(id string) {
	_m.Called(id)
}

// MockMemoryManager_Demote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Demote'
type MockMemoryManager_Demote_Call struct {
	*mock.Call
}

// Demote is a helper method to define mock.On call
//   - id string
func (_e *MockMemoryManager_Expecter) Demote(id interface{}) *MockMemoryManager_Demote_Call {
	return &MockMemoryManager_Demote_Call{Call: _e.mock.On("Demote", id)}
}

func (_c *MockMemoryManager_Demote_Call) Run(run func(id string)) *MockMemoryManager_Demote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMemoryManager_Demote_Call) Return() *MockMemoryManager_Demote_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMemoryManager_Demote_Call) RunAndReturn(run func(string)) *MockMemoryManager_Demote_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function with given fields: id
func (_m *MockMemoryManager) Get(id string) (*archivalist.MemoryItem, bool) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *archivalist.MemoryItem
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*archivalist.MemoryItem, bool)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *archivalist.MemoryItem); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*archivalist.MemoryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockMemoryManager_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMemoryManager_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *MockMemoryManager_Expecter) Get(id interface{}) *MockMemoryManager_Get_Call {
	return &MockMemoryManager_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockMemoryManager_Get_Call) Run(run func(id string)) *MockMemoryManager_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMemoryManager_Get_Call) Return(_a0 *archivalist.MemoryItem, _a1 bool) *MockMemoryManager_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMemoryManager_Get_Call) RunAndReturn(run func(string) (*archivalist.MemoryItem, bool)) *MockMemoryManager_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Promote provides a mock function with given fields: id
func (_m *MockMemoryManager) Promote(id string) {
	_m.Called(id)
}

// MockMemoryManager_Promote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Promote'
type MockMemoryManager_Promote_Call struct {
	*mock.Call
}

// Promote is a helper method to define mock.On call
//   - id string
func (_e *MockMemoryManager_Expecter) Promote(id interface{}) *MockMemoryManager_Promote_Call {
	return &MockMemoryManager_Promote_Call{Call: _e.mock.On("Promote", id)}
}

func (_c *MockMemoryManager_Promote_Call) Run(run func(id string)) *MockMemoryManager_Promote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMemoryManager_Promote_Call) Return() *MockMemoryManager_Promote_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMemoryManager_Promote_Call) RunAndReturn(run func(string)) *MockMemoryManager_Promote_Call {
	_c.Run(run)
	return _c
}

// Remove provides a mock function with given fields: id
func (_m *MockMemoryManager) Remove(id string) {
	_m.Called(id)
}

// MockMemoryManager_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockMemoryManager_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - id string
func (_e *MockMemoryManager_Expecter) Remove(id interface{}) *MockMemoryManager_Remove_Call {
	return &MockMemoryManager_Remove_Call{Call: _e.mock.On("Remove", id)}
}

func (_c *MockMemoryManager_Remove_Call) Run(run func(id string)) *MockMemoryManager_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMemoryManager_Remove_Call) Return() *MockMemoryManager_Remove_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMemoryManager_Remove_Call) RunAndReturn(run func(string)) *MockMemoryManager_Remove_Call {
	_c.Run(run)
	return _c
}

// Stats provides a mock function with no fields
func (_m *MockMemoryManager) Stats() archivalist.MemoryStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 archivalist.MemoryStats
	if rf, ok := ret.Get(0).(func() archivalist.MemoryStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(archivalist.MemoryStats)
	}

	return r0
}

// MockMemoryManager_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockMemoryManager_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockMemoryManager_Expecter) Stats() *MockMemoryManager_Stats_Call {
	return &MockMemoryManager_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockMemoryManager_Stats_Call) Run(run func()) *MockMemoryManager_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMemoryManager_Stats_Call) Return(_a0 archivalist.MemoryStats) *MockMemoryManager_Stats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMemoryManager_Stats_Call) RunAndReturn(run func() archivalist.MemoryStats) *MockMemoryManager_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMemoryManager creates a new instance of MockMemoryManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMemoryManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMemoryManager {
	mock := &MockMemoryManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
