// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	archivalist "github.com/adalundhe/sylk/agents/archivalist"
	mock "github.com/stretchr/testify/mock"
)

// MockConflictDetector is an autogenerated mock type for the ConflictDetectorService type
type MockConflictDetector struct {
	mock.Mock
}

type MockConflictDetector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConflictDetector) EXPECT() *MockConflictDetector_Expecter {
	return &MockConflictDetector_Expecter{mock: &_m.Mock}
}

// DetectConflict provides a mock function with given fields: scope, key, incoming, version, agentID
func (_m *MockConflictDetector) DetectConflict(scope archivalist.Scope, key string, incoming map[string]interface{}, version string, agentID string) *archivalist.ConflictResult {
	ret := _m.Called(scope, key, incoming, version, agentID)

	if len(ret) == 0 {
		panic("no return value specified for DetectConflict")
	}

	var r0 *archivalist.ConflictResult
	if rf, ok := ret.Get(0).(func(archivalist.Scope, string, map[string]interface{}, string, string) *archivalist.ConflictResult); ok {
		r0 = rf(scope, key, incoming, version, agentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*archivalist.ConflictResult)
		}
	}

	return r0
}

// MockConflictDetector_DetectConflict_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetectConflict'
type MockConflictDetector_DetectConflict_Call struct {
	*mock.Call
}

// DetectConflict is a helper method to define mock.On call
//   - scope archivalist.Scope
//   - key string
//   - incoming map[string]interface{}
//   - version string
//   - agentID string
func (_e *MockConflictDetector_Expecter) DetectConflict(scope interface{}, key interface{}, incoming interface{}, version interface{}, agentID interface{}) *MockConflictDetector_DetectConflict_Call {
	return &MockConflictDetector_DetectConflict_Call{Call: _e.mock.On("DetectConflict", scope, key, incoming, version, agentID)}
}

func (_c *MockConflictDetector_DetectConflict_Call) Run(run func(scope archivalist.Scope, key string, incoming map[string]interface{}, version string, agentID string)) *MockConflictDetector_DetectConflict_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(archivalist.Scope), args[1].(string), args[2].(map[string]interface{}), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockConflictDetector_DetectConflict_Call) Return(_a0 *archivalist.ConflictResult) *MockConflictDetector_DetectConflict_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConflictDetector_DetectConflict_Call) RunAndReturn(run func(archivalist.Scope, string, map[string]interface{}, string, string) *archivalist.ConflictResult) *MockConflictDetector_DetectConflict_Call {
	_c.Call.Return(run)
	return _c
}

// Resolve provides a mock function with given fields: result, existing, incoming
func (_m *MockConflictDetector) Resolve(result *archivalist.ConflictResult, existing map[string]interface{}, incoming map[string]interface{}) map[string]interface{} {
	ret := _m.Called(result, existing, incoming)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(*archivalist.ConflictResult, map[string]interface{}, map[string]interface{}) map[string]interface{}); ok {
		r0 = rf(result, existing, incoming)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// MockConflictDetector_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockConflictDetector_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - result *archivalist.ConflictResult
//   - existing map[string]interface{}
//   - incoming map[string]interface{}
func (_e *MockConflictDetector_Expecter) Resolve(result interface{}, existing interface{}, incoming interface{}) *MockConflictDetector_Resolve_Call {
	return &MockConflictDetector_Resolve_Call{Call: _e.mock.On("Resolve", result, existing, incoming)}
}

func (_c *MockConflictDetector_Resolve_Call) Run(run func(result *archivalist.ConflictResult, existing map[string]interface{}, incoming map[string]interface{})) *MockConflictDetector_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*archivalist.ConflictResult), args[1].(map[string]interface{}), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockConflictDetector_Resolve_Call) Return(_a0 map[string]interface{}) *MockConflictDetector_Resolve_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConflictDetector_Resolve_Call) RunAndReturn(run func(*archivalist.ConflictResult, map[string]interface{}, map[string]interface{}) map[string]interface{}) *MockConflictDetector_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConflictDetector creates a new instance of MockConflictDetector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConflictDetector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConflictDetector {
	mock := &MockConflictDetector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
