// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	archivalist "github.com/adalundhe/sylk/agents/archivalist"
	mock "github.com/stretchr/testify/mock"
)

// MockConflictHistory is an autogenerated mock type for the ConflictHistoryService type
type MockConflictHistory struct {
	mock.Mock
}

type MockConflictHistory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConflictHistory) EXPECT() *MockConflictHistory_Expecter {
	return &MockConflictHistory_Expecter{mock: &_m.Mock}
}

// GetRecent provides a mock function with given fields: n
func (_m *MockConflictHistory) GetRecent(n int) []*archivalist.ConflictRecord {
	ret := _m.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for GetRecent")
	}

	var r0 []*archivalist.ConflictRecord
	if rf, ok := ret.Get(0).(func(int) []*archivalist.ConflictRecord); ok {
		r0 = rf(n)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*archivalist.ConflictRecord)
		}
	}

	return r0
}

// MockConflictHistory_GetRecent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecent'
type MockConflictHistory_GetRecent_Call struct {
	*mock.Call
}

// GetRecent is a helper method to define mock.On call
//   - n int
func (_e *MockConflictHistory_Expecter) GetRecent(n interface{}) *MockConflictHistory_GetRecent_Call {
	return &MockConflictHistory_GetRecent_Call{Call: _e.mock.On("GetRecent", n)}
}

func (_c *MockConflictHistory_GetRecent_Call) Run(run func(n int)) *MockConflictHistory_GetRecent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockConflictHistory_GetRecent_Call) Return(_a0 []*archivalist.ConflictRecord) *MockConflictHistory_GetRecent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConflictHistory_GetRecent_Call) RunAndReturn(run func(int) []*archivalist.ConflictRecord) *MockConflictHistory_GetRecent_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnresolved provides a mock function with no fields
func (_m *MockConflictHistory) GetUnresolved() []*archivalist.ConflictRecord {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUnresolved")
	}

	var r0 []*archivalist.ConflictRecord
	if rf, ok := ret.Get(0).(func() []*archivalist.ConflictRecord); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*archivalist.ConflictRecord)
		}
	}

	return r0
}

// MockConflictHistory_GetUnresolved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnresolved'
type MockConflictHistory_GetUnresolved_Call struct {
	*mock.Call
}

// GetUnresolved is a helper method to define mock.On call
func (_e *MockConflictHistory_Expecter) GetUnresolved() *MockConflictHistory_GetUnresolved_Call {
	return &MockConflictHistory_GetUnresolved_Call{Call: _e.mock.On("GetUnresolved")}
}

func (_c *MockConflictHistory_GetUnresolved_Call) Run(run func()) *MockConflictHistory_GetUnresolved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConflictHistory_GetUnresolved_Call) Return(_a0 []*archivalist.ConflictRecord) *MockConflictHistory_GetUnresolved_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConflictHistory_GetUnresolved_Call) RunAndReturn(run func() []*archivalist.ConflictRecord) *MockConflictHistory_GetUnresolved_Call {
	_c.Call.Return(run)
	return _c
}

// Record provides a mock function with given fields: record
func (_m *MockConflictHistory) Record(record *archivalist.ConflictRecord) {
	_m.Called(record)
}

// MockConflictHistory_Record_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Record'
type MockConflictHistory_Record_Call struct {
	*mock.Call
}

// Record is a helper method to define mock.On call
//   - record *archivalist.ConflictRecord
func (_e *MockConflictHistory_Expecter) Record(record interface{}) *MockConflictHistory_Record_Call {
	return &MockConflictHistory_Record_Call{Call: _e.mock.On("Record", record)}
}

func (_c *MockConflictHistory_Record_Call) Run(run func(record *archivalist.ConflictRecord)) *MockConflictHistory_Record_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*archivalist.ConflictRecord))
	})
	return _c
}

func (_c *MockConflictHistory_Record_Call) Return() *MockConflictHistory_Record_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockConflictHistory_Record_Call) RunAndReturn(run func(*archivalist.ConflictRecord)) *MockConflictHistory_Record_Call {
	_c.Run(run)
	return _c
}

// NewMockConflictHistory creates a new instance of MockConflictHistory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConflictHistory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConflictHistory {
	mock := &MockConflictHistory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
