// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	providers "github.com/adalundhe/sylk/core/providers"
	mock "github.com/stretchr/testify/mock"
)

// MockStreamProvider is an autogenerated mock type for the StreamProvider type
type MockStreamProvider struct {
	mock.Mock
}

type MockStreamProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStreamProvider) EXPECT() *MockStreamProvider_Expecter {
	return &MockStreamProvider_Expecter{mock: &_m.Mock}
}

// Complete provides a mock function with given fields: ctx, req
func (_m *MockStreamProvider) Complete(ctx context.Context, req *providers.Request) (*providers.Response, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 *providers.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *providers.Request) (*providers.Response, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *providers.Request) *providers.Response); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providers.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *providers.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStreamProvider_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockStreamProvider_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - req *providers.Request
func (_e *MockStreamProvider_Expecter) Complete(ctx interface{}, req interface{}) *MockStreamProvider_Complete_Call {
	return &MockStreamProvider_Complete_Call{Call: _e.mock.On("Complete", ctx, req)}
}

func (_c *MockStreamProvider_Complete_Call) Run(run func(ctx context.Context, req *providers.Request)) *MockStreamProvider_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*providers.Request))
	})
	return _c
}

func (_c *MockStreamProvider_Complete_Call) Return(_a0 *providers.Response, _a1 error) *MockStreamProvider_Complete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStreamProvider_Complete_Call) RunAndReturn(run func(context.Context, *providers.Request) (*providers.Response, error)) *MockStreamProvider_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// CountTokens provides a mock function with given fields: messages
func (_m *MockStreamProvider) CountTokens(messages []providers.Message) (int, error) {
	ret := _m.Called(messages)

	if len(ret) == 0 {
		panic("no return value specified for CountTokens")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]providers.Message) (int, error)); ok {
		return rf(messages)
	}
	if rf, ok := ret.Get(0).(func([]providers.Message) int); ok {
		r0 = rf(messages)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]providers.Message) error); ok {
		r1 = rf(messages)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStreamProvider_CountTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountTokens'
type MockStreamProvider_CountTokens_Call struct {
	*mock.Call
}

// CountTokens is a helper method to define mock.On call
//   - messages []providers.Message
func (_e *MockStreamProvider_Expecter) CountTokens(messages interface{}) *MockStreamProvider_CountTokens_Call {
	return &MockStreamProvider_CountTokens_Call{Call: _e.mock.On("CountTokens", messages)}
}

func (_c *MockStreamProvider_CountTokens_Call) Run(run func(messages []providers.Message)) *MockStreamProvider_CountTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]providers.Message))
	})
	return _c
}

func (_c *MockStreamProvider_CountTokens_Call) Return(_a0 int, _a1 error) *MockStreamProvider_CountTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStreamProvider_CountTokens_Call) RunAndReturn(run func([]providers.Message) (int, error)) *MockStreamProvider_CountTokens_Call {
	_c.Call.Return(run)
	return _c
}

// HealthCheck provides a mock function with given fields: ctx
func (_m *MockStreamProvider) HealthCheck(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStreamProvider_HealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheck'
type MockStreamProvider_HealthCheck_Call struct {
	*mock.Call
}

// HealthCheck is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStreamProvider_Expecter) HealthCheck(ctx interface{}) *MockStreamProvider_HealthCheck_Call {
	return &MockStreamProvider_HealthCheck_Call{Call: _e.mock.On("HealthCheck", ctx)}
}

func (_c *MockStreamProvider_HealthCheck_Call) Run(run func(ctx context.Context)) *MockStreamProvider_HealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStreamProvider_HealthCheck_Call) Return(_a0 error) *MockStreamProvider_HealthCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStreamProvider_HealthCheck_Call) RunAndReturn(run func(context.Context) error) *MockStreamProvider_HealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// MaxContextTokens provides a mock function with given fields: model
func (_m *MockStreamProvider) MaxContextTokens(model string) int {
	ret := _m.Called(model)

	if len(ret) == 0 {
		panic("no return value specified for MaxContextTokens")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(model)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockStreamProvider_MaxContextTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxContextTokens'
type MockStreamProvider_MaxContextTokens_Call struct {
	*mock.Call
}

// MaxContextTokens is a helper method to define mock.On call
//   - model string
func (_e *MockStreamProvider_Expecter) MaxContextTokens(model interface{}) *MockStreamProvider_MaxContextTokens_Call {
	return &MockStreamProvider_MaxContextTokens_Call{Call: _e.mock.On("MaxContextTokens", model)}
}

func (_c *MockStreamProvider_MaxContextTokens_Call) Run(run func(model string)) *MockStreamProvider_MaxContextTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStreamProvider_MaxContextTokens_Call) Return(_a0 int) *MockStreamProvider_MaxContextTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStreamProvider_MaxContextTokens_Call) RunAndReturn(run func(string) int) *MockStreamProvider_MaxContextTokens_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *MockStreamProvider) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockStreamProvider_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockStreamProvider_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockStreamProvider_Expecter) Name() *MockStreamProvider_Name_Call {
	return &MockStreamProvider_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockStreamProvider_Name_Call) Run(run func()) *MockStreamProvider_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamProvider_Name_Call) Return(_a0 string) *MockStreamProvider_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStreamProvider_Name_Call) RunAndReturn(run func() string) *MockStreamProvider_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Stream provides a mock function with given fields: ctx, req
func (_m *MockStreamProvider) Stream(ctx context.Context, req *providers.Request) (<-chan *providers.StreamChunk, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 <-chan *providers.StreamChunk
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *providers.Request) (<-chan *providers.StreamChunk, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *providers.Request) <-chan *providers.StreamChunk); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *providers.StreamChunk)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *providers.Request) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStreamProvider_Stream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stream'
type MockStreamProvider_Stream_Call struct {
	*mock.Call
}

// Stream is a helper method to define mock.On call
//   - ctx context.Context
//   - req *providers.Request
func (_e *MockStreamProvider_Expecter) Stream(ctx interface{}, req interface{}) *MockStreamProvider_Stream_Call {
	return &MockStreamProvider_Stream_Call{Call: _e.mock.On("Stream", ctx, req)}
}

func (_c *MockStreamProvider_Stream_Call) Run(run func(ctx context.Context, req *providers.Request)) *MockStreamProvider_Stream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*providers.Request))
	})
	return _c
}

func (_c *MockStreamProvider_Stream_Call) Return(_a0 <-chan *providers.StreamChunk, _a1 error) *MockStreamProvider_Stream_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStreamProvider_Stream_Call) RunAndReturn(run func(context.Context, *providers.Request) (<-chan *providers.StreamChunk, error)) *MockStreamProvider_Stream_Call {
	_c.Call.Return(run)
	return _c
}

// StreamWithHandler provides a mock function with given fields: ctx, req, handler
func (_m *MockStreamProvider) StreamWithHandler(ctx context.Context, req *providers.Request, handler providers.StreamHandler) error {
	ret := _m.Called(ctx, req, handler)

	if len(ret) == 0 {
		panic("no return value specified for StreamWithHandler")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *providers.Request, providers.StreamHandler) error); ok {
		r0 = rf(ctx, req, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStreamProvider_StreamWithHandler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamWithHandler'
type MockStreamProvider_StreamWithHandler_Call struct {
	*mock.Call
}

// StreamWithHandler is a helper method to define mock.On call
//   - ctx context.Context
//   - req *providers.Request
//   - handler providers.StreamHandler
func (_e *MockStreamProvider_Expecter) StreamWithHandler(ctx interface{}, req interface{}, handler interface{}) *MockStreamProvider_StreamWithHandler_Call {
	return &MockStreamProvider_StreamWithHandler_Call{Call: _e.mock.On("StreamWithHandler", ctx, req, handler)}
}

func (_c *MockStreamProvider_StreamWithHandler_Call) Run(run func(ctx context.Context, req *providers.Request, handler providers.StreamHandler)) *MockStreamProvider_StreamWithHandler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*providers.Request), args[2].(providers.StreamHandler))
	})
	return _c
}

func (_c *MockStreamProvider_StreamWithHandler_Call) Return(_a0 error) *MockStreamProvider_StreamWithHandler_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStreamProvider_StreamWithHandler_Call) RunAndReturn(run func(context.Context, *providers.Request, providers.StreamHandler) error) *MockStreamProvider_StreamWithHandler_Call {
	_c.Call.Return(run)
	return _c
}

// SupportedModels provides a mock function with no fields
func (_m *MockStreamProvider) SupportedModels() []providers.ModelInfo {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportedModels")
	}

	var r0 []providers.ModelInfo
	if rf, ok := ret.Get(0).(func() []providers.ModelInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]providers.ModelInfo)
		}
	}

	return r0
}

// MockStreamProvider_SupportedModels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportedModels'
type MockStreamProvider_SupportedModels_Call struct {
	*mock.Call
}

// SupportedModels is a helper method to define mock.On call
func (_e *MockStreamProvider_Expecter) SupportedModels() *MockStreamProvider_SupportedModels_Call {
	return &MockStreamProvider_SupportedModels_Call{Call: _e.mock.On("SupportedModels")}
}

func (_c *MockStreamProvider_SupportedModels_Call) Run(run func()) *MockStreamProvider_SupportedModels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamProvider_SupportedModels_Call) Return(_a0 []providers.ModelInfo) *MockStreamProvider_SupportedModels_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStreamProvider_SupportedModels_Call) RunAndReturn(run func() []providers.ModelInfo) *MockStreamProvider_SupportedModels_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStreamProvider creates a new instance of MockStreamProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStreamProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamProvider {
	mock := &MockStreamProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
