// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dag "github.com/adalundhe/sylk/core/dag"
	mock "github.com/stretchr/testify/mock"
)

// ExecutorService is an autogenerated mock type for the ExecutorService type
type ExecutorService struct {
	mock.Mock
}

// Cancel provides a mock function with no fields
func (_m *ExecutorService) Cancel() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Execute provides a mock function with given fields: ctx, _a1, dispatcher
func (_m *ExecutorService) Execute(ctx context.Context, _a1 *dag.DAG, dispatcher dag.NodeDispatcher) (*dag.DAGResult, error) {
	ret := _m.Called(ctx, _a1, dispatcher)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *dag.DAGResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dag.DAG, dag.NodeDispatcher) (*dag.DAGResult, error)); ok {
		return rf(ctx, _a1, dispatcher)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dag.DAG, dag.NodeDispatcher) *dag.DAGResult); ok {
		r0 = rf(ctx, _a1, dispatcher)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dag.DAGResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dag.DAG, dag.NodeDispatcher) error); ok {
		r1 = rf(ctx, _a1, dispatcher)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Status provides a mock function with no fields
func (_m *ExecutorService) Status() *dag.DAGStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *dag.DAGStatus
	if rf, ok := ret.Get(0).(func() *dag.DAGStatus); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dag.DAGStatus)
		}
	}

	return r0
}

// Subscribe provides a mock function with given fields: handler
func (_m *ExecutorService) Subscribe(handler dag.EventHandler) func() {
	ret := _m.Called(handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 func()
	if rf, ok := ret.Get(0).(func(dag.EventHandler) func()); ok {
		r0 = rf(handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	return r0
}

// NewExecutorService creates a new instance of ExecutorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecutorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExecutorService {
	mock := &ExecutorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
