// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dag "github.com/adalundhe/sylk/core/dag"
	mock "github.com/stretchr/testify/mock"
)

// NodeDispatcherService is an autogenerated mock type for the NodeDispatcherService type
type NodeDispatcherService struct {
	mock.Mock
}

// Dispatch provides a mock function with given fields: ctx, node, parentResults
func (_m *NodeDispatcherService) Dispatch(ctx context.Context, node *dag.Node, parentResults map[string]*dag.NodeResult) (*dag.NodeResult, error) {
	ret := _m.Called(ctx, node, parentResults)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 *dag.NodeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dag.Node, map[string]*dag.NodeResult) (*dag.NodeResult, error)); ok {
		return rf(ctx, node, parentResults)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dag.Node, map[string]*dag.NodeResult) *dag.NodeResult); ok {
		r0 = rf(ctx, node, parentResults)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dag.NodeResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dag.Node, map[string]*dag.NodeResult) error); ok {
		r1 = rf(ctx, node, parentResults)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNodeDispatcherService creates a new instance of NodeDispatcherService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNodeDispatcherService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NodeDispatcherService {
	mock := &NodeDispatcherService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
