// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	dag "github.com/adalundhe/sylk/core/dag"
	mock "github.com/stretchr/testify/mock"
)

// SchedulerService is an autogenerated mock type for the SchedulerService type
type SchedulerService struct {
	mock.Mock
}

// Cancel provides a mock function with given fields: id
func (_m *SchedulerService) Cancel(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with no fields
func (_m *SchedulerService) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with no fields
func (_m *SchedulerService) List() []*dag.DAGStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*dag.DAGStatus
	if rf, ok := ret.Get(0).(func() []*dag.DAGStatus); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dag.DAGStatus)
		}
	}

	return r0
}

// Stats provides a mock function with no fields
func (_m *SchedulerService) Stats() dag.SchedulerStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 dag.SchedulerStats
	if rf, ok := ret.Get(0).(func() dag.SchedulerStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(dag.SchedulerStats)
	}

	return r0
}

// Status provides a mock function with given fields: id
func (_m *SchedulerService) Status(id string) (*dag.DAGStatus, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *dag.DAGStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*dag.DAGStatus, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *dag.DAGStatus); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dag.DAGStatus)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Submit provides a mock function with given fields: ctx, _a1, dispatcher
func (_m *SchedulerService) Submit(ctx context.Context, _a1 *dag.DAG, dispatcher dag.NodeDispatcher) (string, error) {
	ret := _m.Called(ctx, _a1, dispatcher)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dag.DAG, dag.NodeDispatcher) (string, error)); ok {
		return rf(ctx, _a1, dispatcher)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dag.DAG, dag.NodeDispatcher) string); ok {
		r0 = rf(ctx, _a1, dispatcher)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dag.DAG, dag.NodeDispatcher) error); ok {
		r1 = rf(ctx, _a1, dispatcher)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SubmitAndWait provides a mock function with given fields: ctx, _a1, dispatcher
func (_m *SchedulerService) SubmitAndWait(ctx context.Context, _a1 *dag.DAG, dispatcher dag.NodeDispatcher) (*dag.DAGResult, error) {
	ret := _m.Called(ctx, _a1, dispatcher)

	if len(ret) == 0 {
		panic("no return value specified for SubmitAndWait")
	}

	var r0 *dag.DAGResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *dag.DAG, dag.NodeDispatcher) (*dag.DAGResult, error)); ok {
		return rf(ctx, _a1, dispatcher)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dag.DAG, dag.NodeDispatcher) *dag.DAGResult); ok {
		r0 = rf(ctx, _a1, dispatcher)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dag.DAGResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dag.DAG, dag.NodeDispatcher) error); ok {
		r1 = rf(ctx, _a1, dispatcher)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Subscribe provides a mock function with given fields: handler
func (_m *SchedulerService) Subscribe(handler dag.EventHandler) func() {
	ret := _m.Called(handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 func()
	if rf, ok := ret.Get(0).(func(dag.EventHandler) func()); ok {
		r0 = rf(handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	return r0
}

// NewSchedulerService creates a new instance of SchedulerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSchedulerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SchedulerService {
	mock := &SchedulerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
