// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockArchivableHandoffState is an autogenerated mock type for the ArchivableHandoffState type
type MockArchivableHandoffState struct {
	mock.Mock
}

type MockArchivableHandoffState_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArchivableHandoffState) EXPECT() *MockArchivableHandoffState_Expecter {
	return &MockArchivableHandoffState_Expecter{mock: &_m.Mock}
}

// GetAgentID provides a mock function with no fields
func (_m *MockArchivableHandoffState) GetAgentID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAgentID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockArchivableHandoffState_GetAgentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgentID'
type MockArchivableHandoffState_GetAgentID_Call struct {
	*mock.Call
}

// GetAgentID is a helper method to define mock.On call
func (_e *MockArchivableHandoffState_Expecter) GetAgentID() *MockArchivableHandoffState_GetAgentID_Call {
	return &MockArchivableHandoffState_GetAgentID_Call{Call: _e.mock.On("GetAgentID")}
}

func (_c *MockArchivableHandoffState_GetAgentID_Call) Run(run func()) *MockArchivableHandoffState_GetAgentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArchivableHandoffState_GetAgentID_Call) Return(_a0 string) *MockArchivableHandoffState_GetAgentID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArchivableHandoffState_GetAgentID_Call) RunAndReturn(run func() string) *MockArchivableHandoffState_GetAgentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAgentType provides a mock function with no fields
func (_m *MockArchivableHandoffState) GetAgentType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAgentType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockArchivableHandoffState_GetAgentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgentType'
type MockArchivableHandoffState_GetAgentType_Call struct {
	*mock.Call
}

// GetAgentType is a helper method to define mock.On call
func (_e *MockArchivableHandoffState_Expecter) GetAgentType() *MockArchivableHandoffState_GetAgentType_Call {
	return &MockArchivableHandoffState_GetAgentType_Call{Call: _e.mock.On("GetAgentType")}
}

func (_c *MockArchivableHandoffState_GetAgentType_Call) Run(run func()) *MockArchivableHandoffState_GetAgentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArchivableHandoffState_GetAgentType_Call) Return(_a0 string) *MockArchivableHandoffState_GetAgentType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArchivableHandoffState_GetAgentType_Call) RunAndReturn(run func() string) *MockArchivableHandoffState_GetAgentType_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompletedAt provides a mock function with no fields
func (_m *MockArchivableHandoffState) GetCompletedAt() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCompletedAt")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MockArchivableHandoffState_GetCompletedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompletedAt'
type MockArchivableHandoffState_GetCompletedAt_Call struct {
	*mock.Call
}

// GetCompletedAt is a helper method to define mock.On call
func (_e *MockArchivableHandoffState_Expecter) GetCompletedAt() *MockArchivableHandoffState_GetCompletedAt_Call {
	return &MockArchivableHandoffState_GetCompletedAt_Call{Call: _e.mock.On("GetCompletedAt")}
}

func (_c *MockArchivableHandoffState_GetCompletedAt_Call) Run(run func()) *MockArchivableHandoffState_GetCompletedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArchivableHandoffState_GetCompletedAt_Call) Return(_a0 time.Time) *MockArchivableHandoffState_GetCompletedAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArchivableHandoffState_GetCompletedAt_Call) RunAndReturn(run func() time.Time) *MockArchivableHandoffState_GetCompletedAt_Call {
	_c.Call.Return(run)
	return _c
}

// GetHandoffIndex provides a mock function with no fields
func (_m *MockArchivableHandoffState) GetHandoffIndex() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHandoffIndex")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockArchivableHandoffState_GetHandoffIndex_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHandoffIndex'
type MockArchivableHandoffState_GetHandoffIndex_Call struct {
	*mock.Call
}

// GetHandoffIndex is a helper method to define mock.On call
func (_e *MockArchivableHandoffState_Expecter) GetHandoffIndex() *MockArchivableHandoffState_GetHandoffIndex_Call {
	return &MockArchivableHandoffState_GetHandoffIndex_Call{Call: _e.mock.On("GetHandoffIndex")}
}

func (_c *MockArchivableHandoffState_GetHandoffIndex_Call) Run(run func()) *MockArchivableHandoffState_GetHandoffIndex_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArchivableHandoffState_GetHandoffIndex_Call) Return(_a0 int) *MockArchivableHandoffState_GetHandoffIndex_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArchivableHandoffState_GetHandoffIndex_Call) RunAndReturn(run func() int) *MockArchivableHandoffState_GetHandoffIndex_Call {
	_c.Call.Return(run)
	return _c
}

// GetPipelineID provides a mock function with no fields
func (_m *MockArchivableHandoffState) GetPipelineID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPipelineID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockArchivableHandoffState_GetPipelineID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPipelineID'
type MockArchivableHandoffState_GetPipelineID_Call struct {
	*mock.Call
}

// GetPipelineID is a helper method to define mock.On call
func (_e *MockArchivableHandoffState_Expecter) GetPipelineID() *MockArchivableHandoffState_GetPipelineID_Call {
	return &MockArchivableHandoffState_GetPipelineID_Call{Call: _e.mock.On("GetPipelineID")}
}

func (_c *MockArchivableHandoffState_GetPipelineID_Call) Run(run func()) *MockArchivableHandoffState_GetPipelineID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArchivableHandoffState_GetPipelineID_Call) Return(_a0 string) *MockArchivableHandoffState_GetPipelineID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArchivableHandoffState_GetPipelineID_Call) RunAndReturn(run func() string) *MockArchivableHandoffState_GetPipelineID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSessionID provides a mock function with no fields
func (_m *MockArchivableHandoffState) GetSessionID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSessionID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockArchivableHandoffState_GetSessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionID'
type MockArchivableHandoffState_GetSessionID_Call struct {
	*mock.Call
}

// GetSessionID is a helper method to define mock.On call
func (_e *MockArchivableHandoffState_Expecter) GetSessionID() *MockArchivableHandoffState_GetSessionID_Call {
	return &MockArchivableHandoffState_GetSessionID_Call{Call: _e.mock.On("GetSessionID")}
}

func (_c *MockArchivableHandoffState_GetSessionID_Call) Run(run func()) *MockArchivableHandoffState_GetSessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArchivableHandoffState_GetSessionID_Call) Return(_a0 string) *MockArchivableHandoffState_GetSessionID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArchivableHandoffState_GetSessionID_Call) RunAndReturn(run func() string) *MockArchivableHandoffState_GetSessionID_Call {
	_c.Call.Return(run)
	return _c
}

// GetStartedAt provides a mock function with no fields
func (_m *MockArchivableHandoffState) GetStartedAt() time.Time {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStartedAt")
	}

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// MockArchivableHandoffState_GetStartedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStartedAt'
type MockArchivableHandoffState_GetStartedAt_Call struct {
	*mock.Call
}

// GetStartedAt is a helper method to define mock.On call
func (_e *MockArchivableHandoffState_Expecter) GetStartedAt() *MockArchivableHandoffState_GetStartedAt_Call {
	return &MockArchivableHandoffState_GetStartedAt_Call{Call: _e.mock.On("GetStartedAt")}
}

func (_c *MockArchivableHandoffState_GetStartedAt_Call) Run(run func()) *MockArchivableHandoffState_GetStartedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArchivableHandoffState_GetStartedAt_Call) Return(_a0 time.Time) *MockArchivableHandoffState_GetStartedAt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArchivableHandoffState_GetStartedAt_Call) RunAndReturn(run func() time.Time) *MockArchivableHandoffState_GetStartedAt_Call {
	_c.Call.Return(run)
	return _c
}

// GetSummary provides a mock function with no fields
func (_m *MockArchivableHandoffState) GetSummary() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSummary")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockArchivableHandoffState_GetSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSummary'
type MockArchivableHandoffState_GetSummary_Call struct {
	*mock.Call
}

// GetSummary is a helper method to define mock.On call
func (_e *MockArchivableHandoffState_Expecter) GetSummary() *MockArchivableHandoffState_GetSummary_Call {
	return &MockArchivableHandoffState_GetSummary_Call{Call: _e.mock.On("GetSummary")}
}

func (_c *MockArchivableHandoffState_GetSummary_Call) Run(run func()) *MockArchivableHandoffState_GetSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArchivableHandoffState_GetSummary_Call) Return(_a0 string) *MockArchivableHandoffState_GetSummary_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArchivableHandoffState_GetSummary_Call) RunAndReturn(run func() string) *MockArchivableHandoffState_GetSummary_Call {
	_c.Call.Return(run)
	return _c
}

// GetTriggerContext provides a mock function with no fields
func (_m *MockArchivableHandoffState) GetTriggerContext() float64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTriggerContext")
	}

	var r0 float64
	if rf, ok := ret.Get(0).(func() float64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(float64)
	}

	return r0
}

// MockArchivableHandoffState_GetTriggerContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTriggerContext'
type MockArchivableHandoffState_GetTriggerContext_Call struct {
	*mock.Call
}

// GetTriggerContext is a helper method to define mock.On call
func (_e *MockArchivableHandoffState_Expecter) GetTriggerContext() *MockArchivableHandoffState_GetTriggerContext_Call {
	return &MockArchivableHandoffState_GetTriggerContext_Call{Call: _e.mock.On("GetTriggerContext")}
}

func (_c *MockArchivableHandoffState_GetTriggerContext_Call) Run(run func()) *MockArchivableHandoffState_GetTriggerContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArchivableHandoffState_GetTriggerContext_Call) Return(_a0 float64) *MockArchivableHandoffState_GetTriggerContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArchivableHandoffState_GetTriggerContext_Call) RunAndReturn(run func() float64) *MockArchivableHandoffState_GetTriggerContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetTriggerReason provides a mock function with no fields
func (_m *MockArchivableHandoffState) GetTriggerReason() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTriggerReason")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockArchivableHandoffState_GetTriggerReason_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTriggerReason'
type MockArchivableHandoffState_GetTriggerReason_Call struct {
	*mock.Call
}

// GetTriggerReason is a helper method to define mock.On call
func (_e *MockArchivableHandoffState_Expecter) GetTriggerReason() *MockArchivableHandoffState_GetTriggerReason_Call {
	return &MockArchivableHandoffState_GetTriggerReason_Call{Call: _e.mock.On("GetTriggerReason")}
}

func (_c *MockArchivableHandoffState_GetTriggerReason_Call) Run(run func()) *MockArchivableHandoffState_GetTriggerReason_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArchivableHandoffState_GetTriggerReason_Call) Return(_a0 string) *MockArchivableHandoffState_GetTriggerReason_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArchivableHandoffState_GetTriggerReason_Call) RunAndReturn(run func() string) *MockArchivableHandoffState_GetTriggerReason_Call {
	_c.Call.Return(run)
	return _c
}

// ToJSON provides a mock function with no fields
func (_m *MockArchivableHandoffState) ToJSON() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToJSON")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArchivableHandoffState_ToJSON_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToJSON'
type MockArchivableHandoffState_ToJSON_Call struct {
	*mock.Call
}

// ToJSON is a helper method to define mock.On call
func (_e *MockArchivableHandoffState_Expecter) ToJSON() *MockArchivableHandoffState_ToJSON_Call {
	return &MockArchivableHandoffState_ToJSON_Call{Call: _e.mock.On("ToJSON")}
}

func (_c *MockArchivableHandoffState_ToJSON_Call) Run(run func()) *MockArchivableHandoffState_ToJSON_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArchivableHandoffState_ToJSON_Call) Return(_a0 []byte, _a1 error) *MockArchivableHandoffState_ToJSON_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockArchivableHandoffState_ToJSON_Call) RunAndReturn(run func() ([]byte, error)) *MockArchivableHandoffState_ToJSON_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockArchivableHandoffState creates a new instance of MockArchivableHandoffState. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArchivableHandoffState(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArchivableHandoffState {
	mock := &MockArchivableHandoffState{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
