// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	pipeline "github.com/adalundhe/sylk/core/pipeline"
	mock "github.com/stretchr/testify/mock"
)

// MockAgentFactoryService is an autogenerated mock type for the AgentFactoryService type
type MockAgentFactoryService struct {
	mock.Mock
}

type MockAgentFactoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentFactoryService) EXPECT() *MockAgentFactoryService_Expecter {
	return &MockAgentFactoryService_Expecter{mock: &_m.Mock}
}

// CreateAgent provides a mock function with given fields: ctx, agentType, config
func (_m *MockAgentFactoryService) CreateAgent(ctx context.Context, agentType string, config pipeline.AgentConfig) (pipeline.AgentService, error) {
	ret := _m.Called(ctx, agentType, config)

	if len(ret) == 0 {
		panic("no return value specified for CreateAgent")
	}

	var r0 pipeline.AgentService
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, pipeline.AgentConfig) (pipeline.AgentService, error)); ok {
		return rf(ctx, agentType, config)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, pipeline.AgentConfig) pipeline.AgentService); ok {
		r0 = rf(ctx, agentType, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pipeline.AgentService)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, pipeline.AgentConfig) error); ok {
		r1 = rf(ctx, agentType, config)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentFactoryService_CreateAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAgent'
type MockAgentFactoryService_CreateAgent_Call struct {
	*mock.Call
}

// CreateAgent is a helper method to define mock.On call
//   - ctx context.Context
//   - agentType string
//   - config pipeline.AgentConfig
func (_e *MockAgentFactoryService_Expecter) CreateAgent(ctx interface{}, agentType interface{}, config interface{}) *MockAgentFactoryService_CreateAgent_Call {
	return &MockAgentFactoryService_CreateAgent_Call{Call: _e.mock.On("CreateAgent", ctx, agentType, config)}
}

func (_c *MockAgentFactoryService_CreateAgent_Call) Run(run func(ctx context.Context, agentType string, config pipeline.AgentConfig)) *MockAgentFactoryService_CreateAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(pipeline.AgentConfig))
	})
	return _c
}

func (_c *MockAgentFactoryService_CreateAgent_Call) Return(_a0 pipeline.AgentService, _a1 error) *MockAgentFactoryService_CreateAgent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentFactoryService_CreateAgent_Call) RunAndReturn(run func(context.Context, string, pipeline.AgentConfig) (pipeline.AgentService, error)) *MockAgentFactoryService_CreateAgent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentFactoryService creates a new instance of MockAgentFactoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentFactoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentFactoryService {
	mock := &MockAgentFactoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
