// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	pipeline "github.com/adalundhe/sylk/core/pipeline"
	mock "github.com/stretchr/testify/mock"
)

// MockHandoffArchiverService is an autogenerated mock type for the HandoffArchiverService type
type MockHandoffArchiverService struct {
	mock.Mock
}

type MockHandoffArchiverService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandoffArchiverService) EXPECT() *MockHandoffArchiverService_Expecter {
	return &MockHandoffArchiverService_Expecter{mock: &_m.Mock}
}

// Archive provides a mock function with given fields: ctx, state
func (_m *MockHandoffArchiverService) Archive(ctx context.Context, state pipeline.ArchivableHandoffState) error {
	ret := _m.Called(ctx, state)

	if len(ret) == 0 {
		panic("no return value specified for Archive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pipeline.ArchivableHandoffState) error); ok {
		r0 = rf(ctx, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHandoffArchiverService_Archive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Archive'
type MockHandoffArchiverService_Archive_Call struct {
	*mock.Call
}

// Archive is a helper method to define mock.On call
//   - ctx context.Context
//   - state pipeline.ArchivableHandoffState
func (_e *MockHandoffArchiverService_Expecter) Archive(ctx interface{}, state interface{}) *MockHandoffArchiverService_Archive_Call {
	return &MockHandoffArchiverService_Archive_Call{Call: _e.mock.On("Archive", ctx, state)}
}

func (_c *MockHandoffArchiverService_Archive_Call) Run(run func(ctx context.Context, state pipeline.ArchivableHandoffState)) *MockHandoffArchiverService_Archive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pipeline.ArchivableHandoffState))
	})
	return _c
}

func (_c *MockHandoffArchiverService_Archive_Call) Return(_a0 error) *MockHandoffArchiverService_Archive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHandoffArchiverService_Archive_Call) RunAndReturn(run func(context.Context, pipeline.ArchivableHandoffState) error) *MockHandoffArchiverService_Archive_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function with given fields: ctx, query
func (_m *MockHandoffArchiverService) Query(ctx context.Context, query pipeline.ArchiveQuery) ([]*pipeline.HandoffArchiveEntry, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []*pipeline.HandoffArchiveEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pipeline.ArchiveQuery) ([]*pipeline.HandoffArchiveEntry, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pipeline.ArchiveQuery) []*pipeline.HandoffArchiveEntry); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pipeline.HandoffArchiveEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pipeline.ArchiveQuery) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHandoffArchiverService_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockHandoffArchiverService_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - query pipeline.ArchiveQuery
func (_e *MockHandoffArchiverService_Expecter) Query(ctx interface{}, query interface{}) *MockHandoffArchiverService_Query_Call {
	return &MockHandoffArchiverService_Query_Call{Call: _e.mock.On("Query", ctx, query)}
}

func (_c *MockHandoffArchiverService_Query_Call) Run(run func(ctx context.Context, query pipeline.ArchiveQuery)) *MockHandoffArchiverService_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(pipeline.ArchiveQuery))
	})
	return _c
}

func (_c *MockHandoffArchiverService_Query_Call) Return(_a0 []*pipeline.HandoffArchiveEntry, _a1 error) *MockHandoffArchiverService_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHandoffArchiverService_Query_Call) RunAndReturn(run func(context.Context, pipeline.ArchiveQuery) ([]*pipeline.HandoffArchiveEntry, error)) *MockHandoffArchiverService_Query_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHandoffArchiverService creates a new instance of MockHandoffArchiverService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandoffArchiverService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandoffArchiverService {
	mock := &MockHandoffArchiverService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
