// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockArchivalEmbedder is an autogenerated mock type for the ArchivalEmbedder type
type MockArchivalEmbedder struct {
	mock.Mock
}

type MockArchivalEmbedder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArchivalEmbedder) EXPECT() *MockArchivalEmbedder_Expecter {
	return &MockArchivalEmbedder_Expecter{mock: &_m.Mock}
}

// Embed provides a mock function with given fields: ctx, text
func (_m *MockArchivalEmbedder) Embed(ctx context.Context, text string) ([]float32, error) {
	ret := _m.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for Embed")
	}

	var r0 []float32
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]float32, error)); ok {
		return rf(ctx, text)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []float32); ok {
		r0 = rf(ctx, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockArchivalEmbedder_Embed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Embed'
type MockArchivalEmbedder_Embed_Call struct {
	*mock.Call
}

// Embed is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockArchivalEmbedder_Expecter) Embed(ctx interface{}, text interface{}) *MockArchivalEmbedder_Embed_Call {
	return &MockArchivalEmbedder_Embed_Call{Call: _e.mock.On("Embed", ctx, text)}
}

func (_c *MockArchivalEmbedder_Embed_Call) Run(run func(ctx context.Context, text string)) *MockArchivalEmbedder_Embed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockArchivalEmbedder_Embed_Call) Return(_a0 []float32, _a1 error) *MockArchivalEmbedder_Embed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockArchivalEmbedder_Embed_Call) RunAndReturn(run func(context.Context, string) ([]float32, error)) *MockArchivalEmbedder_Embed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockArchivalEmbedder creates a new instance of MockArchivalEmbedder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArchivalEmbedder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArchivalEmbedder {
	mock := &MockArchivalEmbedder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
