// Code generated by mockery v2.53.6. DO NOT EDIT.

package forest

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

type MockForestProposalSink struct{ mock.Mock }

func (_m *MockForestProposalSink) ProposeClaim(ctx context.Context, proposal ForestClaimProposal) error {
	ret := _m.Called(ctx, proposal)
	return ret.Error(0)
}

type MockSkillArtifactWriter struct{ mock.Mock }

func (_m *MockSkillArtifactWriter) WriteSkillCandidate(ctx context.Context, candidate GeneratedSkillCandidate, files []SkillCandidateFile) error {
	ret := _m.Called(ctx, candidate, files)
	return ret.Error(0)
}

type MockPolicyOutcomeSource struct{ mock.Mock }

func (_m *MockPolicyOutcomeSource) PolicyOutcomes(ctx context.Context, candidateID string, limit int) ([]PolicyOutcome, error) {
	ret := _m.Called(ctx, candidateID, limit)
	if fn, ok := ret.Get(0).(func(context.Context, string, int) []PolicyOutcome); ok {
		return fn(ctx, candidateID, limit), ret.Error(1)
	}
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).([]PolicyOutcome), ret.Error(1)
}

type MockTextSearcher struct{ mock.Mock }

func (_m *MockTextSearcher) SearchText(ctx context.Context, query string, limit int) ([]ForestTextHit, error) {
	ret := _m.Called(ctx, query, limit)
	if fn, ok := ret.Get(0).(func(context.Context, string, int) []ForestTextHit); ok {
		return fn(ctx, query, limit), ret.Error(1)
	}
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).([]ForestTextHit), ret.Error(1)
}

type MockAgentTurnProvider struct{ mock.Mock }

func (_m *MockAgentTurnProvider) RecentAgentTurns(ctx context.Context, sessionID string, limit int) ([]AgentTurn, error) {
	ret := _m.Called(ctx, sessionID, limit)
	if fn, ok := ret.Get(0).(func(context.Context, string, int) []AgentTurn); ok {
		return fn(ctx, sessionID, limit), ret.Error(1)
	}
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).([]AgentTurn), ret.Error(1)
}

type MockGuardianApprover struct{ mock.Mock }

func (_m *MockGuardianApprover) ApproveForestProposal(ctx context.Context, request GuardianApprovalRequest) (ForestAuthorityApproval, error) {
	ret := _m.Called(ctx, request)
	if fn, ok := ret.Get(0).(func(context.Context, GuardianApprovalRequest) ForestAuthorityApproval); ok {
		return fn(ctx, request), ret.Error(1)
	}
	return ret.Get(0).(ForestAuthorityApproval), ret.Error(1)
}

func newMockForestProposalSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockForestProposalSink {
	m := &MockForestProposalSink{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
