// Code generated by mockery v2.53.6. DO NOT EDIT.

package forest

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockNeighborIndex is an autogenerated mock type for the NeighborIndex type
type MockNeighborIndex struct {
	mock.Mock
}

type MockNeighborIndex_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNeighborIndex) EXPECT() *MockNeighborIndex_Expecter {
	return &MockNeighborIndex_Expecter{mock: &_m.Mock}
}

// Neighbors provides a mock function with given fields: ctx, node, limit
func (_m *MockNeighborIndex) Neighbors(ctx context.Context, node ForestNode, limit int) ([]NodeNeighbor, error) {
	ret := _m.Called(ctx, node, limit)

	if len(ret) == 0 {
		panic("no return value specified for Neighbors")
	}

	var r0 []NodeNeighbor
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ForestNode, int) ([]NodeNeighbor, error)); ok {
		return rf(ctx, node, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ForestNode, int) []NodeNeighbor); ok {
		r0 = rf(ctx, node, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]NodeNeighbor)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ForestNode, int) error); ok {
		r1 = rf(ctx, node, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNeighborIndex_Neighbors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Neighbors'
type MockNeighborIndex_Neighbors_Call struct {
	*mock.Call
}

// Neighbors is a helper method to define mock.On call
//   - ctx context.Context
//   - node ForestNode
//   - limit int
func (_e *MockNeighborIndex_Expecter) Neighbors(ctx interface{}, node interface{}, limit interface{}) *MockNeighborIndex_Neighbors_Call {
	return &MockNeighborIndex_Neighbors_Call{Call: _e.mock.On("Neighbors", ctx, node, limit)}
}

func (_c *MockNeighborIndex_Neighbors_Call) Run(run func(ctx context.Context, node ForestNode, limit int)) *MockNeighborIndex_Neighbors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ForestNode), args[2].(int))
	})
	return _c
}

func (_c *MockNeighborIndex_Neighbors_Call) Return(_a0 []NodeNeighbor, _a1 error) *MockNeighborIndex_Neighbors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNeighborIndex_Neighbors_Call) RunAndReturn(run func(context.Context, ForestNode, int) ([]NodeNeighbor, error)) *MockNeighborIndex_Neighbors_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNeighborIndex creates a new instance of MockNeighborIndex. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNeighborIndex(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNeighborIndex {
	mock := &MockNeighborIndex{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
