package forest

import (
	"context"
	cryptorand "crypto/rand"
	"database/sql"
	"encoding/binary"
	"errors"
	"fmt"
	"log/slog"
	mathrand "math/rand"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/adalundhe/sylk/core/claims"
	ctxpkg "github.com/adalundhe/sylk/core/context"
	"github.com/adalundhe/sylk/core/knowledge/memory"
)

// Config configures the Memory Forest service.
type Config struct {
	DB           *sql.DB
	ContentStore *ctxpkg.UniversalContentStore
	Searcher     *ctxpkg.TieredSearcher
	Logger       *slog.Logger
	MaxTraces    int
	Booster      boosterConfig

	ReplayDelay         time.Duration
	SubstrateDebounce   time.Duration
	TrainingDebounce    time.Duration
	ReplayBatchSize     int
	SubstrateLimit      int
	TrainingMaxExamples int

	// SynchronousProjection forces AppendEvent to run the branch
	// projection inline (single transaction, single connection) and
	// disables the async projector goroutine. Used by tests and any
	// caller that needs read-your-writes semantics on the branch
	// projection without WaitForBranchSeq.
	//
	// Production deployments leave this false; the async projector
	// is what makes CQRS valuable (decoupled write throughput, lease-
	// coordinated multi-process safety). Tests typically set it true
	// to avoid lock-contention with shared-memory SQLite.
	SynchronousProjection bool

	// DisableBackgroundWorkers prevents maintenance/projector workers
	// from starting. This is narrower than SynchronousProjection:
	// several tests need inline branch projection while still exercising
	// event-driven replay/training/substrate maintenance. UI snapshot
	// tests use this when they only need deterministic read-your-writes
	// ingestion and immediate snapshot queries.
	DisableBackgroundWorkers bool

	// ── Issue #3 — selection-bias correction ──

	// CounterfactualLabelWeight is the magnitude applied to training
	// labels for candidates that were considered alongside the named
	// branch but did not themselves receive an explicit outcome.
	// Default: defaultCounterfactualLabelWeight (0.3).
	CounterfactualLabelWeight float64

	// CounterfactualWindow bounds how far back the counterfactual
	// labeling pass looks for retrievals that scored a given branch.
	// Older retrievals were against a stale projection; their
	// candidate sets are less informative.
	// Default: defaultCounterfactualWindow (24h).
	CounterfactualWindow time.Duration

	// ImplicitNegativeWeight is the magnitude applied to "ignored"
	// labels generated by the sweeper. Lower than explicit failure
	// because absence of outcome ≠ confirmed bad.
	// Default: defaultImplicitNegativeWeight (0.15).
	ImplicitNegativeWeight float64

	// ImplicitNegativeHorizon is how long after a retrieval an
	// unmatched return is considered ignored. Should comfortably
	// exceed the longest realistic outcome-feedback latency.
	// Default: defaultImplicitNegativeHorizon (1h).
	ImplicitNegativeHorizon time.Duration

	// ImplicitNegativeSweepInterval is the cadence between sweeps.
	// Default: defaultImplicitNegativeSweepInterval (5m).
	ImplicitNegativeSweepInterval time.Duration

	// ExplorationRate is the per-retrieval probability of
	// substituting the top-K with a random sample from the broader
	// candidate pool. 0 disables exploration entirely.
	// Default: defaultExplorationRate (0.05).
	ExplorationRate float64

	// ExplorationLabelWeight is the multiplier on training labels
	// produced from exploration retrievals (unbiased data deserves
	// higher weight).
	// Default: defaultExplorationLabelWeight (1.5).
	ExplorationLabelWeight float64

	// ExplorationSeed makes ε-greedy deterministic for tests. Zero
	// means use a crypto-random seed.
	ExplorationSeed int64

	// ── Issue #4 — diversity + cooldown ──

	// DiversityLambda balances relevance vs novelty in the MMR rerank.
	// 1.0 = pure relevance (no diversity), 0.0 = pure diversity.
	// Default: defaultDiversityLambda (0.7). Clamped to [0,1].
	DiversityLambda float64

	// RetrievalCooldownWindow is the count of recent retrievals (per
	// session) used to compute the cooldown signal.
	// Default: defaultRetrievalCooldownWindow (32).
	RetrievalCooldownWindow int

	// RetrievalCooldownPenalty is the maximum score scale-down applied
	// to a branch that appeared in every recent retrieval. 0 disables
	// the cooldown.
	// Default: defaultRetrievalCooldownPenalty (0.3). Clamped to [0,1].
	RetrievalCooldownPenalty float64

	// ── Issue #6 — AntiPattern promotion ──

	// AntiPatternFailureThreshold is the minimum failure_count before
	// an Outcome branch becomes eligible for AntiPattern promotion.
	// Default: defaultAntiPatternFailureThreshold (3).
	AntiPatternFailureThreshold int

	// AntiPatternFailureRate is the minimum failure_count /
	// total_observations ratio for promotion. Clamped to [0,1].
	// Default: defaultAntiPatternFailureRate (0.6).
	AntiPatternFailureRate float64

	// AntiPatternPromotionInterval is the cadence between promotion
	// scans. Default: defaultAntiPatternPromotionInterval (10m).
	AntiPatternPromotionInterval time.Duration

	// ── Retrieval-candidates background pruner ──

	// RetrievalCandidatesRetention bounds how long candidate rows are
	// retained before pruning. Forest_retrieval_events themselves stay
	// append-only forever (audit ledger).
	// Default: defaultRetrievalCandidatesRetention (7d).
	RetrievalCandidatesRetention time.Duration

	// RetrievalCandidatesPruneInterval is the cadence of the pruner.
	// Default: defaultRetrievalCandidatesPruneInterval (1h).
	RetrievalCandidatesPruneInterval time.Duration

	// ── Issue #7 — substrate mode + A/B sampling ──

	// SubstrateMode is the dominant substrate algorithm. The original
	// 4-iter diffusion (`full`) is the default; other modes
	// (`pagerank`, `warmth_only`) are A/B-tested against it via
	// SubstrateABRate. Default: defaultSubstrateMode (full).
	SubstrateMode SubstrateMode

	// SubstrateABRate is the per-retrieval probability of swapping the
	// dominant SubstrateMode for one of the alternatives. Sampled at
	// retrieve-time, captured in the audit, joined with outcome
	// events by SubstrateModeStatsSince to compare modes empirically.
	// 0 disables A/B. Default: defaultSubstrateABRate (0).
	SubstrateABRate float64

	// SubstrateModeSeed seeds the per-process RNG that drives A/B
	// sampling. Zero falls back to a crypto-random seed. Tests pin
	// this for deterministic mode selection.
	SubstrateModeSeed int64

	// ── Issue #8 — learned base scorer ──

	// BaseScoreTrainInterval is the cadence of the trainer goroutine.
	// Default: defaultBaseScoreTrainInterval (1h).
	BaseScoreTrainInterval time.Duration

	// BaseScoreMinTrainingExamples bounds promotion: a model trained
	// on fewer than this many labeled examples is never promoted.
	// Default: defaultBaseScoreMinTrainingExamples (1000).
	BaseScoreMinTrainingExamples int

	// BaseScoreImprovementThreshold is the minimum accuracy gain
	// over the current champion required for promotion.
	// Default: defaultBaseScoreImprovementThreshold (0.01).
	BaseScoreImprovementThreshold float64

	// BaseScoreLearningRate is the SGD step size during training.
	// Default: defaultBaseScoreLearningRate (0.005).
	BaseScoreLearningRate float64

	// BaseScoreL1Reg / BaseScoreL2Reg are regularization
	// coefficients. L1 drives uninformative weights toward zero
	// (pruning signal); L2 prevents weight explosion.
	BaseScoreL1Reg float64
	BaseScoreL2Reg float64

	// BaseScoreEpochs is the number of SGD passes per training cycle.
	// Default: defaultBaseScoreEpochs (8).
	BaseScoreEpochs int

	// BaseScoreTrainBatch is the maximum number of labeled examples
	// sampled per training cycle.
	// Default: defaultBaseScoreTrainBatch (4096).
	BaseScoreTrainBatch int

	// BaseScoreABRate is the per-retrieval probability of routing
	// through the challenger model. 0 disables A/B sampling.
	// Default: defaultBaseScoreABRate (0).
	BaseScoreABRate float64

	// BaseScoreSeed seeds the per-process RNG for A/B sampling. Zero
	// falls back to a crypto-random seed.
	BaseScoreSeed int64

	// BaseScoreMaxWeight clamps each weight to ±this value after
	// every SGD step.
	// Default: defaultBaseScoreMaxWeight (5.0).
	BaseScoreMaxWeight float64

	// BaseScorePruningThreshold flags components with |weight| below
	// this value as pruning candidates in ScoreComponentStatsSince.
	// Default: defaultBaseScorePruningThreshold (0.005).
	BaseScorePruningThreshold float64

	// ── Issue #10 — storage growth + archival ──

	// BranchTraceRetentionPerBranch is the max trace rows kept per
	// branch by the background pruner.
	// Default: defaultBranchTraceRetentionPerBranch (64).
	BranchTraceRetentionPerBranch int

	// BranchTracePruneInterval is the cadence between trace prune scans.
	// Default: defaultBranchTracePruneInterval (15m).
	BranchTracePruneInterval time.Duration

	// TrainingExamplesRetention is how long labeled training examples
	// are retained after their last update before pruning.
	// Default: defaultTrainingExamplesRetention (30d).
	TrainingExamplesRetention time.Duration

	// TrainingExamplesPruneInterval is the cadence of the pruner.
	// Default: defaultTrainingExamplesPruneInterval (1h).
	TrainingExamplesPruneInterval time.Duration

	// SubstrateStateRetention bounds how long substrate state is
	// retained for sessions whose latest event is older than this.
	// Default: defaultSubstrateStateRetention (30d).
	SubstrateStateRetention time.Duration

	// SubstrateStatePruneInterval is the cadence of the pruner.
	// Default: defaultSubstrateStatePruneInterval (6h).
	SubstrateStatePruneInterval time.Duration

	// EventArchiveAge is the age above which forest_events rows are
	// moved to forest_events_archive. Tied to operator's forensic
	// vs storage-cost trade-off.
	// Default: defaultEventArchiveAge (30d).
	EventArchiveAge time.Duration

	// RetrievalEventArchiveAge is the corresponding age for
	// forest_retrieval_events. May differ from EventArchiveAge if
	// operators want longer retention on the audit ledger.
	// Default: defaultRetrievalEventArchiveAge (30d).
	RetrievalEventArchiveAge time.Duration

	// EventArchiveInterval is the cadence of the archival worker.
	// Default: defaultEventArchiveInterval (1h).
	EventArchiveInterval time.Duration

	// EventArchiveBatchSize bounds how many events are archived per
	// cycle. Limits the per-cycle transaction size.
	// Default: defaultEventArchiveBatchSize (1000).
	EventArchiveBatchSize int

	// ClaimsDeltaSubscriber enables claims-native ingestion. When set,
	// canonical claims deltas are ingested into forest_ledger and
	// artifact/validation evidence projections. This replaces the legacy
	// claims activity harvester for claims lifecycle semantics.
	ClaimsDeltaSubscriber    claims.DeltaSubscriber
	ClaimsDeltaSessionFilter string
	DeltaIngestQueueCapacity int
}

// MemoryForest provides forest projection, retrieval, and learning services.
type MemoryForest struct {
	db           *sql.DB
	contentStore *ctxpkg.UniversalContentStore
	searcher     *ctxpkg.TieredSearcher
	logger       *slog.Logger
	warmth       *WarmthStore
	models       *learnedModelStore
	booster      boosterConfig

	// tuner is the integrated hyperparameter system (see
	// hyperparameters.go). Single source of truth for every
	// forest tunable. The tuner publishes its current snapshot
	// here via Subscribe; readers go through snapshot.Load() so
	// runtime adaptation promotions take effect on every existing
	// hot-path read without explicit invalidation.
	tuner               *HyperParameterTuner
	snapshot            atomic.Pointer[HyperParameters]
	snapshotUnsubscribe func()

	runCtx    context.Context
	runCancel context.CancelFunc
	runtime   *Runtime

	// Tunables migrated to the tuner snapshot:
	//   replayDelay, substrateDebounce, trainingDebounce →
	//   m.hyperparams().{ReplayDelay,SubstrateDebounce,TrainingDebounce}
	replayBatchSize     int
	substrateLimit      int
	trainingMaxExamples int

	maintenanceRunMu sync.Mutex
	maintenanceMu    sync.Mutex
	maintenanceWake  chan struct{}
	pendingSubstrate map[string]scheduledForestWork
	replayDue        time.Time
	trainingWork     scheduledForestWork
	trainingDirty    bool

	// CQRS branch projector — single tracked goroutine consumes
	// events from forest_event_seq_log in seq order and applies
	// them to the Branch projection (and downstream relay edges,
	// canopy, substrate-dirty marker, replay queue, warmth, training
	// labels). Lease-coordinated for multi-process safety.
	//
	// One wake channel per projector. Sharing one wake across
	// projectors causes the signal to be "stolen" — whichever
	// projector reads first consumes it, leaving the other to wait
	// out the poll interval. Separate channels means each projector
	// is notified independently when its source advances.
	projectorWake           chan struct{} // branch projector wake
	retrievalCandidatesWake chan struct{} // retrieval candidates projector wake
	projectorID             string
	synchronousProjection   bool

	// seqNotify broadcasts projection watermark advances so
	// WaitForBranchSeq is event-driven (no DB polling). Updated
	// after every successful apply; Halt fires on projector failure.
	seqNotify *seqNotifier

	// retrievalAuditQueue + drainer — async path for retrieval audit
	// emission. The Retrieve hot path enqueues; a tracked goroutine
	// drains. Never blocks the response path on the audit DB write.
	retrievalAuditQueue    chan *RetrievalAuditEvent
	retrievalAuditInFlight atomic.Int64
	retrievalAuditIdle     chan struct{} // signaled after each drain completes
	retrievalAuditClosed   atomic.Bool   // set on Close; emits become no-ops

	// Issue #3 / #4 tunables migrated to the tuner snapshot:
	//   counterfactual/implicit-negative weights, exploration rate,
	//   diversity lambda, retrieval cooldown — all read via
	//   m.hyperparams().X. Retained on the tuner so runtime
	//   adaptation can promote new values without re-capturing here.

	// Issue #6 — AntiPattern promotion. Periodic scanner promotes
	// Failed-outcome branches to sibling AntiPattern projections.
	// Tracked goroutine on m.wg, panic recovery, drain-then-sleep.
	antiPatternFailureThreshold  int
	antiPatternFailureRate       float64
	antiPatternPromotionInterval time.Duration

	// Background pruner — bounds forest_retrieval_candidates growth.
	// Lease-coordinated, drain-then-sleep, panic-recovered.
	retrievalCandidatesRetention     time.Duration
	retrievalCandidatesPruneInterval time.Duration

	// Issue #7 — substrate mode + A/B sampling. The dominant mode
	// runs unless A/B sampling fires for a given retrieval (sampled
	// from substrateModeRng under substrateModeRngMu). Captured in
	// the audit per retrieval.
	substrateMode      SubstrateMode
	substrateABRate    float64
	substrateModeRng   *mathrand.Rand
	substrateModeRngMu sync.Mutex

	// pageRankIncrementalCache holds per-session PageRank state with
	// O(work-done) incremental updates via Andersen-Chung-Lang push.
	// Replaces the (now-removed) version-keyed cache so a graph
	// mutation in a session reuses cached r/p vectors and pushes
	// only mass localized to changed-edge endpoints.
	pageRankIncrementalCache *pageRankIncrementalCache

	// Issue #8 — learned base scorer. Trainer is a tracked goroutine
	// (lease-coordinated, drain-then-sleep). baseScoreCache holds the
	// active champion + challenger via atomic pointers so the hot
	// scoring path never blocks behind a training write.
	// Base-scorer hyperparameters migrated to the tuner snapshot:
	//   learning rate, L1/L2, epochs, improvement-threshold,
	//   min-training-examples, max-weight, pruning-threshold —
	//   all read via m.hyperparams().X.
	baseScoreStore         *baseScoreModelStore
	baseScoreCache         *baseScoreCache
	baseScoreTrainInterval time.Duration
	baseScoreTrainBatch    int
	baseScoreABRate        float64
	baseScoreModeRng       *mathrand.Rand
	baseScoreModeRngMu     sync.Mutex
	deltaIngestor          *DeltaIngestor

	// Issue #9 — base-score calibration cache. Single atomic-pointer
	// holder so the Retrieve hot path stamps a recent ECE-derived
	// confidence value onto each packet without per-request DB
	// queries. Lazy refresh after staleness window.
	calibrationCache *calibrationCache

	// Issue #10 — storage growth + archival. Each maintenance
	// goroutine is tracked on m.wg, lease-coordinated via
	// forest_projector_state, drain-then-sleep cadence, errors as
	// artifacts on the lease row. Configurable retention windows +
	// scan intervals.
	branchTraceRetentionPerBranch int
	branchTracePruneInterval      time.Duration
	trainingExamplesRetention     time.Duration
	trainingExamplesPruneInterval time.Duration
	substrateStateRetention       time.Duration
	substrateStatePruneInterval   time.Duration
	eventArchiveAge               time.Duration
	retrievalEventArchiveAge      time.Duration
	eventArchiveInterval          time.Duration
	eventArchiveBatchSize         int

	// explorationRng is a *mathrand.Rand seeded at construction.
	// Guarded by explorationRngMu — Go's math/rand source is not
	// goroutine-safe, and Retrieve can be called concurrently.
	explorationRng   *mathrand.Rand
	explorationRngMu sync.Mutex

	stopOnce sync.Once
	stopCh   chan struct{}
	wg       sync.WaitGroup
}

// New creates and initializes a Memory Forest service.
func New(cfg Config) (*MemoryForest, error) {
	if cfg.DB == nil {
		return nil, errors.New("forest db is required")
	}
	if err := ensureSchema(cfg.DB); err != nil {
		return nil, err
	}
	models, err := newLearnedModelStore(cfg.DB)
	if err != nil {
		return nil, err
	}
	booster := cfg.Booster
	if booster == (boosterConfig{}) {
		booster = defaultBoosterConfig()
	}

	runCtx, runCancel := context.WithCancel(context.Background())
	logger := normalizeLogger(cfg.Logger)

	// Build the tuner BEFORE per-field captures. The tuner
	// resolves the layered priority chain (Config → workload-init
	// → persisted → placeholder) and is the source of truth for
	// every tunable below. The captures then pull from the tuner
	// snapshot, ensuring "Config explicitly set" and "workload-init
	// fitted from my ledger" values flow into the field reads
	// existing code uses.
	tuner, err := NewHyperParameterTuner(runCtx, cfg.DB, logger)
	if err != nil {
		runCancel()
		return nil, fmt.Errorf("forest: hyperparameter tuner init: %w", err)
	}
	if err := applyConfigOverrides(runCtx, tuner, cfg); err != nil {
		runCancel()
		tuner.Stop()
		return nil, fmt.Errorf("forest: hyperparameter overrides: %w", err)
	}
	hp := tuner.Get()
	_ = hp // kept while migrating fields → snapshot.Load() reads

	service := &MemoryForest{
		db:                               cfg.DB,
		contentStore:                     cfg.ContentStore,
		searcher:                         cfg.Searcher,
		logger:                           logger,
		warmth:                           newWarmthStore(cfg.DB, cfg.MaxTraces),
		models:                           models,
		booster:                          booster,
		tuner:                            tuner,
		runCtx:                           runCtx,
		runCancel:                        runCancel,
		runtime:                          newRuntime(runCtx, logger),
		replayBatchSize:                  resolveForestReplayBatchSize(cfg.ReplayBatchSize),
		substrateLimit:                   resolveForestSubstrateLimit(cfg.SubstrateLimit),
		trainingMaxExamples:              resolveForestTrainingExamples(cfg.TrainingMaxExamples),
		maintenanceWake:                  make(chan struct{}, 1),
		pendingSubstrate:                 make(map[string]scheduledForestWork),
		projectorWake:                    make(chan struct{}, 1),
		retrievalCandidatesWake:          make(chan struct{}, 1),
		projectorID:                      generateProjectorID(),
		synchronousProjection:            cfg.SynchronousProjection,
		seqNotify:                        newSeqNotifier(),
		retrievalAuditIdle:               make(chan struct{}, 1),
		explorationRng:                   newExplorationRng(cfg.ExplorationSeed),
		antiPatternFailureThreshold:      resolveAntiPatternFailureThreshold(cfg.AntiPatternFailureThreshold),
		antiPatternFailureRate:           resolveAntiPatternFailureRate(cfg.AntiPatternFailureRate),
		antiPatternPromotionInterval:     resolveAntiPatternPromotionInterval(cfg.AntiPatternPromotionInterval),
		retrievalCandidatesRetention:     resolveRetrievalCandidatesRetention(cfg.RetrievalCandidatesRetention),
		retrievalCandidatesPruneInterval: resolveRetrievalCandidatesPruneInterval(cfg.RetrievalCandidatesPruneInterval),
		substrateMode:                    resolveSubstrateMode(cfg.SubstrateMode),
		substrateABRate:                  resolveSubstrateABRate(cfg.SubstrateABRate),
		substrateModeRng:                 newExplorationRng(cfg.SubstrateModeSeed),
		pageRankIncrementalCache:         newPageRankIncrementalCache(pageRankCacheCapacity),
		baseScoreCache:                   newBaseScoreCache(),
		baseScoreTrainInterval:           resolveBaseScoreTrainInterval(cfg.BaseScoreTrainInterval),
		baseScoreTrainBatch:              resolveBaseScoreTrainBatch(cfg.BaseScoreTrainBatch),
		baseScoreABRate:                  resolveBaseScoreABRate(cfg.BaseScoreABRate),
		baseScoreModeRng:                 newExplorationRng(cfg.BaseScoreSeed),
		calibrationCache:                 newCalibrationCache(),
		branchTraceRetentionPerBranch:    resolveBranchTraceRetentionPerBranch(cfg.BranchTraceRetentionPerBranch),
		branchTracePruneInterval:         resolveBranchTracePruneInterval(cfg.BranchTracePruneInterval),
		trainingExamplesRetention:        resolveTrainingExamplesRetention(cfg.TrainingExamplesRetention),
		trainingExamplesPruneInterval:    resolveTrainingExamplesPruneInterval(cfg.TrainingExamplesPruneInterval),
		substrateStateRetention:          resolveSubstrateStateRetention(cfg.SubstrateStateRetention),
		substrateStatePruneInterval:      resolveSubstrateStatePruneInterval(cfg.SubstrateStatePruneInterval),
		eventArchiveAge:                  resolveEventArchiveAge(cfg.EventArchiveAge),
		retrievalEventArchiveAge:         resolveRetrievalEventArchiveAge(cfg.RetrievalEventArchiveAge),
		eventArchiveInterval:             resolveEventArchiveInterval(cfg.EventArchiveInterval),
		eventArchiveBatchSize:            resolveEventArchiveBatchSize(cfg.EventArchiveBatchSize),
		stopCh:                           make(chan struct{}),
	}
	service.baseScoreStore = newBaseScoreModelStore(service.db)
	service.registerRuntimeQueue("maintenance_wake", cap(service.maintenanceWake))
	service.registerRuntimeQueue("branch_projector_wake", cap(service.projectorWake))
	service.registerRuntimeQueue("retrieval_candidates_wake", cap(service.retrievalCandidatesWake))
	service.registerRuntimeQueue("retrieval_audit_idle", cap(service.retrievalAuditIdle))
	if err := service.runtime.RegisterLease(projectorBranchName, service.projectorID); err != nil {
		service.logger.Error("forest_runtime_lease_register_failed", "lease", projectorBranchName, "err", err.Error())
	}

	// Subscribe to tuner promotions so runtime adaptation
	// updates the cached snapshot atomically. Subscribe fires
	// once immediately with the current snapshot, ensuring the
	// snapshot pointer is non-nil before any read path runs.
	service.snapshotUnsubscribe = tuner.Subscribe(func(updated *HyperParameters) {
		service.snapshot.Store(updated)
	})

	// Warn (not fail) if retention < attribution window: the
	// SubstrateModeStatsSince diagnostic JOINs against
	// forest_retrieval_candidates, which the background pruner trims.
	// A retention shorter than the attribution window silently
	// undercounts outcomes for older retrievals. Operators may set
	// this intentionally to bound storage; we log so the trade-off
	// is visible.
	if service.retrievalCandidatesRetention < outcomeAttributionWindow {
		service.logger.Warn(
			"forest: retrieval-candidates retention is shorter than substrate outcome attribution window; SubstrateModeStatsSince will undercount older retrievals",
			"retention", service.retrievalCandidatesRetention.String(),
			"attribution_window", outcomeAttributionWindow.String(),
		)
	}

	if cfg.ClaimsDeltaSubscriber != nil {
		if _, err := service.MountClaimsDeltaIngestion(cfg.ClaimsDeltaSubscriber, cfg.ClaimsDeltaSessionFilter, resolveDeltaIngestQueueCapacity(cfg.DeltaIngestQueueCapacity)); err != nil {
			runCancel()
			tuner.Stop()
			return nil, fmt.Errorf("forest: mount claims delta ingestion: %w", err)
		}
	}

	if !cfg.DisableBackgroundWorkers {
		service.startMaintenance()
	}
	if !service.synchronousProjection && !cfg.DisableBackgroundWorkers {
		// Async-only goroutines: branch projector,
		// retrieval-candidates projector, audit drainer,
		// implicit-negative sweeper, AntiPattern promoter, and
		// storage pruners. Tests using SynchronousProjection=true
		// write branch projections inline but still rely on the
		// maintenance worker for replay, substrate, and training
		// schedules.
		service.startBranchProjector()
		service.startRetrievalCandidatesProjector()
		service.startRetrievalAuditDrainer()
		service.startImplicitNegativeSweeper()
		service.startAntiPatternPromoter()
		service.startRetrievalCandidatesPruner()
		service.startBaseScoreTrainer()
		// Issue #10 — storage growth + archival workers.
		service.startBranchTracePruner()
		service.startTrainingExamplesPruner()
		service.startSubstrateStatePruner()
		service.startEventArchivalWorker()
	}
	// Best-effort initial cache hydration so the first Retrieve sees
	// any persisted models from a prior process. Failure is logged
	// (not fatal) — cold-start fallback to defaults handles it.
	if _, err := service.hydrateBaseScoreCache(runCtx); err != nil {
		service.logger.Warn(
			"forest: initial base-score cache hydration failed",
			"err", err.Error(),
		)
	}
	return service, nil
}

// newExplorationRng seeds the exploration RNG. A non-zero
// Config.ExplorationSeed produces deterministic behavior (used by
// tests). Zero falls back to a crypto-random 64-bit seed so the
// per-process exploration sequence is unpredictable across restarts.
func newExplorationRng(configSeed int64) *mathrand.Rand {
	seed := configSeed
	if seed == 0 {
		var buf [8]byte
		if _, err := cryptorand.Read(buf[:]); err == nil {
			seed = int64(binary.LittleEndian.Uint64(buf[:]))
		} else {
			seed = time.Now().UnixNano()
		}
	}
	return mathrand.New(mathrand.NewSource(seed))
}

// Close stops background maintenance loops + drains pending audits
// + flushes the projector. Idempotent via stopOnce.
//
// The retrievalAuditClosed flag is flipped BEFORE runCancel so any
// concurrent emitRetrievalAudit caller observes shutdown and drops
// the event rather than enqueueing onto a channel whose drainer is
// about to exit.
func (m *MemoryForest) Close() error {
	return m.CloseWithContext(context.Background())
}

// CloseWithContext is the context-aware close. Cancels the run
// context and stop channel, then waits for tracked workers to drain
// — but bounded by ctx. When ctx is canceled before drain completes,
// returns ctx.Err() wrapped so the caller (typically a shutdown
// orchestrator with a per-subsystem budget) can record the timeout
// and proceed with the rest of the teardown rather than hanging
// indefinitely on a stuck worker.
//
// The shutdown signal (runCancel + stopCh) is delivered exactly once
// regardless of how many CloseWithContext calls race; the per-call
// drain wait is independent and each caller observes its own ctx.
//
// On timeout the wg-monitor goroutine is intentionally left running.
// It exits naturally when the workers eventually drain (or when the
// process exits, which the kill watchdog guarantees within bounded
// time). closeTuner is skipped on timeout because the tuner may be
// one of the workers we're waiting for; any cleanup it owes is
// reclaimed at process exit.
func (m *MemoryForest) CloseWithContext(ctx context.Context) error {
	m.stopOnce.Do(func() {
		m.retrievalAuditClosed.Store(true)
		if m.runCancel != nil {
			m.runCancel()
		}
		close(m.stopCh)
	})
	if m.runtime != nil {
		if err := m.runtime.Close(ctx); err != nil {
			m.recordRuntimeShutdownTimeout(ctx, err)
			return err
		}
	} else {
		m.logger.Error("forest_runtime_missing_close")
	}
	m.closeTuner()
	return nil
}

func (m *MemoryForest) startWorker(name string, queueLimit int, run func(context.Context) error) {
	if m == nil || run == nil {
		return
	}
	if m.runtime != nil {
		if err := m.runtime.StartWorker(name, queueLimit, run); err != nil {
			m.logger.Error("forest_runtime_start_failed", "worker", name, "err", err.Error())
		}
		return
	}
	m.logger.Error("forest_runtime_missing_worker_not_started", "worker", name)
}

func (m *MemoryForest) recordRuntimeShutdownTimeout(ctx context.Context, cause error) {
	if m == nil || cause == nil {
		return
	}
	recordCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), time.Second)
	defer cancel()
	_, err := m.AppendLedgerRecord(recordCtx, LedgerRecord{
		SourceKind:  LedgerSourceMaintenance,
		SourceID:    "runtime_shutdown",
		SourceKey:   "runtime_shutdown_timeout:" + stableID(time.Now().UTC().Format(time.RFC3339Nano), cause.Error()),
		EventKind:   "runtime.shutdown_timeout",
		SessionID:   "global",
		SubjectType: "runtime",
		SubjectID:   "shutdown",
		Reason:      cause.Error(),
		OccurredAt:  time.Now().UTC(),
		Payload: map[string]any{
			"error": cause.Error(),
		},
	})
	if err != nil {
		m.logger.Warn("forest_runtime_shutdown_timeout_artifact_failed", "err", err.Error())
	}
}

func (m *MemoryForest) RuntimeSnapshot() RuntimeSnapshot {
	if m == nil || m.runtime == nil {
		return RuntimeSnapshot{}
	}
	return m.runtime.Snapshot()
}

func (m *MemoryForest) registerRuntimeQueue(name string, capacity int) {
	if m == nil || m.runtime == nil {
		return
	}
	if err := m.runtime.RegisterQueue(name, capacity); err != nil {
		m.logger.Error("forest_runtime_queue_register_failed", "queue", name, "err", err.Error())
	}
}

func (m *MemoryForest) registerRuntimeTicker(name string, interval time.Duration) {
	if m == nil || m.runtime == nil {
		return
	}
	if err := m.runtime.RegisterTicker(name, interval); err != nil {
		m.logger.Error("forest_runtime_ticker_register_failed", "ticker", name, "err", err.Error())
	}
}

func (m *MemoryForest) recordRuntimeQueueOverflow(name, reason string) {
	if m == nil || m.runtime == nil {
		return
	}
	m.runtime.RecordQueueOverflow(name, reason)
}

func normalizeLogger(logger *slog.Logger) *slog.Logger {
	if logger != nil {
		return logger
	}
	return slog.Default()
}

// SetContentStore wires a content store after forest construction.
func (m *MemoryForest) SetContentStore(store *ctxpkg.UniversalContentStore) {
	if m == nil {
		return
	}
	m.contentStore = store
}

// SetSearcher wires a tiered searcher after forest construction.
func (m *MemoryForest) SetSearcher(searcher *ctxpkg.TieredSearcher) {
	if m == nil {
		return
	}
	m.searcher = searcher
}

// OnContentIndexed satisfies context.ContentIndexObserver.
func (m *MemoryForest) OnContentIndexed(ctx context.Context, entry *ctxpkg.ContentEntry) error {
	if entry == nil {
		return nil
	}
	if entry.Metadata != nil && entry.Metadata[ctxpkg.MetadataForestSynthetic] == "true" {
		return nil
	}
	return m.RecordContent(ctx, entry)
}

// RecordContent maps a content entry into the ledger and branch projection.
func (m *MemoryForest) RecordContent(ctx context.Context, entry *ctxpkg.ContentEntry) error {
	if entry == nil {
		return nil
	}
	event := eventFromContent(entry)
	return m.AppendEvent(ctx, event)
}

// RecordOutcome records explicit branch outcome feedback.
func (m *MemoryForest) RecordOutcome(ctx context.Context, record OutcomeRecord) error {
	if strings.TrimSpace(record.BranchID) == "" {
		return errors.New("branch_id is required")
	}

	branch, err := m.getBranch(ctx, record.BranchID)
	if err != nil {
		return err
	}
	if branch == nil {
		return fmt.Errorf("branch %s not found", record.BranchID)
	}

	event := &Event{
		SessionID:      firstNonEmpty(record.SessionID, branch.SessionID),
		TaskID:         firstNonEmpty(record.TaskID, branch.TaskID),
		AgentID:        record.AgentID,
		AgentType:      record.AgentType,
		EventType:      EventTypeOutcomeRecorded,
		Family:         TreeFamilyOutcome,
		Scope:          branch.Scope,
		RootID:         branch.RootID,
		BranchID:       branch.ID,
		ParentBranchID: branch.ParentID,
		IntentID:       firstNonEmpty(branch.IntentID, branch.RootID),
		Confidence:     defaultConfidence(record.Confidence),
		Salience:       defaultSalience(record.Salience),
		Timestamp:      time.Now().UTC(),
		Title:          summarizeText(record.Summary, 72),
		Summary:        summarizeText(record.Summary, 240),
		ProvenanceRefs: dedupeStrings(record.ProvenanceRefs),
		Supersedes:     dedupeStrings(record.Supersedes),
		Contradicts:    dedupeStrings(record.Contradicts),
		Payload: map[string]any{
			"status": record.Status,
		},
	}
	return m.AppendEvent(ctx, event)
}

// AppendEvent records a legacy branch-compatible event in the canonical
// forest ledger and assigns it the ledger's monotonic sequence. The event is
// durable on return; the branch projector consumes forest_ledger records with
// source_kind=forest_event_compat until the phase-4 node graph replaces the
// branch projection entirely.
//
// Runtime no longer writes forest_events. That table is retained only for
// archived historical rows and explicit migration fixtures.
func (m *MemoryForest) AppendEvent(ctx context.Context, event *Event) error {
	prepared := prepareEvent(event)
	result, err := m.AppendLedgerRecord(ctx, ledgerRecordFromForestEvent(prepared))
	if err != nil {
		slog.Error("forest_append_ledger_record_failed",
			"event_id", prepared.ID,
			"branch_id", prepared.BranchID,
			"err", err.Error(),
		)
		return err
	}
	prepared.Seq = result.Seq
	event.Seq = result.Seq
	if !result.Inserted {
		return nil
	}
	if m.synchronousProjection {
		if err := m.projectInlineForTests(ctx, prepared); err != nil {
			slog.Error("forest_inline_projection_failed",
				"event_id", prepared.ID,
				"branch_id", prepared.BranchID,
				"err", err.Error(),
			)
			return err
		}
		return nil
	}
	m.notifyProjector()
	return nil
}

func ledgerRecordFromForestEvent(event *Event) LedgerRecord {
	actorType := firstNonEmptyString(event.AgentType, event.AgentID, "unknown")
	return LedgerRecord{
		ID:          "ledger_" + stableID("forest_event", event.ID),
		SourceKind:  LedgerSourceForestEvent,
		SourceID:    event.ID,
		SourceKey:   "forest_event:" + event.ID,
		EventKind:   firstNonEmptyString(string(event.EventType), "forest.event"),
		SessionID:   firstNonEmptyString(event.SessionID, "global"),
		TaskID:      event.TaskID,
		SubjectType: "branch",
		SubjectID:   event.BranchID,
		Actor:       claims.DegradedAgentRef(actorType, "legacy forest event actor"),
		OccurredAt:  event.Timestamp,
		Payload:     event,
		Refs:        forestEventRefs(event),
	}
}

func forestEventRefs(event *Event) []claims.DeltaRef {
	if event == nil {
		return nil
	}
	refs := make([]claims.DeltaRef, 0, 1+len(event.ProvenanceRefs)+len(event.Supersedes)+len(event.Contradicts))
	if event.ContentID != "" {
		refs = append(refs, claims.DeltaRef{Role: "content", Type: "content", ID: event.ContentID})
	}
	for _, ref := range event.ProvenanceRefs {
		if strings.TrimSpace(ref) != "" {
			refs = append(refs, claims.DeltaRef{Role: "provenance", Type: "external_ref", ID: ref})
		}
	}
	for _, branchID := range event.Supersedes {
		if strings.TrimSpace(branchID) != "" {
			refs = append(refs, claims.DeltaRef{Role: "supersedes", Type: "branch", ID: branchID})
		}
	}
	for _, branchID := range event.Contradicts {
		if strings.TrimSpace(branchID) != "" {
			refs = append(refs, claims.DeltaRef{Role: "contradicts", Type: "branch", ID: branchID})
		}
	}
	return refs
}

// projectInlineForTests applies the projection synchronously inside
// AppendEvent. Used only when Config.SynchronousProjection is true.
// Mirrors the apply step the branch projector would run, including
// the watermark update on forest_projector_state and seq-notifier
// advance so WaitForBranchSeq callers wake correctly even in sync
// mode (relevant when test code dispatches across goroutines).
func (m *MemoryForest) projectInlineForTests(ctx context.Context, event *Event) error {
	if err := m.ensureProjectorRow(projectorBranchName); err != nil {
		return err
	}

	tx, err := m.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin inline projection tx: %w", err)
	}
	defer tx.Rollback()

	branch, created, replayDue, applyErr := m.projectBranchTx(ctx, tx, event)
	if applyErr != nil {
		return applyErr
	}
	if err := setProjectorWatermarkTx(ctx, tx, projectorBranchName, event.Seq, event.Timestamp); err != nil {
		return err
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit inline projection tx: %w", err)
	}

	if m.seqNotify != nil {
		m.seqNotify.Advance(event.Seq)
	}
	m.runProjectorPostCommit(event, branch, created, replayDue)
	return nil
}

// notifyProjector signals the branch projector that new work is
// available. Non-blocking — the wake channel is buffered to size 1,
// so a pending wake collapses with subsequent ones.
func (m *MemoryForest) notifyProjector() {
	if m == nil || m.projectorWake == nil {
		return
	}
	select {
	case m.projectorWake <- struct{}{}:
	default:
		m.recordRuntimeQueueOverflow("branch_projector_wake", "branch projector wake already pending")
	}
}

// projectBranchTx applies a single durable event to the branch
// projection (branch row, relay edges, canopy, replay queue,
// substrate-dirty marker). The event must already exist in the
// ledger and have a non-zero Seq — this function projects, it does
// not append.
//
// Called exclusively from the branch projector under its single-
// leader lease, so there is no concurrent contention on any
// projection row.
func (m *MemoryForest) projectBranchTx(ctx context.Context, tx *sql.Tx, event *Event) (*Branch, bool, time.Time, error) {
	branch, err := getBranchTx(ctx, tx, event.BranchID)
	if err != nil {
		return nil, false, time.Time{}, err
	}
	created := branch == nil
	// Canonicalize at the projection apply boundary so a from-scratch
	// rebuild over pre-Phase-3 ledger rows (forest_events still carries
	// historical 'decision'/'preference'/etc. — the ledger is append-
	// only and cannot be rewritten) produces canonical families on the
	// projection. New events are already canonicalized in prepareEvent;
	// this guards the replay path.
	event.Family = canonicalizeFamily(event.Family)
	branch = applyEvent(branch, event)
	branch.LastAppliedSeq = event.Seq

	if err := upsertBranchTx(ctx, tx, branch); err != nil {
		return nil, false, time.Time{}, err
	}
	if err := upsertRelayEdgesTx(ctx, tx, event); err != nil {
		return nil, false, time.Time{}, err
	}
	if err := refreshCanopiesTx(ctx, tx, event.SessionID, event.TaskID, event.IntentID); err != nil {
		return nil, false, time.Time{}, err
	}
	replayDue, err := m.enqueueReplayTx(ctx, tx, branch, event)
	if err != nil {
		return nil, false, time.Time{}, err
	}
	if err := markSubstrateDirtyTx(ctx, tx, event.SessionID, event.Timestamp); err != nil {
		return nil, false, time.Time{}, err
	}
	return branch, created, replayDue, nil
}

func prepareEvent(event *Event) *Event {
	if event == nil {
		event = &Event{}
	}
	now := event.Timestamp
	if now.IsZero() {
		now = time.Now().UTC()
	}
	event.Timestamp = now
	if event.SessionID == "" {
		event.SessionID = "global"
	}
	event.TaskID = normalizeForestTaskID(firstNonEmpty(event.TaskID, forestTaskIDFromPayload(event.Payload)))
	if event.Scope == "" {
		event.Scope = ScopeEpisodic
	}
	if event.Family == "" {
		event.Family = TreeFamilyEvidence
	}
	// Phase 3 of Issue #11: every author boundary canonicalizes to
	// the consolidated five-family taxonomy + AntiPattern. Catches
	// callers that still pass deprecated family values directly to
	// AppendEvent (rather than going through familyFromContentEntry).
	event.Family = canonicalizeFamily(event.Family)
	event.Confidence = defaultConfidence(event.Confidence)
	event.Salience = defaultSalience(event.Salience)
	if event.Summary == "" {
		event.Summary = summarizeText(event.Title, 240)
	}
	if event.Title == "" {
		event.Title = summarizeText(event.Summary, 72)
	}
	if event.IntentID == "" {
		event.IntentID = stableID("intent", event.SessionID, event.TaskID, normalizeText(firstNonEmpty(event.Title, event.Summary, event.BranchID)))
	}
	if event.RootID == "" {
		event.RootID = stableID("root", event.SessionID, event.TaskID, event.IntentID, string(event.Family))
	}
	if event.BranchID == "" {
		event.BranchID = stableID("branch", event.RootID, event.TaskID, normalizeText(firstNonEmpty(event.Title, event.Summary)), event.AgentType)
	}
	if event.ID == "" {
		event.ID = stableID(
			"event",
			event.SessionID,
			event.TaskID,
			event.BranchID,
			string(event.EventType),
			event.Timestamp.UTC().Format(time.RFC3339Nano),
			event.Title,
			event.ContentID,
		)
	}
	event.ProvenanceRefs = dedupeStrings(event.ProvenanceRefs)
	event.Supersedes = dedupeStrings(event.Supersedes)
	event.Contradicts = dedupeStrings(event.Contradicts)
	event.RelatedBranchIDs = dedupeStrings(event.RelatedBranchIDs)
	return event
}

func eventFromContent(entry *ctxpkg.ContentEntry) *Event {
	entry = entry.Clone()
	entry.HydrateForestMetadata()

	family := familyFromContentEntry(entry)
	scope := scopeFromContentEntry(entry, family)
	taskID := forestTaskIDFromStringMetadata(entry.Metadata)
	intentID := firstNonEmpty(entry.IntentID, stableID("intent", entry.SessionID, taskID, normalizeText(entry.Content)))
	rootID := stableID("root", firstNonEmpty(entry.SessionID, "global"), taskID, intentID, string(family))
	branchID := firstNonEmpty(entry.BranchID, stableID("branch", rootID, taskID, entry.ParentID, entry.AgentType, fmt.Sprintf("%d", entry.TurnNumber)))
	eventType := eventTypeFromContentType(entry.ContentType)

	return prepareEvent(&Event{
		SessionID:      entry.SessionID,
		TaskID:         taskID,
		AgentID:        entry.AgentID,
		AgentType:      entry.AgentType,
		EventType:      eventType,
		Family:         family,
		Scope:          scope,
		RootID:         rootID,
		BranchID:       branchID,
		ParentBranchID: entry.ParentID,
		IntentID:       intentID,
		ContentID:      entry.ID,
		Confidence:     defaultConfidence(entry.Confidence),
		Salience:       defaultSalience(entry.Salience),
		Timestamp:      entry.Timestamp,
		Title:          summarizeText(entry.Content, 72),
		Summary:        summarizeText(entry.Content, 240),
		ProvenanceRefs: dedupeStrings(entry.ProvenanceRefs),
		Supersedes:     dedupeStrings(entry.Supersedes),
		Contradicts:    dedupeStrings(entry.Contradicts),
		Payload: map[string]any{
			"content_type":   entry.ContentType,
			"keywords":       entry.Keywords,
			"entities":       entry.Entities,
			"related_files":  entry.RelatedFiles,
			"facet":          entry.Facet,
			"outcome_ref":    entry.OutcomeRef,
			"metadata":       entry.EffectiveMetadata(),
			"parent_content": entry.ParentID,
		},
	})
}

func eventTypeFromContentType(contentType ctxpkg.ContentType) EventType {
	switch contentType {
	case ctxpkg.ContentTypeDecision:
		return EventTypeDecisionRecorded
	case ctxpkg.ContentTypeOutcome:
		return EventTypeOutcomeRecorded
	case ctxpkg.ContentTypePreference:
		return EventTypePreferenceRecorded
	case ctxpkg.ContentTypeHypothesis:
		return EventTypeHypothesisRecorded
	default:
		return EventTypeContentIndexed
	}
}

func familyFromContentEntry(entry *ctxpkg.ContentEntry) TreeFamily {
	// Issue #11 Phase 3 — content-type → family routing collapsed
	// per the audit's 5-family taxonomy. Decision content becomes
	// Intent, Preference becomes Constraint (severity assigned by
	// caller path), Hypothesis-as-Conflict becomes AntiPattern,
	// Hypothesis-as-Opportunity becomes Intent.
	switch entry.ContentType {
	case ctxpkg.ContentTypeIntentSnapshot, ctxpkg.ContentTypeUserPrompt:
		return TreeFamilyIntent
	case ctxpkg.ContentTypeConstraint, ctxpkg.ContentTypeSuccessCriterion:
		return TreeFamilyConstraint
	case ctxpkg.ContentTypeDecision, ctxpkg.ContentTypePlanWorkflow:
		return TreeFamilyIntent
	case ctxpkg.ContentTypeOutcome:
		return TreeFamilyOutcome
	case ctxpkg.ContentTypePreference:
		return TreeFamilyConstraint
	case ctxpkg.ContentTypeHypothesis:
		if strings.EqualFold(entry.Facet, "conflict") {
			return TreeFamilyAntiPattern
		}
		return TreeFamilyIntent
	case ctxpkg.ContentTypeBranchSummary:
		if entry.Facet != "" {
			return TreeFamily(entry.Facet)
		}
		return TreeFamilyEvidence
	}

	agentType := strings.ToLower(entry.AgentType)
	switch {
	case strings.HasPrefix(agentType, "scribe-"):
		return TreeFamilyEvidence
	case agentType == "guardian":
		return TreeFamilyConstraint
	case agentType == "designer":
		return TreeFamilyIntent
	case agentType == "engineer":
		return TreeFamilyIntent
	case agentType == "archivalist":
		return TreeFamilyOutcome
	case agentType == "academic", agentType == "librarian":
		return TreeFamilyEvidence
	default:
		return TreeFamilyEvidence
	}
}

func scopeFromContentEntry(entry *ctxpkg.ContentEntry, family TreeFamily) MemoryScope {
	if entry.Scope != "" {
		return MemoryScope(entry.Scope)
	}
	switch entry.ContentType {
	case ctxpkg.ContentTypeResearchPaper, ctxpkg.ContentTypeWebFetch, ctxpkg.ContentTypeCodeFile:
		if entry.SessionID == "" {
			return ScopeSemantic
		}
		return ScopeEpisodic
	case ctxpkg.ContentTypeBranchSummary:
		return ScopeSemantic
	}

	agentType := strings.ToLower(entry.AgentType)
	switch {
	case strings.HasPrefix(agentType, "scribe-"):
		return ScopeWorking
	case agentType == "guardian":
		return ScopeSemantic
	default:
		// Issue #11 Phase 3: Preference + Capability merged into
		// Constraint + Intent respectively; both now route through
		// the existing family checks below.
		if family == TreeFamilyConstraint {
			return ScopeSemantic
		}
		return ScopeEpisodic
	}
}

func applyEvent(branch *Branch, event *Event) *Branch {
	now := event.Timestamp
	if branch == nil {
		branch = &Branch{
			ID:         event.BranchID,
			RootID:     event.RootID,
			ParentID:   event.ParentBranchID,
			Family:     event.Family,
			Scope:      event.Scope,
			State:      BranchStateActive,
			SessionID:  event.SessionID,
			TaskID:     event.TaskID,
			AgentID:    event.AgentID,
			AgentType:  event.AgentType,
			IntentID:   event.IntentID,
			Title:      event.Title,
			Summary:    event.Summary,
			Confidence: event.Confidence,
			Salience:   event.Salience,
			Utility:    0.5,
			CreatedAt:  now,
			UpdatedAt:  now,
			Metadata:   map[string]any{},
		}
	}

	branch.RootID = firstNonEmpty(branch.RootID, event.RootID)
	branch.ParentID = firstNonEmpty(branch.ParentID, event.ParentBranchID)
	branch.Family = nonEmptyFamily(branch.Family, event.Family)
	branch.Scope = nonEmptyScope(branch.Scope, event.Scope)
	branch.SessionID = firstNonEmpty(branch.SessionID, event.SessionID)
	branch.TaskID = firstNonEmpty(branch.TaskID, event.TaskID)
	branch.AgentID = firstNonEmpty(branch.AgentID, event.AgentID)
	branch.AgentType = firstNonEmpty(branch.AgentType, event.AgentType)
	branch.IntentID = firstNonEmpty(branch.IntentID, event.IntentID)
	branch.Title = chooseText(branch.Title, event.Title)
	branch.Summary = chooseText(branch.Summary, event.Summary)
	branch.Confidence = blend(branch.Confidence, event.Confidence, event.Salience)
	branch.Salience = mathMax(branch.Salience*0.85, event.Salience)
	branch.UpdatedAt = now

	switch event.EventType {
	case EventTypeDecisionRecorded:
		branch.SupportCount++
		branch.Utility = clamp01(branch.Utility + 0.05)
	case EventTypePreferenceRecorded:
		branch.SupportCount++
		branch.Utility = clamp01(branch.Utility + 0.03)
	case EventTypeOutcomeRecorded:
		branch.SupportCount++
		applyOutcomeImpact(branch, event)
	case EventTypeValidation:
		branch.SupportCount++
		branch.State = BranchStateValidated
		branch.Utility = clamp01(branch.Utility + 0.08)
	case EventTypeContradiction:
		branch.CounterCount++
		branch.State = BranchStateContradicted
	case EventTypeReplayPromoted, EventTypeReplayConsolidated:
		branch.Scope = ScopeSemantic
		branch.Utility = clamp01(branch.Utility + 0.04)
	case EventTypeEcologyPruned:
		branch.State = BranchStateDormant
	case EventTypeEcologyRegrown:
		branch.State = BranchStateActive
	case EventTypeClaimAccepted:
		branch.SupportCount++
		branch.SuccessCount++
		branch.Utility = clamp01(branch.Utility + 0.08)
		enrichClaimsMetadata(branch, event)
	case EventTypeClaimRejected:
		branch.CounterCount++
		branch.FailureCount++
		branch.Utility = clamp01(branch.Utility - 0.05)
		enrichClaimsMetadata(branch, event)
	case EventTypeTestamentRecorded:
		branch.SupportCount++
		enrichClaimsMetadata(branch, event)
	default:
		branch.SupportCount++
	}

	if len(event.Supersedes) > 0 {
		branch.State = BranchStateSuperseded
	}
	if len(event.Contradicts) > 0 {
		branch.CounterCount += len(event.Contradicts)
	}
	branch.ConflictScore = computeConflictScore(branch)
	if branch.State == BranchStateActive && branch.ConflictScore > 0.75 {
		branch.State = BranchStateContradicted
	}
	branch.SuccessRate = computeSuccessRate(branch)

	if branch.Metadata == nil {
		branch.Metadata = make(map[string]any)
	}
	branch.Metadata["last_event_type"] = event.EventType
	branch.Metadata["last_event_id"] = event.ID
	branch.Metadata["last_payload"] = event.Payload
	return branch
}

// enrichClaimsMetadata copies claims-specific payload fields into the
// branch metadata so forest skills return structured claim provenance.
func enrichClaimsMetadata(branch *Branch, event *Event) {
	if event.Payload == nil {
		return
	}
	for _, key := range []string{"claim_id", "testament_id", "testament_ids", "artifact_count", "validation_verdicts"} {
		if v, ok := event.Payload[key]; ok {
			branch.Metadata[key] = v
		}
	}
}

func applyOutcomeImpact(branch *Branch, event *Event) {
	status, _ := event.Payload["status"].(OutcomeStatus)
	if status == "" {
		if raw, ok := event.Payload["status"].(string); ok {
			status = OutcomeStatus(raw)
		}
	}
	switch status {
	case OutcomeStatusSucceeded:
		branch.SuccessCount++
		branch.Utility = clamp01(branch.Utility + 0.15)
		branch.State = BranchStateValidated
	case OutcomeStatusFailed:
		branch.FailureCount++
		branch.CounterCount++
		branch.ScopeRisk = clamp01(branch.ScopeRisk + 0.1)
		branch.Utility = clamp01(branch.Utility - 0.12)
	case OutcomeStatusMixed:
		branch.SuccessCount++
		branch.FailureCount++
		branch.Utility = clamp01(branch.Utility + 0.02)
	}
}

func computeConflictScore(branch *Branch) float64 {
	total := branch.SupportCount + branch.CounterCount
	if total == 0 {
		return 0
	}
	return float64(branch.CounterCount) / float64(total)
}

func computeSuccessRate(branch *Branch) float64 {
	total := branch.SuccessCount + branch.FailureCount
	if total == 0 {
		return 0.5
	}
	return float64(branch.SuccessCount) / float64(total)
}

func getBranchTx(ctx context.Context, tx *sql.Tx, branchID string) (*Branch, error) {
	row := tx.QueryRowContext(ctx, `
		SELECT id, root_id, parent_id, family, scope, state, session_id, task_id, agent_id, agent_type,
		       intent_id, title, summary, confidence, salience, utility, success_rate,
		       scope_risk, conflict_score, support_count, counter_count, success_count,
		       failure_count, access_count, last_accessed_at, created_at, updated_at, metadata,
		       last_applied_seq, constraint_severity
		FROM forest_branches
		WHERE id = ?
	`, branchID)
	return scanBranch(row)
}

func (m *MemoryForest) getBranch(ctx context.Context, branchID string) (*Branch, error) {
	row := m.db.QueryRowContext(ctx, `
		SELECT id, root_id, parent_id, family, scope, state, session_id, task_id, agent_id, agent_type,
		       intent_id, title, summary, confidence, salience, utility, success_rate,
		       scope_risk, conflict_score, support_count, counter_count, success_count,
		       failure_count, access_count, last_accessed_at, created_at, updated_at, metadata,
		       last_applied_seq, constraint_severity
		FROM forest_branches
		WHERE id = ?
	`, branchID)
	return scanBranch(row)
}

func scanBranch(row rowScanner) (*Branch, error) {
	var (
		branch             Branch
		parentID           sql.NullString
		taskID             sql.NullString
		agentID            sql.NullString
		agentType          sql.NullString
		intentID           sql.NullString
		lastAccessedAt     int64
		createdAt          int64
		updatedAt          int64
		metadataRaw        sql.NullString
		lastAppliedSeq     int64
		constraintSeverity sql.NullString
	)
	err := row.Scan(
		&branch.ID, &branch.RootID, &parentID, &branch.Family, &branch.Scope, &branch.State,
		&branch.SessionID, &taskID, &agentID, &agentType, &intentID, &branch.Title, &branch.Summary,
		&branch.Confidence, &branch.Salience, &branch.Utility, &branch.SuccessRate, &branch.ScopeRisk,
		&branch.ConflictScore, &branch.SupportCount, &branch.CounterCount, &branch.SuccessCount,
		&branch.FailureCount, &branch.AccessCount, &lastAccessedAt, &createdAt, &updatedAt, &metadataRaw,
		&lastAppliedSeq, &constraintSeverity,
	)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("scan branch: %w", err)
	}
	branch.ParentID = parentID.String
	branch.TaskID = taskID.String
	branch.AgentID = agentID.String
	branch.AgentType = agentType.String
	branch.IntentID = intentID.String
	if lastAccessedAt > 0 {
		branch.LastAccessedAt = time.Unix(lastAccessedAt, 0).UTC()
	}
	branch.CreatedAt = time.Unix(createdAt, 0).UTC()
	branch.UpdatedAt = time.Unix(updatedAt, 0).UTC()
	if metadataRaw.Valid {
		_ = unmarshalJSON(metadataRaw.String, &branch.Metadata)
	}
	branch.LastAppliedSeq = lastAppliedSeq
	branch.ConstraintSeverity = ConstraintSeverity(constraintSeverity.String)
	return &branch, nil
}

type rowScanner interface {
	Scan(dest ...any) error
}

func upsertBranchTx(ctx context.Context, tx *sql.Tx, branch *Branch) error {
	_, err := tx.ExecContext(ctx, `
		INSERT INTO forest_branches
		(id, root_id, parent_id, family, scope, state, session_id, task_id, agent_id, agent_type,
		 intent_id, title, summary, confidence, salience, utility, success_rate, scope_risk,
		 conflict_score, support_count, counter_count, success_count, failure_count,
		 access_count, last_accessed_at, created_at, updated_at, metadata, last_applied_seq,
		 constraint_severity)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
		ON CONFLICT(id) DO UPDATE SET
			root_id = excluded.root_id,
			parent_id = excluded.parent_id,
			family = excluded.family,
			scope = excluded.scope,
			state = excluded.state,
			session_id = excluded.session_id,
			task_id = excluded.task_id,
			agent_id = excluded.agent_id,
			agent_type = excluded.agent_type,
			intent_id = excluded.intent_id,
			title = excluded.title,
			summary = excluded.summary,
			confidence = excluded.confidence,
			salience = excluded.salience,
			utility = excluded.utility,
			success_rate = excluded.success_rate,
			scope_risk = excluded.scope_risk,
			conflict_score = excluded.conflict_score,
			support_count = excluded.support_count,
			counter_count = excluded.counter_count,
			success_count = excluded.success_count,
			failure_count = excluded.failure_count,
			access_count = excluded.access_count,
			last_accessed_at = excluded.last_accessed_at,
			updated_at = excluded.updated_at,
			metadata = excluded.metadata,
			last_applied_seq = excluded.last_applied_seq,
			constraint_severity = excluded.constraint_severity
	`, branch.ID, branch.RootID, nullStringValue(branch.ParentID), string(branch.Family), string(branch.Scope),
		string(branch.State), branch.SessionID, nullStringValue(branch.TaskID), nullStringValue(branch.AgentID), nullStringValue(branch.AgentType),
		nullStringValue(branch.IntentID), branch.Title, branch.Summary, branch.Confidence, branch.Salience, branch.Utility,
		branch.SuccessRate, branch.ScopeRisk, branch.ConflictScore, branch.SupportCount, branch.CounterCount,
		branch.SuccessCount, branch.FailureCount, branch.AccessCount, branch.LastAccessedAt.Unix(), branch.CreatedAt.Unix(),
		branch.UpdatedAt.Unix(), marshalJSON(branch.Metadata), branch.LastAppliedSeq,
		string(branch.ConstraintSeverity))
	if err != nil {
		return fmt.Errorf("upsert branch: %w", err)
	}
	return nil
}

func upsertRelayEdgesTx(ctx context.Context, tx *sql.Tx, event *Event) error {
	pairs := make([]relayUpdate, 0, len(event.RelatedBranchIDs)+len(event.Contradicts)+len(event.Supersedes)+1)
	if event.ParentBranchID != "" && event.ParentBranchID != event.BranchID {
		pairs = append(pairs, relayUpdate{event.BranchID, event.ParentBranchID, RelayRelationCoOccurs, 0.12})
	}
	for _, branchID := range event.RelatedBranchIDs {
		if branchID == event.BranchID {
			continue
		}
		pairs = append(pairs, relayUpdate{event.BranchID, branchID, RelayRelationSupports, 0.10})
	}
	for _, branchID := range event.Contradicts {
		pairs = append(pairs, relayUpdate{event.BranchID, branchID, RelayRelationContradicts, 0.18})
	}
	for _, branchID := range event.Supersedes {
		pairs = append(pairs, relayUpdate{event.BranchID, branchID, RelayRelationSupersedes, 0.16})
	}

	for _, pair := range pairs {
		if _, err := tx.ExecContext(ctx, `
			INSERT INTO forest_relay_edges
			(source_branch_id, target_branch_id, relation, weight, cofire_count, last_reinforced_at, metadata)
			VALUES (?, ?, ?, ?, 1, ?, '{}')
			ON CONFLICT(source_branch_id, target_branch_id, relation) DO UPDATE SET
				weight = MIN(2.0, forest_relay_edges.weight + excluded.weight),
				cofire_count = forest_relay_edges.cofire_count + 1,
				last_reinforced_at = excluded.last_reinforced_at
		`, pair.SourceID, pair.TargetID, string(pair.Relation), pair.Weight, event.Timestamp.Unix()); err != nil {
			return fmt.Errorf("upsert relay edge: %w", err)
		}
	}
	return nil
}

type relayUpdate struct {
	SourceID string
	TargetID string
	Relation RelayRelation
	Weight   float64
}

func refreshCanopiesTx(ctx context.Context, tx *sql.Tx, sessionID, taskID, intentID string) error {
	if sessionID == "" {
		sessionID = "global"
	}
	taskID = normalizeForestTaskID(taskID)
	sessionRoots, err := topRootsTx(ctx, tx, `
		SELECT root_id
		FROM forest_branches
		WHERE session_id = ? AND state != ?
		GROUP BY root_id
		ORDER BY MAX(salience) DESC, MAX(updated_at) DESC
		LIMIT 8
	`, sessionID, string(BranchStateDormant))
	if err != nil {
		return err
	}
	if err := upsertCanopyVariantsTx(ctx, tx, Canopy{
		SessionID: sessionID,
		Horizon:   CanopyHorizonSession,
		RootIDs:   sessionRoots,
		Summary:   summarizeText(strings.Join(sessionRoots, " "), 160),
		UpdatedAt: time.Now().UTC(),
	}, intentID); err != nil {
		return err
	}

	if taskID != "" {
		taskRoots, err := topRootsTx(ctx, tx, `
			SELECT root_id
			FROM forest_branches
			WHERE session_id = ? AND task_id = ? AND state != ?
			GROUP BY root_id
			ORDER BY MAX(salience) DESC, MAX(updated_at) DESC
			LIMIT 8
		`, sessionID, taskID, string(BranchStateDormant))
		if err != nil {
			return err
		}
		if err := upsertCanopyVariantsTx(ctx, tx, Canopy{
			SessionID: sessionID,
			TaskID:    taskID,
			Horizon:   CanopyHorizonTask,
			RootIDs:   taskRoots,
			Summary:   summarizeText(strings.Join(taskRoots, " "), 160),
			UpdatedAt: time.Now().UTC(),
		}, intentID); err != nil {
			return err
		}
	}

	projectRoots, err := topRootsTx(ctx, tx, `
		SELECT root_id
		FROM forest_branches
		WHERE state != ?
		GROUP BY root_id
		ORDER BY MAX(utility) DESC, MAX(updated_at) DESC
		LIMIT 8
	`, string(BranchStateDormant))
	if err != nil {
		return err
	}
	return upsertCanopyTx(ctx, tx, Canopy{
		Horizon:   CanopyHorizonProject,
		RootIDs:   projectRoots,
		Summary:   summarizeText(strings.Join(projectRoots, " "), 160),
		UpdatedAt: time.Now().UTC(),
	})
}

func upsertCanopyVariantsTx(ctx context.Context, tx *sql.Tx, canopy Canopy, intentID string) error {
	canopy.IntentID = ""
	canopy.Key = canopyKey(canopy.Horizon, canopy.SessionID, canopy.TaskID, "")
	if err := upsertCanopyTx(ctx, tx, canopy); err != nil {
		return err
	}
	intentID = strings.TrimSpace(intentID)
	if intentID == "" {
		return nil
	}
	canopy.IntentID = intentID
	canopy.Key = canopyKey(canopy.Horizon, canopy.SessionID, canopy.TaskID, intentID)
	return upsertCanopyTx(ctx, tx, canopy)
}

func topRootsTx(ctx context.Context, tx *sql.Tx, query string, args ...any) ([]string, error) {
	rows, err := tx.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("query canopy roots: %w", err)
	}
	defer rows.Close()

	var roots []string
	for rows.Next() {
		var rootID string
		if err := rows.Scan(&rootID); err != nil {
			return nil, fmt.Errorf("scan canopy root: %w", err)
		}
		roots = append(roots, rootID)
	}
	return roots, rows.Err()
}

func upsertCanopyTx(ctx context.Context, tx *sql.Tx, canopy Canopy) error {
	_, err := tx.ExecContext(ctx, `
		INSERT INTO forest_canopies (canopy_key, session_id, task_id, intent_id, horizon, root_ids, summary, updated_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?)
		ON CONFLICT(canopy_key) DO UPDATE SET
			root_ids = excluded.root_ids,
			summary = excluded.summary,
			updated_at = excluded.updated_at
	`, canopy.Key, nullStringValue(canopy.SessionID), nullStringValue(canopy.TaskID), nullStringValue(canopy.IntentID), string(canopy.Horizon),
		marshalJSON(canopy.RootIDs), canopy.Summary, canopy.UpdatedAt.Unix())
	if err != nil {
		return fmt.Errorf("upsert canopy: %w", err)
	}
	return nil
}

func markSubstrateDirtyTx(ctx context.Context, tx *sql.Tx, sessionID string, at time.Time) error {
	sessionID = normalizeForestSessionID(sessionID)
	if at.IsZero() {
		at = time.Now().UTC()
	}
	_, err := tx.ExecContext(ctx, `
		INSERT INTO forest_substrate_sessions
		(session_id, graph_version, substrate_version, dirty, dirty_at, updated_at)
		VALUES (?, 1, 0, 1, ?, ?)
		ON CONFLICT(session_id) DO UPDATE SET
			graph_version = forest_substrate_sessions.graph_version + 1,
			dirty = 1,
			dirty_at = excluded.dirty_at,
			updated_at = excluded.updated_at
	`, sessionID, at.Unix(), at.Unix())
	if err != nil {
		return fmt.Errorf("mark substrate dirty: %w", err)
	}
	return nil
}

func (m *MemoryForest) enqueueReplayTx(ctx context.Context, tx *sql.Tx, branch *Branch, event *Event) (time.Time, error) {
	priority := replayPriority(branch, event)
	if priority < 0.45 {
		return time.Time{}, nil
	}
	availableAt := event.Timestamp.Add(m.hyperparams().ReplayDelay).UTC()
	_, err := tx.ExecContext(ctx, `
		INSERT INTO forest_replay_queue
		(branch_id, root_id, priority, reason, state, available_at, payload)
		VALUES (?, ?, ?, ?, ?, ?, ?)
	`, branch.ID, branch.RootID, priority, string(event.EventType), string(ReplayStateQueued),
		availableAt.Unix(), marshalJSON(event.Payload))
	if err != nil {
		return time.Time{}, fmt.Errorf("enqueue replay: %w", err)
	}
	return availableAt, nil
}

func replayPriority(branch *Branch, event *Event) float64 {
	priority := (branch.Salience * 0.35) + (branch.Confidence * 0.25) + (branch.Utility * 0.20) + (1-branch.ConflictScore)*0.20
	if branch != nil && branch.Metadata != nil {
		priority += 0.10 * metadataFloat(branch.Metadata, "substrate_frontier")
		priority -= 0.08 * metadataFloat(branch.Metadata, "substrate_inhibition")
	}
	switch {
	case strings.EqualFold(branch.AgentType, "guardian"):
		priority += 0.15
	case strings.HasPrefix(strings.ToLower(branch.AgentType), "scribe-"):
		priority += 0.10
	}
	switch event.EventType {
	case EventTypeOutcomeRecorded, EventTypeContradiction, EventTypeValidation:
		priority += 0.10
	}
	return clamp01(priority)
}

func (m *MemoryForest) RunReplay(ctx context.Context, limit int) (ReplayResult, error) {
	m.maintenanceRunMu.Lock()
	defer m.maintenanceRunMu.Unlock()

	result, _, err := m.runReplay(ctx, limit)
	return result, err
}

func (m *MemoryForest) runReplay(ctx context.Context, limit int) (ReplayResult, []string, error) {
	if limit <= 0 {
		limit = 8
	}

	rows, err := m.db.QueryContext(ctx, `
		SELECT id, branch_id, root_id, priority, reason, payload
		FROM forest_replay_queue
		WHERE state = ? AND available_at <= ?
		ORDER BY priority DESC, available_at ASC
		LIMIT ?
	`, string(ReplayStateQueued), time.Now().UTC().Unix(), limit)
	if err != nil {
		return ReplayResult{}, nil, fmt.Errorf("query replay queue: %w", err)
	}

	var items []replayItem
	for rows.Next() {
		var item replayItem
		if err := rows.Scan(&item.ID, &item.BranchID, &item.RootID, &item.Priority, &item.Reason, &item.Payload); err != nil {
			_ = rows.Close()
			return ReplayResult{}, nil, fmt.Errorf("scan replay queue: %w", err)
		}
		items = append(items, item)
	}
	if err := rows.Close(); err != nil {
		return ReplayResult{}, nil, err
	}
	if err := rows.Err(); err != nil {
		return ReplayResult{}, nil, err
	}

	var (
		result          ReplayResult
		touchedSessions []string
	)
	for _, item := range items {
		result.Processed++
		promoted, sessionID, err := m.replayBranch(ctx, item.ID, item.BranchID, item.RootID, item.Priority, item.Reason, item.Payload.String)
		if err != nil {
			return result, touchedSessions, err
		}
		if promoted {
			result.Promoted++
		}
		if sessionID != "" {
			touchedSessions = append(touchedSessions, sessionID)
		}
	}
	return result, dedupeStrings(touchedSessions), nil
}

type replayItem struct {
	ID       int64
	BranchID string
	RootID   string
	Priority float64
	Reason   string
	Payload  sql.NullString
}

func (m *MemoryForest) replayBranch(ctx context.Context, queueID int64, branchID, rootID string, priority float64, reason, payload string) (bool, string, error) {
	branch, err := m.getBranch(ctx, branchID)
	if err != nil {
		return false, "", err
	}
	if branch == nil {
		_, _ = m.db.ExecContext(ctx, `UPDATE forest_replay_queue SET state = ? WHERE id = ?`, string(ReplayStateComplete), queueID)
		return false, "", nil
	}

	_, err = m.db.ExecContext(ctx, `UPDATE forest_replay_queue SET state = ?, attempts = attempts + 1 WHERE id = ?`, string(ReplayStateRunning), queueID)
	if err != nil {
		return false, "", fmt.Errorf("mark replay running: %w", err)
	}

	promoted := false
	if branch.Scope == ScopeEpisodic || branch.Scope == ScopeWorking {
		now := time.Now().UTC()
		semanticID := stableID("semantic", branch.RootID, branch.TaskID, normalizeText(branch.Title))
		semanticBranch := &Branch{
			ID:             semanticID,
			RootID:         branch.RootID,
			ParentID:       branch.ID,
			Family:         branch.Family,
			Scope:          ScopeSemantic,
			State:          BranchStateActive,
			SessionID:      branch.SessionID,
			TaskID:         branch.TaskID,
			AgentID:        branch.AgentID,
			AgentType:      branch.AgentType,
			IntentID:       firstNonEmpty(branch.IntentID, rootID),
			Title:          branch.Title,
			Summary:        summarizeText(branch.Summary, 240),
			Confidence:     clamp01((branch.Confidence + priority) / 2),
			Salience:       clamp01(branch.Salience),
			Utility:        clamp01((branch.Utility + priority) / 2),
			SuccessRate:    branch.SuccessRate,
			ScopeRisk:      branch.ScopeRisk,
			ConflictScore:  branch.ConflictScore,
			SupportCount:   branch.SupportCount,
			CounterCount:   branch.CounterCount,
			SuccessCount:   branch.SuccessCount,
			FailureCount:   branch.FailureCount,
			AccessCount:    branch.AccessCount,
			LastAccessedAt: branch.LastAccessedAt,
			CreatedAt:      now,
			UpdatedAt:      now,
			Metadata: map[string]any{
				"replay_reason":  reason,
				"replay_payload": payload,
				"source_branch":  branch.ID,
			},
		}

		tx, err := m.db.BeginTx(ctx, nil)
		if err != nil {
			return false, "", fmt.Errorf("begin replay tx: %w", err)
		}
		defer tx.Rollback()

		if err := upsertBranchTx(ctx, tx, semanticBranch); err != nil {
			return false, "", err
		}
		if err := upsertRelayEdgesTx(ctx, tx, &Event{
			BranchID:         semanticBranch.ID,
			ParentBranchID:   branch.ID,
			RelatedBranchIDs: []string{branch.ID},
			Timestamp:        now,
		}); err != nil {
			return false, "", err
		}
		if err := refreshCanopiesTx(ctx, tx, branch.SessionID, branch.TaskID, semanticBranch.IntentID); err != nil {
			return false, "", err
		}
		if err := markSubstrateDirtyTx(ctx, tx, branch.SessionID, now); err != nil {
			return false, "", err
		}
		if _, err := tx.ExecContext(ctx, `UPDATE forest_replay_queue SET state = ? WHERE id = ?`, string(ReplayStateComplete), queueID); err != nil {
			return false, "", err
		}
		if err := tx.Commit(); err != nil {
			return false, "", fmt.Errorf("commit replay tx: %w", err)
		}
		_ = m.warmth.RecordAccess(ctx, semanticBranch.ID, memory.AccessReinforcement, "replay")
		promoted = true
		return promoted, branch.SessionID, nil
	}

	_, err = m.db.ExecContext(ctx, `UPDATE forest_replay_queue SET state = ? WHERE id = ?`, string(ReplayStateComplete), queueID)
	if err != nil {
		return false, "", fmt.Errorf("complete replay queue item: %w", err)
	}
	return false, "", nil
}

func (m *MemoryForest) RunEcology(ctx context.Context) (EcologyResult, error) {
	m.maintenanceRunMu.Lock()
	defer m.maintenanceRunMu.Unlock()

	now := time.Now().UTC()
	result := EcologyResult{}

	dormantRows, err := m.db.QueryContext(ctx, `
		SELECT id, updated_at, access_count
		FROM forest_branches
		WHERE state NOT IN (?, ?) AND scope != ?
	`, string(BranchStateDormant), string(BranchStateSuperseded), string(ScopeSemantic))
	if err != nil {
		return result, fmt.Errorf("query ecology candidates: %w", err)
	}
	defer dormantRows.Close()

	for dormantRows.Next() {
		var (
			branchID    string
			updatedAt   int64
			accessCount int
		)
		if err := dormantRows.Scan(&branchID, &updatedAt, &accessCount); err != nil {
			return result, fmt.Errorf("scan ecology candidate: %w", err)
		}
		updated := time.Unix(updatedAt, 0).UTC()
		if accessCount == 0 && now.Sub(updated) > 7*24*time.Hour {
			if _, err := m.db.ExecContext(ctx, `
				UPDATE forest_branches
				SET state = ?, scope = ?
				WHERE id = ?
			`, string(BranchStateDormant), string(ScopeDormant), branchID); err != nil {
				return result, fmt.Errorf("mark dormant: %w", err)
			}
			result.Dormant++
		}
	}
	if err := dormantRows.Err(); err != nil {
		return result, err
	}

	_, err = m.db.ExecContext(ctx, `
		UPDATE forest_branches
		SET state = ?, scope = ?
		WHERE state = ? AND access_count > 0 AND updated_at >= ?
	`, string(BranchStateActive), string(ScopeEpisodic), string(BranchStateDormant), now.Add(-24*time.Hour).Unix())
	if err != nil {
		return result, fmt.Errorf("regrow dormant branches: %w", err)
	}

	row := m.db.QueryRowContext(ctx, `
		SELECT COUNT(*)
		FROM forest_branches
		WHERE state = ? AND access_count > 0 AND updated_at >= ?
	`, string(BranchStateActive), now.Add(-24*time.Hour).Unix())
	_ = row.Scan(&result.Regrown)

	return result, nil
}

func chooseText(current, candidate string) string {
	candidate = strings.TrimSpace(candidate)
	if candidate == "" {
		return current
	}
	if strings.TrimSpace(current) == "" || len(candidate) > len(current) {
		return candidate
	}
	return current
}

func blend(current, candidate, salience float64) float64 {
	if current == 0 {
		return candidate
	}
	weight := clamp01(salience)
	if weight == 0 {
		weight = 0.5
	}
	return (current * (1 - weight)) + (candidate * weight)
}

func mathMax(a, b float64) float64 {
	if a > b {
		return a
	}
	return b
}

func firstNonEmpty(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return value
		}
	}
	return ""
}

func nonEmptyFamily(current, candidate TreeFamily) TreeFamily {
	if current != "" {
		return current
	}
	return candidate
}

func nonEmptyScope(current, candidate MemoryScope) MemoryScope {
	if current != "" {
		return current
	}
	return candidate
}

func nullStringValue(value string) any {
	value = strings.TrimSpace(value)
	if value == "" {
		return nil
	}
	return value
}

func forestTaskIDFromPayload(payload map[string]any) string {
	if len(payload) == 0 {
		return ""
	}
	if taskID := forestTaskIDFromAny(payload["task_id"]); taskID != "" {
		return taskID
	}
	if metadata, ok := payload["metadata"].(map[string]any); ok {
		return forestTaskIDFromAnyMetadata(metadata)
	}
	return ""
}
