// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockRetryPolicy is an autogenerated mock type for the RetryPolicyService type
type MockRetryPolicy struct {
	mock.Mock
}

type MockRetryPolicy_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRetryPolicy) EXPECT() *MockRetryPolicy_Expecter {
	return &MockRetryPolicy_Expecter{mock: &_m.Mock}
}

// MaxAttempts provides a mock function with no fields
func (_m *MockRetryPolicy) MaxAttempts() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MaxAttempts")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockRetryPolicy_MaxAttempts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MaxAttempts'
type MockRetryPolicy_MaxAttempts_Call struct {
	*mock.Call
}

// MaxAttempts is a helper method to define mock.On call
func (_e *MockRetryPolicy_Expecter) MaxAttempts() *MockRetryPolicy_MaxAttempts_Call {
	return &MockRetryPolicy_MaxAttempts_Call{Call: _e.mock.On("MaxAttempts")}
}

func (_c *MockRetryPolicy_MaxAttempts_Call) Run(run func()) *MockRetryPolicy_MaxAttempts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRetryPolicy_MaxAttempts_Call) Return(_a0 int) *MockRetryPolicy_MaxAttempts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRetryPolicy_MaxAttempts_Call) RunAndReturn(run func() int) *MockRetryPolicy_MaxAttempts_Call {
	_c.Call.Return(run)
	return _c
}

// NextDelay provides a mock function with given fields: attempt
func (_m *MockRetryPolicy) NextDelay(attempt int) time.Duration {
	ret := _m.Called(attempt)

	if len(ret) == 0 {
		panic("no return value specified for NextDelay")
	}

	var r0 time.Duration
	if rf, ok := ret.Get(0).(func(int) time.Duration); ok {
		r0 = rf(attempt)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	return r0
}

// MockRetryPolicy_NextDelay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextDelay'
type MockRetryPolicy_NextDelay_Call struct {
	*mock.Call
}

// NextDelay is a helper method to define mock.On call
//   - attempt int
func (_e *MockRetryPolicy_Expecter) NextDelay(attempt interface{}) *MockRetryPolicy_NextDelay_Call {
	return &MockRetryPolicy_NextDelay_Call{Call: _e.mock.On("NextDelay", attempt)}
}

func (_c *MockRetryPolicy_NextDelay_Call) Run(run func(attempt int)) *MockRetryPolicy_NextDelay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockRetryPolicy_NextDelay_Call) Return(_a0 time.Duration) *MockRetryPolicy_NextDelay_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRetryPolicy_NextDelay_Call) RunAndReturn(run func(int) time.Duration) *MockRetryPolicy_NextDelay_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldRetry provides a mock function with given fields: attempt, err
func (_m *MockRetryPolicy) ShouldRetry(attempt int, err error) bool {
	ret := _m.Called(attempt, err)

	if len(ret) == 0 {
		panic("no return value specified for ShouldRetry")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, error) bool); ok {
		r0 = rf(attempt, err)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockRetryPolicy_ShouldRetry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldRetry'
type MockRetryPolicy_ShouldRetry_Call struct {
	*mock.Call
}

// ShouldRetry is a helper method to define mock.On call
//   - attempt int
//   - err error
func (_e *MockRetryPolicy_Expecter) ShouldRetry(attempt interface{}, err interface{}) *MockRetryPolicy_ShouldRetry_Call {
	return &MockRetryPolicy_ShouldRetry_Call{Call: _e.mock.On("ShouldRetry", attempt, err)}
}

func (_c *MockRetryPolicy_ShouldRetry_Call) Run(run func(attempt int, err error)) *MockRetryPolicy_ShouldRetry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(error))
	})
	return _c
}

func (_c *MockRetryPolicy_ShouldRetry_Call) Return(_a0 bool) *MockRetryPolicy_ShouldRetry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRetryPolicy_ShouldRetry_Call) RunAndReturn(run func(int, error) bool) *MockRetryPolicy_ShouldRetry_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRetryPolicy creates a new instance of MockRetryPolicy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRetryPolicy(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRetryPolicy {
	mock := &MockRetryPolicy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
