// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	guide "github.com/adalundhe/sylk/agents/guide"
	mock "github.com/stretchr/testify/mock"
)

// MockRegistry is an autogenerated mock type for the RegistryService type
type MockRegistry struct {
	mock.Mock
}

type MockRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistry) EXPECT() *MockRegistry_Expecter {
	return &MockRegistry_Expecter{mock: &_m.Mock}
}

// FindBestMatch provides a mock function with given fields: result
func (_m *MockRegistry) FindBestMatch(result *guide.RouteResult) *guide.AgentRegistration {
	ret := _m.Called(result)

	if len(ret) == 0 {
		panic("no return value specified for FindBestMatch")
	}

	var r0 *guide.AgentRegistration
	if rf, ok := ret.Get(0).(func(*guide.RouteResult) *guide.AgentRegistration); ok {
		r0 = rf(result)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*guide.AgentRegistration)
		}
	}

	return r0
}

// MockRegistry_FindBestMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBestMatch'
type MockRegistry_FindBestMatch_Call struct {
	*mock.Call
}

// FindBestMatch is a helper method to define mock.On call
//   - result *guide.RouteResult
func (_e *MockRegistry_Expecter) FindBestMatch(result interface{}) *MockRegistry_FindBestMatch_Call {
	return &MockRegistry_FindBestMatch_Call{Call: _e.mock.On("FindBestMatch", result)}
}

func (_c *MockRegistry_FindBestMatch_Call) Run(run func(result *guide.RouteResult)) *MockRegistry_FindBestMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*guide.RouteResult))
	})
	return _c
}

func (_c *MockRegistry_FindBestMatch_Call) Return(_a0 *guide.AgentRegistration) *MockRegistry_FindBestMatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_FindBestMatch_Call) RunAndReturn(run func(*guide.RouteResult) *guide.AgentRegistration) *MockRegistry_FindBestMatch_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: id
func (_m *MockRegistry) Get(id string) *guide.AgentRegistration {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *guide.AgentRegistration
	if rf, ok := ret.Get(0).(func(string) *guide.AgentRegistration); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*guide.AgentRegistration)
		}
	}

	return r0
}

// MockRegistry_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRegistry_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *MockRegistry_Expecter) Get(id interface{}) *MockRegistry_Get_Call {
	return &MockRegistry_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockRegistry_Get_Call) Run(run func(id string)) *MockRegistry_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistry_Get_Call) Return(_a0 *guide.AgentRegistration) *MockRegistry_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_Get_Call) RunAndReturn(run func(string) *guide.AgentRegistration) *MockRegistry_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *MockRegistry) GetAll() []*guide.AgentRegistration {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*guide.AgentRegistration
	if rf, ok := ret.Get(0).(func() []*guide.AgentRegistration); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*guide.AgentRegistration)
		}
	}

	return r0
}

// MockRegistry_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockRegistry_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockRegistry_Expecter) GetAll() *MockRegistry_GetAll_Call {
	return &MockRegistry_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockRegistry_GetAll_Call) Run(run func()) *MockRegistry_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistry_GetAll_Call) Return(_a0 []*guide.AgentRegistration) *MockRegistry_GetAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_GetAll_Call) RunAndReturn(run func() []*guide.AgentRegistration) *MockRegistry_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function with given fields: name
func (_m *MockRegistry) GetByName(name string) *guide.AgentRegistration {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *guide.AgentRegistration
	if rf, ok := ret.Get(0).(func(string) *guide.AgentRegistration); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*guide.AgentRegistration)
		}
	}

	return r0
}

// MockRegistry_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockRegistry_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - name string
func (_e *MockRegistry_Expecter) GetByName(name interface{}) *MockRegistry_GetByName_Call {
	return &MockRegistry_GetByName_Call{Call: _e.mock.On("GetByName", name)}
}

func (_c *MockRegistry_GetByName_Call) Run(run func(name string)) *MockRegistry_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistry_GetByName_Call) Return(_a0 *guide.AgentRegistration) *MockRegistry_GetByName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRegistry_GetByName_Call) RunAndReturn(run func(string) *guide.AgentRegistration) *MockRegistry_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: registration
func (_m *MockRegistry) Register(registration *guide.AgentRegistration) {
	_m.Called(registration)
}

// MockRegistry_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockRegistry_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - registration *guide.AgentRegistration
func (_e *MockRegistry_Expecter) Register(registration interface{}) *MockRegistry_Register_Call {
	return &MockRegistry_Register_Call{Call: _e.mock.On("Register", registration)}
}

func (_c *MockRegistry_Register_Call) Run(run func(registration *guide.AgentRegistration)) *MockRegistry_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*guide.AgentRegistration))
	})
	return _c
}

func (_c *MockRegistry_Register_Call) Return() *MockRegistry_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRegistry_Register_Call) RunAndReturn(run func(*guide.AgentRegistration)) *MockRegistry_Register_Call {
	_c.Run(run)
	return _c
}

// RegisterFromRoutingInfo provides a mock function with given fields: info
func (_m *MockRegistry) RegisterFromRoutingInfo(info *guide.AgentRoutingInfo) {
	_m.Called(info)
}

// MockRegistry_RegisterFromRoutingInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterFromRoutingInfo'
type MockRegistry_RegisterFromRoutingInfo_Call struct {
	*mock.Call
}

// RegisterFromRoutingInfo is a helper method to define mock.On call
//   - info *guide.AgentRoutingInfo
func (_e *MockRegistry_Expecter) RegisterFromRoutingInfo(info interface{}) *MockRegistry_RegisterFromRoutingInfo_Call {
	return &MockRegistry_RegisterFromRoutingInfo_Call{Call: _e.mock.On("RegisterFromRoutingInfo", info)}
}

func (_c *MockRegistry_RegisterFromRoutingInfo_Call) Run(run func(info *guide.AgentRoutingInfo)) *MockRegistry_RegisterFromRoutingInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*guide.AgentRoutingInfo))
	})
	return _c
}

func (_c *MockRegistry_RegisterFromRoutingInfo_Call) Return() *MockRegistry_RegisterFromRoutingInfo_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRegistry_RegisterFromRoutingInfo_Call) RunAndReturn(run func(*guide.AgentRoutingInfo)) *MockRegistry_RegisterFromRoutingInfo_Call {
	_c.Run(run)
	return _c
}

// Unregister provides a mock function with given fields: id
func (_m *MockRegistry) Unregister(id string) {
	_m.Called(id)
}

// MockRegistry_Unregister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unregister'
type MockRegistry_Unregister_Call struct {
	*mock.Call
}

// Unregister is a helper method to define mock.On call
//   - id string
func (_e *MockRegistry_Expecter) Unregister(id interface{}) *MockRegistry_Unregister_Call {
	return &MockRegistry_Unregister_Call{Call: _e.mock.On("Unregister", id)}
}

func (_c *MockRegistry_Unregister_Call) Run(run func(id string)) *MockRegistry_Unregister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistry_Unregister_Call) Return() *MockRegistry_Unregister_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRegistry_Unregister_Call) RunAndReturn(run func(string)) *MockRegistry_Unregister_Call {
	_c.Run(run)
	return _c
}

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
