// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	guide "github.com/adalundhe/sylk/agents/guide"
	mock "github.com/stretchr/testify/mock"
)

// MockParser is an autogenerated mock type for the ParserService type
type MockParser struct {
	mock.Mock
}

type MockParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParser) EXPECT() *MockParser_Expecter {
	return &MockParser_Expecter{mock: &_m.Mock}
}

// IsDSL provides a mock function with given fields: input
func (_m *MockParser) IsDSL(input string) bool {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for IsDSL")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockParser_IsDSL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDSL'
type MockParser_IsDSL_Call struct {
	*mock.Call
}

// IsDSL is a helper method to define mock.On call
//   - input string
func (_e *MockParser_Expecter) IsDSL(input interface{}) *MockParser_IsDSL_Call {
	return &MockParser_IsDSL_Call{Call: _e.mock.On("IsDSL", input)}
}

func (_c *MockParser_IsDSL_Call) Run(run func(input string)) *MockParser_IsDSL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockParser_IsDSL_Call) Return(_a0 bool) *MockParser_IsDSL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockParser_IsDSL_Call) RunAndReturn(run func(string) bool) *MockParser_IsDSL_Call {
	_c.Call.Return(run)
	return _c
}

// Parse provides a mock function with given fields: input
func (_m *MockParser) Parse(input string) (*guide.DSLCommand, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *guide.DSLCommand
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*guide.DSLCommand, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(string) *guide.DSLCommand); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*guide.DSLCommand)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - input string
func (_e *MockParser_Expecter) Parse(input interface{}) *MockParser_Parse_Call {
	return &MockParser_Parse_Call{Call: _e.mock.On("Parse", input)}
}

func (_c *MockParser_Parse_Call) Run(run func(input string)) *MockParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockParser_Parse_Call) Return(_a0 *guide.DSLCommand, _a1 error) *MockParser_Parse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockParser_Parse_Call) RunAndReturn(run func(string) (*guide.DSLCommand, error)) *MockParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// ParseMultiple provides a mock function with given fields: input
func (_m *MockParser) ParseMultiple(input string) ([]*guide.DSLCommand, []error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for ParseMultiple")
	}

	var r0 []*guide.DSLCommand
	var r1 []error
	if rf, ok := ret.Get(0).(func(string) ([]*guide.DSLCommand, []error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(string) []*guide.DSLCommand); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*guide.DSLCommand)
		}
	}

	if rf, ok := ret.Get(1).(func(string) []error); ok {
		r1 = rf(input)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]error)
		}
	}

	return r0, r1
}

// MockParser_ParseMultiple_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseMultiple'
type MockParser_ParseMultiple_Call struct {
	*mock.Call
}

// ParseMultiple is a helper method to define mock.On call
//   - input string
func (_e *MockParser_Expecter) ParseMultiple(input interface{}) *MockParser_ParseMultiple_Call {
	return &MockParser_ParseMultiple_Call{Call: _e.mock.On("ParseMultiple", input)}
}

func (_c *MockParser_ParseMultiple_Call) Run(run func(input string)) *MockParser_ParseMultiple_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockParser_ParseMultiple_Call) Return(_a0 []*guide.DSLCommand, _a1 []error) *MockParser_ParseMultiple_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockParser_ParseMultiple_Call) RunAndReturn(run func(string) ([]*guide.DSLCommand, []error)) *MockParser_ParseMultiple_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockParser creates a new instance of MockParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParser {
	mock := &MockParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
