// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	guide "github.com/adalundhe/sylk/agents/guide"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockHealthMonitor is an autogenerated mock type for the HealthMonitorService type
type MockHealthMonitor struct {
	mock.Mock
}

type MockHealthMonitor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthMonitor) EXPECT() *MockHealthMonitor_Expecter {
	return &MockHealthMonitor_Expecter{mock: &_m.Mock}
}

// GetStatus provides a mock function with given fields: agentID
func (_m *MockHealthMonitor) GetStatus(agentID string) guide.HealthStatus {
	ret := _m.Called(agentID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 guide.HealthStatus
	if rf, ok := ret.Get(0).(func(string) guide.HealthStatus); ok {
		r0 = rf(agentID)
	} else {
		r0 = ret.Get(0).(guide.HealthStatus)
	}

	return r0
}

// MockHealthMonitor_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockHealthMonitor_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - agentID string
func (_e *MockHealthMonitor_Expecter) GetStatus(agentID interface{}) *MockHealthMonitor_GetStatus_Call {
	return &MockHealthMonitor_GetStatus_Call{Call: _e.mock.On("GetStatus", agentID)}
}

func (_c *MockHealthMonitor_GetStatus_Call) Run(run func(agentID string)) *MockHealthMonitor_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockHealthMonitor_GetStatus_Call) Return(_a0 guide.HealthStatus) *MockHealthMonitor_GetStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthMonitor_GetStatus_Call) RunAndReturn(run func(string) guide.HealthStatus) *MockHealthMonitor_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// IsHealthy provides a mock function with given fields: agentID
func (_m *MockHealthMonitor) IsHealthy(agentID string) bool {
	ret := _m.Called(agentID)

	if len(ret) == 0 {
		panic("no return value specified for IsHealthy")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(agentID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockHealthMonitor_IsHealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsHealthy'
type MockHealthMonitor_IsHealthy_Call struct {
	*mock.Call
}

// IsHealthy is a helper method to define mock.On call
//   - agentID string
func (_e *MockHealthMonitor_Expecter) IsHealthy(agentID interface{}) *MockHealthMonitor_IsHealthy_Call {
	return &MockHealthMonitor_IsHealthy_Call{Call: _e.mock.On("IsHealthy", agentID)}
}

func (_c *MockHealthMonitor_IsHealthy_Call) Run(run func(agentID string)) *MockHealthMonitor_IsHealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockHealthMonitor_IsHealthy_Call) Return(_a0 bool) *MockHealthMonitor_IsHealthy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthMonitor_IsHealthy_Call) RunAndReturn(run func(string) bool) *MockHealthMonitor_IsHealthy_Call {
	_c.Call.Return(run)
	return _c
}

// RecordResponse provides a mock function with given fields: agentID, responseTime
func (_m *MockHealthMonitor) RecordResponse(agentID string, responseTime time.Duration) {
	_m.Called(agentID, responseTime)
}

// MockHealthMonitor_RecordResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordResponse'
type MockHealthMonitor_RecordResponse_Call struct {
	*mock.Call
}

// RecordResponse is a helper method to define mock.On call
//   - agentID string
//   - responseTime time.Duration
func (_e *MockHealthMonitor_Expecter) RecordResponse(agentID interface{}, responseTime interface{}) *MockHealthMonitor_RecordResponse_Call {
	return &MockHealthMonitor_RecordResponse_Call{Call: _e.mock.On("RecordResponse", agentID, responseTime)}
}

func (_c *MockHealthMonitor_RecordResponse_Call) Run(run func(agentID string, responseTime time.Duration)) *MockHealthMonitor_RecordResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockHealthMonitor_RecordResponse_Call) Return() *MockHealthMonitor_RecordResponse_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthMonitor_RecordResponse_Call) RunAndReturn(run func(string, time.Duration)) *MockHealthMonitor_RecordResponse_Call {
	_c.Run(run)
	return _c
}

// Register provides a mock function with given fields: agentID
func (_m *MockHealthMonitor) Register(agentID string) {
	_m.Called(agentID)
}

// MockHealthMonitor_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockHealthMonitor_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - agentID string
func (_e *MockHealthMonitor_Expecter) Register(agentID interface{}) *MockHealthMonitor_Register_Call {
	return &MockHealthMonitor_Register_Call{Call: _e.mock.On("Register", agentID)}
}

func (_c *MockHealthMonitor_Register_Call) Run(run func(agentID string)) *MockHealthMonitor_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockHealthMonitor_Register_Call) Return() *MockHealthMonitor_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthMonitor_Register_Call) RunAndReturn(run func(string)) *MockHealthMonitor_Register_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockHealthMonitor) Start(ctx context.Context) {
	_m.Called(ctx)
}

// MockHealthMonitor_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockHealthMonitor_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthMonitor_Expecter) Start(ctx interface{}) *MockHealthMonitor_Start_Call {
	return &MockHealthMonitor_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockHealthMonitor_Start_Call) Run(run func(ctx context.Context)) *MockHealthMonitor_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHealthMonitor_Start_Call) Return() *MockHealthMonitor_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthMonitor_Start_Call) RunAndReturn(run func(context.Context)) *MockHealthMonitor_Start_Call {
	_c.Run(run)
	return _c
}

// Stats provides a mock function with no fields
func (_m *MockHealthMonitor) Stats() guide.HealthMonitorStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 guide.HealthMonitorStats
	if rf, ok := ret.Get(0).(func() guide.HealthMonitorStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(guide.HealthMonitorStats)
	}

	return r0
}

// MockHealthMonitor_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockHealthMonitor_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockHealthMonitor_Expecter) Stats() *MockHealthMonitor_Stats_Call {
	return &MockHealthMonitor_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockHealthMonitor_Stats_Call) Run(run func()) *MockHealthMonitor_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthMonitor_Stats_Call) Return(_a0 guide.HealthMonitorStats) *MockHealthMonitor_Stats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthMonitor_Stats_Call) RunAndReturn(run func() guide.HealthMonitorStats) *MockHealthMonitor_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *MockHealthMonitor) Stop() {
	_m.Called()
}

// MockHealthMonitor_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockHealthMonitor_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockHealthMonitor_Expecter) Stop() *MockHealthMonitor_Stop_Call {
	return &MockHealthMonitor_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockHealthMonitor_Stop_Call) Run(run func()) *MockHealthMonitor_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthMonitor_Stop_Call) Return() *MockHealthMonitor_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthMonitor_Stop_Call) RunAndReturn(run func()) *MockHealthMonitor_Stop_Call {
	_c.Run(run)
	return _c
}

// Unregister provides a mock function with given fields: agentID
func (_m *MockHealthMonitor) Unregister(agentID string) {
	_m.Called(agentID)
}

// MockHealthMonitor_Unregister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unregister'
type MockHealthMonitor_Unregister_Call struct {
	*mock.Call
}

// Unregister is a helper method to define mock.On call
//   - agentID string
func (_e *MockHealthMonitor_Expecter) Unregister(agentID interface{}) *MockHealthMonitor_Unregister_Call {
	return &MockHealthMonitor_Unregister_Call{Call: _e.mock.On("Unregister", agentID)}
}

func (_c *MockHealthMonitor_Unregister_Call) Run(run func(agentID string)) *MockHealthMonitor_Unregister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockHealthMonitor_Unregister_Call) Return() *MockHealthMonitor_Unregister_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHealthMonitor_Unregister_Call) RunAndReturn(run func(string)) *MockHealthMonitor_Unregister_Call {
	_c.Run(run)
	return _c
}

// NewMockHealthMonitor creates a new instance of MockHealthMonitor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthMonitor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthMonitor {
	mock := &MockHealthMonitor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
