// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	guide "github.com/adalundhe/sylk/agents/guide"
	mock "github.com/stretchr/testify/mock"
)

// MockClassifier is an autogenerated mock type for the ClassifierService type
type MockClassifier struct {
	mock.Mock
}

type MockClassifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClassifier) EXPECT() *MockClassifier_Expecter {
	return &MockClassifier_Expecter{mock: &_m.Mock}
}

// AddCorrection provides a mock function with given fields: correction
func (_m *MockClassifier) AddCorrection(correction guide.CorrectionRecord) {
	_m.Called(correction)
}

// MockClassifier_AddCorrection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCorrection'
type MockClassifier_AddCorrection_Call struct {
	*mock.Call
}

// AddCorrection is a helper method to define mock.On call
//   - correction guide.CorrectionRecord
func (_e *MockClassifier_Expecter) AddCorrection(correction interface{}) *MockClassifier_AddCorrection_Call {
	return &MockClassifier_AddCorrection_Call{Call: _e.mock.On("AddCorrection", correction)}
}

func (_c *MockClassifier_AddCorrection_Call) Run(run func(correction guide.CorrectionRecord)) *MockClassifier_AddCorrection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(guide.CorrectionRecord))
	})
	return _c
}

func (_c *MockClassifier_AddCorrection_Call) Return() *MockClassifier_AddCorrection_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClassifier_AddCorrection_Call) RunAndReturn(run func(guide.CorrectionRecord)) *MockClassifier_AddCorrection_Call {
	_c.Run(run)
	return _c
}

// Classify provides a mock function with given fields: ctx, input
func (_m *MockClassifier) Classify(ctx context.Context, input string) (*guide.ClassificationResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Classify")
	}

	var r0 *guide.ClassificationResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*guide.ClassificationResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *guide.ClassificationResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*guide.ClassificationResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClassifier_Classify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Classify'
type MockClassifier_Classify_Call struct {
	*mock.Call
}

// Classify is a helper method to define mock.On call
//   - ctx context.Context
//   - input string
func (_e *MockClassifier_Expecter) Classify(ctx interface{}, input interface{}) *MockClassifier_Classify_Call {
	return &MockClassifier_Classify_Call{Call: _e.mock.On("Classify", ctx, input)}
}

func (_c *MockClassifier_Classify_Call) Run(run func(ctx context.Context, input string)) *MockClassifier_Classify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClassifier_Classify_Call) Return(_a0 *guide.ClassificationResult, _a1 error) *MockClassifier_Classify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClassifier_Classify_Call) RunAndReturn(run func(context.Context, string) (*guide.ClassificationResult, error)) *MockClassifier_Classify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClassifier creates a new instance of MockClassifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClassifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClassifier {
	mock := &MockClassifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
