// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	guide "github.com/adalundhe/sylk/agents/guide"
	mock "github.com/stretchr/testify/mock"
)

// MockCircuitBreakerRegistry is an autogenerated mock type for the CircuitBreakerRegistryService type
type MockCircuitBreakerRegistry struct {
	mock.Mock
}

type MockCircuitBreakerRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCircuitBreakerRegistry) EXPECT() *MockCircuitBreakerRegistry_Expecter {
	return &MockCircuitBreakerRegistry_Expecter{mock: &_m.Mock}
}

// Allow provides a mock function with given fields: agentID
func (_m *MockCircuitBreakerRegistry) Allow(agentID string) bool {
	ret := _m.Called(agentID)

	if len(ret) == 0 {
		panic("no return value specified for Allow")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(agentID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockCircuitBreakerRegistry_Allow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allow'
type MockCircuitBreakerRegistry_Allow_Call struct {
	*mock.Call
}

// Allow is a helper method to define mock.On call
//   - agentID string
func (_e *MockCircuitBreakerRegistry_Expecter) Allow(agentID interface{}) *MockCircuitBreakerRegistry_Allow_Call {
	return &MockCircuitBreakerRegistry_Allow_Call{Call: _e.mock.On("Allow", agentID)}
}

func (_c *MockCircuitBreakerRegistry_Allow_Call) Run(run func(agentID string)) *MockCircuitBreakerRegistry_Allow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCircuitBreakerRegistry_Allow_Call) Return(_a0 bool) *MockCircuitBreakerRegistry_Allow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCircuitBreakerRegistry_Allow_Call) RunAndReturn(run func(string) bool) *MockCircuitBreakerRegistry_Allow_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: agentID
func (_m *MockCircuitBreakerRegistry) Get(agentID string) *guide.CircuitBreaker {
	ret := _m.Called(agentID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *guide.CircuitBreaker
	if rf, ok := ret.Get(0).(func(string) *guide.CircuitBreaker); ok {
		r0 = rf(agentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*guide.CircuitBreaker)
		}
	}

	return r0
}

// MockCircuitBreakerRegistry_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCircuitBreakerRegistry_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - agentID string
func (_e *MockCircuitBreakerRegistry_Expecter) Get(agentID interface{}) *MockCircuitBreakerRegistry_Get_Call {
	return &MockCircuitBreakerRegistry_Get_Call{Call: _e.mock.On("Get", agentID)}
}

func (_c *MockCircuitBreakerRegistry_Get_Call) Run(run func(agentID string)) *MockCircuitBreakerRegistry_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCircuitBreakerRegistry_Get_Call) Return(_a0 *guide.CircuitBreaker) *MockCircuitBreakerRegistry_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCircuitBreakerRegistry_Get_Call) RunAndReturn(run func(string) *guide.CircuitBreaker) *MockCircuitBreakerRegistry_Get_Call {
	_c.Call.Return(run)
	return _c
}

// OpenCircuits provides a mock function with no fields
func (_m *MockCircuitBreakerRegistry) OpenCircuits() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for OpenCircuits")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockCircuitBreakerRegistry_OpenCircuits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenCircuits'
type MockCircuitBreakerRegistry_OpenCircuits_Call struct {
	*mock.Call
}

// OpenCircuits is a helper method to define mock.On call
func (_e *MockCircuitBreakerRegistry_Expecter) OpenCircuits() *MockCircuitBreakerRegistry_OpenCircuits_Call {
	return &MockCircuitBreakerRegistry_OpenCircuits_Call{Call: _e.mock.On("OpenCircuits")}
}

func (_c *MockCircuitBreakerRegistry_OpenCircuits_Call) Run(run func()) *MockCircuitBreakerRegistry_OpenCircuits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCircuitBreakerRegistry_OpenCircuits_Call) Return(_a0 []string) *MockCircuitBreakerRegistry_OpenCircuits_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCircuitBreakerRegistry_OpenCircuits_Call) RunAndReturn(run func() []string) *MockCircuitBreakerRegistry_OpenCircuits_Call {
	_c.Call.Return(run)
	return _c
}

// RecordFailure provides a mock function with given fields: agentID
func (_m *MockCircuitBreakerRegistry) RecordFailure(agentID string) {
	_m.Called(agentID)
}

// MockCircuitBreakerRegistry_RecordFailure_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordFailure'
type MockCircuitBreakerRegistry_RecordFailure_Call struct {
	*mock.Call
}

// RecordFailure is a helper method to define mock.On call
//   - agentID string
func (_e *MockCircuitBreakerRegistry_Expecter) RecordFailure(agentID interface{}) *MockCircuitBreakerRegistry_RecordFailure_Call {
	return &MockCircuitBreakerRegistry_RecordFailure_Call{Call: _e.mock.On("RecordFailure", agentID)}
}

func (_c *MockCircuitBreakerRegistry_RecordFailure_Call) Run(run func(agentID string)) *MockCircuitBreakerRegistry_RecordFailure_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCircuitBreakerRegistry_RecordFailure_Call) Return() *MockCircuitBreakerRegistry_RecordFailure_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCircuitBreakerRegistry_RecordFailure_Call) RunAndReturn(run func(string)) *MockCircuitBreakerRegistry_RecordFailure_Call {
	_c.Run(run)
	return _c
}

// RecordSuccess provides a mock function with given fields: agentID
func (_m *MockCircuitBreakerRegistry) RecordSuccess(agentID string) {
	_m.Called(agentID)
}

// MockCircuitBreakerRegistry_RecordSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordSuccess'
type MockCircuitBreakerRegistry_RecordSuccess_Call struct {
	*mock.Call
}

// RecordSuccess is a helper method to define mock.On call
//   - agentID string
func (_e *MockCircuitBreakerRegistry_Expecter) RecordSuccess(agentID interface{}) *MockCircuitBreakerRegistry_RecordSuccess_Call {
	return &MockCircuitBreakerRegistry_RecordSuccess_Call{Call: _e.mock.On("RecordSuccess", agentID)}
}

func (_c *MockCircuitBreakerRegistry_RecordSuccess_Call) Run(run func(agentID string)) *MockCircuitBreakerRegistry_RecordSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCircuitBreakerRegistry_RecordSuccess_Call) Return() *MockCircuitBreakerRegistry_RecordSuccess_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCircuitBreakerRegistry_RecordSuccess_Call) RunAndReturn(run func(string)) *MockCircuitBreakerRegistry_RecordSuccess_Call {
	_c.Run(run)
	return _c
}

// Remove provides a mock function with given fields: agentID
func (_m *MockCircuitBreakerRegistry) Remove(agentID string) {
	_m.Called(agentID)
}

// MockCircuitBreakerRegistry_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockCircuitBreakerRegistry_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - agentID string
func (_e *MockCircuitBreakerRegistry_Expecter) Remove(agentID interface{}) *MockCircuitBreakerRegistry_Remove_Call {
	return &MockCircuitBreakerRegistry_Remove_Call{Call: _e.mock.On("Remove", agentID)}
}

func (_c *MockCircuitBreakerRegistry_Remove_Call) Run(run func(agentID string)) *MockCircuitBreakerRegistry_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCircuitBreakerRegistry_Remove_Call) Return() *MockCircuitBreakerRegistry_Remove_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCircuitBreakerRegistry_Remove_Call) RunAndReturn(run func(string)) *MockCircuitBreakerRegistry_Remove_Call {
	_c.Run(run)
	return _c
}

// Stats provides a mock function with no fields
func (_m *MockCircuitBreakerRegistry) Stats() map[string]guide.CircuitBreakerStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 map[string]guide.CircuitBreakerStats
	if rf, ok := ret.Get(0).(func() map[string]guide.CircuitBreakerStats); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]guide.CircuitBreakerStats)
		}
	}

	return r0
}

// MockCircuitBreakerRegistry_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockCircuitBreakerRegistry_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockCircuitBreakerRegistry_Expecter) Stats() *MockCircuitBreakerRegistry_Stats_Call {
	return &MockCircuitBreakerRegistry_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockCircuitBreakerRegistry_Stats_Call) Run(run func()) *MockCircuitBreakerRegistry_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCircuitBreakerRegistry_Stats_Call) Return(_a0 map[string]guide.CircuitBreakerStats) *MockCircuitBreakerRegistry_Stats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCircuitBreakerRegistry_Stats_Call) RunAndReturn(run func() map[string]guide.CircuitBreakerStats) *MockCircuitBreakerRegistry_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCircuitBreakerRegistry creates a new instance of MockCircuitBreakerRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCircuitBreakerRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCircuitBreakerRegistry {
	mock := &MockCircuitBreakerRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
