// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	guide "github.com/adalundhe/sylk/agents/guide"
	mock "github.com/stretchr/testify/mock"
)

// MockRouter is an autogenerated mock type for the RouterService type
type MockRouter struct {
	mock.Mock
}

type MockRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRouter) EXPECT() *MockRouter_Expecter {
	return &MockRouter_Expecter{mock: &_m.Mock}
}

// AddCorrection provides a mock function with given fields: correction
func (_m *MockRouter) AddCorrection(correction guide.CorrectionRecord) {
	_m.Called(correction)
}

// MockRouter_AddCorrection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCorrection'
type MockRouter_AddCorrection_Call struct {
	*mock.Call
}

// AddCorrection is a helper method to define mock.On call
//   - correction guide.CorrectionRecord
func (_e *MockRouter_Expecter) AddCorrection(correction interface{}) *MockRouter_AddCorrection_Call {
	return &MockRouter_AddCorrection_Call{Call: _e.mock.On("AddCorrection", correction)}
}

func (_c *MockRouter_AddCorrection_Call) Run(run func(correction guide.CorrectionRecord)) *MockRouter_AddCorrection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(guide.CorrectionRecord))
	})
	return _c
}

func (_c *MockRouter_AddCorrection_Call) Return() *MockRouter_AddCorrection_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouter_AddCorrection_Call) RunAndReturn(run func(guide.CorrectionRecord)) *MockRouter_AddCorrection_Call {
	_c.Run(run)
	return _c
}

// FormatAsDSL provides a mock function with given fields: result
func (_m *MockRouter) FormatAsDSL(result *guide.RouteResult) string {
	ret := _m.Called(result)

	if len(ret) == 0 {
		panic("no return value specified for FormatAsDSL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(*guide.RouteResult) string); ok {
		r0 = rf(result)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockRouter_FormatAsDSL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FormatAsDSL'
type MockRouter_FormatAsDSL_Call struct {
	*mock.Call
}

// FormatAsDSL is a helper method to define mock.On call
//   - result *guide.RouteResult
func (_e *MockRouter_Expecter) FormatAsDSL(result interface{}) *MockRouter_FormatAsDSL_Call {
	return &MockRouter_FormatAsDSL_Call{Call: _e.mock.On("FormatAsDSL", result)}
}

func (_c *MockRouter_FormatAsDSL_Call) Run(run func(result *guide.RouteResult)) *MockRouter_FormatAsDSL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*guide.RouteResult))
	})
	return _c
}

func (_c *MockRouter_FormatAsDSL_Call) Return(_a0 string) *MockRouter_FormatAsDSL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRouter_FormatAsDSL_Call) RunAndReturn(run func(*guide.RouteResult) string) *MockRouter_FormatAsDSL_Call {
	_c.Call.Return(run)
	return _c
}

// IsDSL provides a mock function with given fields: input
func (_m *MockRouter) IsDSL(input string) bool {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for IsDSL")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockRouter_IsDSL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDSL'
type MockRouter_IsDSL_Call struct {
	*mock.Call
}

// IsDSL is a helper method to define mock.On call
//   - input string
func (_e *MockRouter_Expecter) IsDSL(input interface{}) *MockRouter_IsDSL_Call {
	return &MockRouter_IsDSL_Call{Call: _e.mock.On("IsDSL", input)}
}

func (_c *MockRouter_IsDSL_Call) Run(run func(input string)) *MockRouter_IsDSL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRouter_IsDSL_Call) Return(_a0 bool) *MockRouter_IsDSL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRouter_IsDSL_Call) RunAndReturn(run func(string) bool) *MockRouter_IsDSL_Call {
	_c.Call.Return(run)
	return _c
}

// ParseDSL provides a mock function with given fields: input
func (_m *MockRouter) ParseDSL(input string) (*guide.DSLCommand, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for ParseDSL")
	}

	var r0 *guide.DSLCommand
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*guide.DSLCommand, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(string) *guide.DSLCommand); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*guide.DSLCommand)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRouter_ParseDSL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseDSL'
type MockRouter_ParseDSL_Call struct {
	*mock.Call
}

// ParseDSL is a helper method to define mock.On call
//   - input string
func (_e *MockRouter_Expecter) ParseDSL(input interface{}) *MockRouter_ParseDSL_Call {
	return &MockRouter_ParseDSL_Call{Call: _e.mock.On("ParseDSL", input)}
}

func (_c *MockRouter_ParseDSL_Call) Run(run func(input string)) *MockRouter_ParseDSL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRouter_ParseDSL_Call) Return(_a0 *guide.DSLCommand, _a1 error) *MockRouter_ParseDSL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRouter_ParseDSL_Call) RunAndReturn(run func(string) (*guide.DSLCommand, error)) *MockRouter_ParseDSL_Call {
	_c.Call.Return(run)
	return _c
}

// Route provides a mock function with given fields: ctx, request
func (_m *MockRouter) Route(ctx context.Context, request *guide.RouteRequest) (*guide.RouteResult, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Route")
	}

	var r0 *guide.RouteResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *guide.RouteRequest) (*guide.RouteResult, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *guide.RouteRequest) *guide.RouteResult); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*guide.RouteResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *guide.RouteRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRouter_Route_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Route'
type MockRouter_Route_Call struct {
	*mock.Call
}

// Route is a helper method to define mock.On call
//   - ctx context.Context
//   - request *guide.RouteRequest
func (_e *MockRouter_Expecter) Route(ctx interface{}, request interface{}) *MockRouter_Route_Call {
	return &MockRouter_Route_Call{Call: _e.mock.On("Route", ctx, request)}
}

func (_c *MockRouter_Route_Call) Run(run func(ctx context.Context, request *guide.RouteRequest)) *MockRouter_Route_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*guide.RouteRequest))
	})
	return _c
}

func (_c *MockRouter_Route_Call) Return(_a0 *guide.RouteResult, _a1 error) *MockRouter_Route_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRouter_Route_Call) RunAndReturn(run func(context.Context, *guide.RouteRequest) (*guide.RouteResult, error)) *MockRouter_Route_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRouter creates a new instance of MockRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRouter {
	mock := &MockRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
