// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	guide "github.com/adalundhe/sylk/agents/guide"
	mock "github.com/stretchr/testify/mock"
)

// MockDeadLetterQueue is an autogenerated mock type for the DeadLetterQueueService type
type MockDeadLetterQueue struct {
	mock.Mock
}

type MockDeadLetterQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeadLetterQueue) EXPECT() *MockDeadLetterQueue_Expecter {
	return &MockDeadLetterQueue_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: letter
func (_m *MockDeadLetterQueue) Add(letter *guide.DeadLetter) {
	_m.Called(letter)
}

// MockDeadLetterQueue_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockDeadLetterQueue_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - letter *guide.DeadLetter
func (_e *MockDeadLetterQueue_Expecter) Add(letter interface{}) *MockDeadLetterQueue_Add_Call {
	return &MockDeadLetterQueue_Add_Call{Call: _e.mock.On("Add", letter)}
}

func (_c *MockDeadLetterQueue_Add_Call) Run(run func(letter *guide.DeadLetter)) *MockDeadLetterQueue_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*guide.DeadLetter))
	})
	return _c
}

func (_c *MockDeadLetterQueue_Add_Call) Return() *MockDeadLetterQueue_Add_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDeadLetterQueue_Add_Call) RunAndReturn(run func(*guide.DeadLetter)) *MockDeadLetterQueue_Add_Call {
	_c.Run(run)
	return _c
}

// AddFromMessage provides a mock function with given fields: msg, topic, reason, err, attempts
func (_m *MockDeadLetterQueue) AddFromMessage(msg *guide.Message, topic string, reason guide.DeadLetterReason, err error, attempts int) {
	_m.Called(msg, topic, reason, err, attempts)
}

// MockDeadLetterQueue_AddFromMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFromMessage'
type MockDeadLetterQueue_AddFromMessage_Call struct {
	*mock.Call
}

// AddFromMessage is a helper method to define mock.On call
//   - msg *guide.Message
//   - topic string
//   - reason guide.DeadLetterReason
//   - err error
//   - attempts int
func (_e *MockDeadLetterQueue_Expecter) AddFromMessage(msg interface{}, topic interface{}, reason interface{}, err interface{}, attempts interface{}) *MockDeadLetterQueue_AddFromMessage_Call {
	return &MockDeadLetterQueue_AddFromMessage_Call{Call: _e.mock.On("AddFromMessage", msg, topic, reason, err, attempts)}
}

func (_c *MockDeadLetterQueue_AddFromMessage_Call) Run(run func(msg *guide.Message, topic string, reason guide.DeadLetterReason, err error, attempts int)) *MockDeadLetterQueue_AddFromMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*guide.Message), args[1].(string), args[2].(guide.DeadLetterReason), args[3].(error), args[4].(int))
	})
	return _c
}

func (_c *MockDeadLetterQueue_AddFromMessage_Call) Return() *MockDeadLetterQueue_AddFromMessage_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDeadLetterQueue_AddFromMessage_Call) RunAndReturn(run func(*guide.Message, string, guide.DeadLetterReason, error, int)) *MockDeadLetterQueue_AddFromMessage_Call {
	_c.Run(run)
	return _c
}

// Clear provides a mock function with no fields
func (_m *MockDeadLetterQueue) Clear() {
	_m.Called()
}

// MockDeadLetterQueue_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockDeadLetterQueue_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockDeadLetterQueue_Expecter) Clear() *MockDeadLetterQueue_Clear_Call {
	return &MockDeadLetterQueue_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *MockDeadLetterQueue_Clear_Call) Run(run func()) *MockDeadLetterQueue_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeadLetterQueue_Clear_Call) Return() *MockDeadLetterQueue_Clear_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockDeadLetterQueue_Clear_Call) RunAndReturn(run func()) *MockDeadLetterQueue_Clear_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function with given fields: filter
func (_m *MockDeadLetterQueue) Get(filter guide.DeadLetterFilter) []*guide.DeadLetter {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []*guide.DeadLetter
	if rf, ok := ret.Get(0).(func(guide.DeadLetterFilter) []*guide.DeadLetter); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*guide.DeadLetter)
		}
	}

	return r0
}

// MockDeadLetterQueue_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDeadLetterQueue_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - filter guide.DeadLetterFilter
func (_e *MockDeadLetterQueue_Expecter) Get(filter interface{}) *MockDeadLetterQueue_Get_Call {
	return &MockDeadLetterQueue_Get_Call{Call: _e.mock.On("Get", filter)}
}

func (_c *MockDeadLetterQueue_Get_Call) Run(run func(filter guide.DeadLetterFilter)) *MockDeadLetterQueue_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(guide.DeadLetterFilter))
	})
	return _c
}

func (_c *MockDeadLetterQueue_Get_Call) Return(_a0 []*guide.DeadLetter) *MockDeadLetterQueue_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeadLetterQueue_Get_Call) RunAndReturn(run func(guide.DeadLetterFilter) []*guide.DeadLetter) *MockDeadLetterQueue_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCorrelationID provides a mock function with given fields: correlationID
func (_m *MockDeadLetterQueue) GetByCorrelationID(correlationID string) *guide.DeadLetter {
	ret := _m.Called(correlationID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCorrelationID")
	}

	var r0 *guide.DeadLetter
	if rf, ok := ret.Get(0).(func(string) *guide.DeadLetter); ok {
		r0 = rf(correlationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*guide.DeadLetter)
		}
	}

	return r0
}

// MockDeadLetterQueue_GetByCorrelationID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCorrelationID'
type MockDeadLetterQueue_GetByCorrelationID_Call struct {
	*mock.Call
}

// GetByCorrelationID is a helper method to define mock.On call
//   - correlationID string
func (_e *MockDeadLetterQueue_Expecter) GetByCorrelationID(correlationID interface{}) *MockDeadLetterQueue_GetByCorrelationID_Call {
	return &MockDeadLetterQueue_GetByCorrelationID_Call{Call: _e.mock.On("GetByCorrelationID", correlationID)}
}

func (_c *MockDeadLetterQueue_GetByCorrelationID_Call) Run(run func(correlationID string)) *MockDeadLetterQueue_GetByCorrelationID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockDeadLetterQueue_GetByCorrelationID_Call) Return(_a0 *guide.DeadLetter) *MockDeadLetterQueue_GetByCorrelationID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeadLetterQueue_GetByCorrelationID_Call) RunAndReturn(run func(string) *guide.DeadLetter) *MockDeadLetterQueue_GetByCorrelationID_Call {
	_c.Call.Return(run)
	return _c
}

// Len provides a mock function with no fields
func (_m *MockDeadLetterQueue) Len() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Len")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockDeadLetterQueue_Len_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Len'
type MockDeadLetterQueue_Len_Call struct {
	*mock.Call
}

// Len is a helper method to define mock.On call
func (_e *MockDeadLetterQueue_Expecter) Len() *MockDeadLetterQueue_Len_Call {
	return &MockDeadLetterQueue_Len_Call{Call: _e.mock.On("Len")}
}

func (_c *MockDeadLetterQueue_Len_Call) Run(run func()) *MockDeadLetterQueue_Len_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeadLetterQueue_Len_Call) Return(_a0 int) *MockDeadLetterQueue_Len_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeadLetterQueue_Len_Call) RunAndReturn(run func() int) *MockDeadLetterQueue_Len_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRetried provides a mock function with given fields: correlationID
func (_m *MockDeadLetterQueue) MarkRetried(correlationID string) bool {
	ret := _m.Called(correlationID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRetried")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(correlationID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockDeadLetterQueue_MarkRetried_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRetried'
type MockDeadLetterQueue_MarkRetried_Call struct {
	*mock.Call
}

// MarkRetried is a helper method to define mock.On call
//   - correlationID string
func (_e *MockDeadLetterQueue_Expecter) MarkRetried(correlationID interface{}) *MockDeadLetterQueue_MarkRetried_Call {
	return &MockDeadLetterQueue_MarkRetried_Call{Call: _e.mock.On("MarkRetried", correlationID)}
}

func (_c *MockDeadLetterQueue_MarkRetried_Call) Run(run func(correlationID string)) *MockDeadLetterQueue_MarkRetried_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockDeadLetterQueue_MarkRetried_Call) Return(_a0 bool) *MockDeadLetterQueue_MarkRetried_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeadLetterQueue_MarkRetried_Call) RunAndReturn(run func(string) bool) *MockDeadLetterQueue_MarkRetried_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: correlationID
func (_m *MockDeadLetterQueue) Remove(correlationID string) bool {
	ret := _m.Called(correlationID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(correlationID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockDeadLetterQueue_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockDeadLetterQueue_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - correlationID string
func (_e *MockDeadLetterQueue_Expecter) Remove(correlationID interface{}) *MockDeadLetterQueue_Remove_Call {
	return &MockDeadLetterQueue_Remove_Call{Call: _e.mock.On("Remove", correlationID)}
}

func (_c *MockDeadLetterQueue_Remove_Call) Run(run func(correlationID string)) *MockDeadLetterQueue_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockDeadLetterQueue_Remove_Call) Return(_a0 bool) *MockDeadLetterQueue_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeadLetterQueue_Remove_Call) RunAndReturn(run func(string) bool) *MockDeadLetterQueue_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function with no fields
func (_m *MockDeadLetterQueue) Stats() guide.DeadLetterStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 guide.DeadLetterStats
	if rf, ok := ret.Get(0).(func() guide.DeadLetterStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(guide.DeadLetterStats)
	}

	return r0
}

// MockDeadLetterQueue_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockDeadLetterQueue_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockDeadLetterQueue_Expecter) Stats() *MockDeadLetterQueue_Stats_Call {
	return &MockDeadLetterQueue_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockDeadLetterQueue_Stats_Call) Run(run func()) *MockDeadLetterQueue_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeadLetterQueue_Stats_Call) Return(_a0 guide.DeadLetterStats) *MockDeadLetterQueue_Stats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeadLetterQueue_Stats_Call) RunAndReturn(run func() guide.DeadLetterStats) *MockDeadLetterQueue_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeadLetterQueue creates a new instance of MockDeadLetterQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeadLetterQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeadLetterQueue {
	mock := &MockDeadLetterQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
