// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	guide "github.com/adalundhe/sylk/agents/guide"
	mock "github.com/stretchr/testify/mock"
)

// MockPendingStore is an autogenerated mock type for the PendingStoreService type
type MockPendingStore struct {
	mock.Mock
}

type MockPendingStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPendingStore) EXPECT() *MockPendingStore_Expecter {
	return &MockPendingStore_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: req, classification, targetAgentID
func (_m *MockPendingStore) Add(req *guide.RouteRequest, classification *guide.RouteResult, targetAgentID string) string {
	ret := _m.Called(req, classification, targetAgentID)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(*guide.RouteRequest, *guide.RouteResult, string) string); ok {
		r0 = rf(req, classification, targetAgentID)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPendingStore_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockPendingStore_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - req *guide.RouteRequest
//   - classification *guide.RouteResult
//   - targetAgentID string
func (_e *MockPendingStore_Expecter) Add(req interface{}, classification interface{}, targetAgentID interface{}) *MockPendingStore_Add_Call {
	return &MockPendingStore_Add_Call{Call: _e.mock.On("Add", req, classification, targetAgentID)}
}

func (_c *MockPendingStore_Add_Call) Run(run func(req *guide.RouteRequest, classification *guide.RouteResult, targetAgentID string)) *MockPendingStore_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*guide.RouteRequest), args[1].(*guide.RouteResult), args[2].(string))
	})
	return _c
}

func (_c *MockPendingStore_Add_Call) Return(_a0 string) *MockPendingStore_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPendingStore_Add_Call) RunAndReturn(run func(*guide.RouteRequest, *guide.RouteResult, string) string) *MockPendingStore_Add_Call {
	_c.Call.Return(run)
	return _c
}

// CleanupExpired provides a mock function with no fields
func (_m *MockPendingStore) CleanupExpired() []*guide.PendingRequest {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CleanupExpired")
	}

	var r0 []*guide.PendingRequest
	if rf, ok := ret.Get(0).(func() []*guide.PendingRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*guide.PendingRequest)
		}
	}

	return r0
}

// MockPendingStore_CleanupExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupExpired'
type MockPendingStore_CleanupExpired_Call struct {
	*mock.Call
}

// CleanupExpired is a helper method to define mock.On call
func (_e *MockPendingStore_Expecter) CleanupExpired() *MockPendingStore_CleanupExpired_Call {
	return &MockPendingStore_CleanupExpired_Call{Call: _e.mock.On("CleanupExpired")}
}

func (_c *MockPendingStore_CleanupExpired_Call) Run(run func()) *MockPendingStore_CleanupExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPendingStore_CleanupExpired_Call) Return(_a0 []*guide.PendingRequest) *MockPendingStore_CleanupExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPendingStore_CleanupExpired_Call) RunAndReturn(run func() []*guide.PendingRequest) *MockPendingStore_CleanupExpired_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function with no fields
func (_m *MockPendingStore) Count() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockPendingStore_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockPendingStore_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
func (_e *MockPendingStore_Expecter) Count() *MockPendingStore_Count_Call {
	return &MockPendingStore_Count_Call{Call: _e.mock.On("Count")}
}

func (_c *MockPendingStore_Count_Call) Run(run func()) *MockPendingStore_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPendingStore_Count_Call) Return(_a0 int) *MockPendingStore_Count_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPendingStore_Count_Call) RunAndReturn(run func() int) *MockPendingStore_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountBySource provides a mock function with given fields: sourceAgentID
func (_m *MockPendingStore) CountBySource(sourceAgentID string) int {
	ret := _m.Called(sourceAgentID)

	if len(ret) == 0 {
		panic("no return value specified for CountBySource")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(sourceAgentID)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockPendingStore_CountBySource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountBySource'
type MockPendingStore_CountBySource_Call struct {
	*mock.Call
}

// CountBySource is a helper method to define mock.On call
//   - sourceAgentID string
func (_e *MockPendingStore_Expecter) CountBySource(sourceAgentID interface{}) *MockPendingStore_CountBySource_Call {
	return &MockPendingStore_CountBySource_Call{Call: _e.mock.On("CountBySource", sourceAgentID)}
}

func (_c *MockPendingStore_CountBySource_Call) Run(run func(sourceAgentID string)) *MockPendingStore_CountBySource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPendingStore_CountBySource_Call) Return(_a0 int) *MockPendingStore_CountBySource_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPendingStore_CountBySource_Call) RunAndReturn(run func(string) int) *MockPendingStore_CountBySource_Call {
	_c.Call.Return(run)
	return _c
}

// CountByTarget provides a mock function with given fields: targetAgentID
func (_m *MockPendingStore) CountByTarget(targetAgentID string) int {
	ret := _m.Called(targetAgentID)

	if len(ret) == 0 {
		panic("no return value specified for CountByTarget")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(targetAgentID)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockPendingStore_CountByTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByTarget'
type MockPendingStore_CountByTarget_Call struct {
	*mock.Call
}

// CountByTarget is a helper method to define mock.On call
//   - targetAgentID string
func (_e *MockPendingStore_Expecter) CountByTarget(targetAgentID interface{}) *MockPendingStore_CountByTarget_Call {
	return &MockPendingStore_CountByTarget_Call{Call: _e.mock.On("CountByTarget", targetAgentID)}
}

func (_c *MockPendingStore_CountByTarget_Call) Run(run func(targetAgentID string)) *MockPendingStore_CountByTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPendingStore_CountByTarget_Call) Return(_a0 int) *MockPendingStore_CountByTarget_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPendingStore_CountByTarget_Call) RunAndReturn(run func(string) int) *MockPendingStore_CountByTarget_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: correlationID
func (_m *MockPendingStore) Get(correlationID string) *guide.PendingRequest {
	ret := _m.Called(correlationID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *guide.PendingRequest
	if rf, ok := ret.Get(0).(func(string) *guide.PendingRequest); ok {
		r0 = rf(correlationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*guide.PendingRequest)
		}
	}

	return r0
}

// MockPendingStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPendingStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - correlationID string
func (_e *MockPendingStore_Expecter) Get(correlationID interface{}) *MockPendingStore_Get_Call {
	return &MockPendingStore_Get_Call{Call: _e.mock.On("Get", correlationID)}
}

func (_c *MockPendingStore_Get_Call) Run(run func(correlationID string)) *MockPendingStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPendingStore_Get_Call) Return(_a0 *guide.PendingRequest) *MockPendingStore_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPendingStore_Get_Call) RunAndReturn(run func(string) *guide.PendingRequest) *MockPendingStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySource provides a mock function with given fields: sourceAgentID
func (_m *MockPendingStore) GetBySource(sourceAgentID string) []*guide.PendingRequest {
	ret := _m.Called(sourceAgentID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySource")
	}

	var r0 []*guide.PendingRequest
	if rf, ok := ret.Get(0).(func(string) []*guide.PendingRequest); ok {
		r0 = rf(sourceAgentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*guide.PendingRequest)
		}
	}

	return r0
}

// MockPendingStore_GetBySource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySource'
type MockPendingStore_GetBySource_Call struct {
	*mock.Call
}

// GetBySource is a helper method to define mock.On call
//   - sourceAgentID string
func (_e *MockPendingStore_Expecter) GetBySource(sourceAgentID interface{}) *MockPendingStore_GetBySource_Call {
	return &MockPendingStore_GetBySource_Call{Call: _e.mock.On("GetBySource", sourceAgentID)}
}

func (_c *MockPendingStore_GetBySource_Call) Run(run func(sourceAgentID string)) *MockPendingStore_GetBySource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPendingStore_GetBySource_Call) Return(_a0 []*guide.PendingRequest) *MockPendingStore_GetBySource_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPendingStore_GetBySource_Call) RunAndReturn(run func(string) []*guide.PendingRequest) *MockPendingStore_GetBySource_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTarget provides a mock function with given fields: targetAgentID
func (_m *MockPendingStore) GetByTarget(targetAgentID string) []*guide.PendingRequest {
	ret := _m.Called(targetAgentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTarget")
	}

	var r0 []*guide.PendingRequest
	if rf, ok := ret.Get(0).(func(string) []*guide.PendingRequest); ok {
		r0 = rf(targetAgentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*guide.PendingRequest)
		}
	}

	return r0
}

// MockPendingStore_GetByTarget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTarget'
type MockPendingStore_GetByTarget_Call struct {
	*mock.Call
}

// GetByTarget is a helper method to define mock.On call
//   - targetAgentID string
func (_e *MockPendingStore_Expecter) GetByTarget(targetAgentID interface{}) *MockPendingStore_GetByTarget_Call {
	return &MockPendingStore_GetByTarget_Call{Call: _e.mock.On("GetByTarget", targetAgentID)}
}

func (_c *MockPendingStore_GetByTarget_Call) Run(run func(targetAgentID string)) *MockPendingStore_GetByTarget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPendingStore_GetByTarget_Call) Return(_a0 []*guide.PendingRequest) *MockPendingStore_GetByTarget_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPendingStore_GetByTarget_Call) RunAndReturn(run func(string) []*guide.PendingRequest) *MockPendingStore_GetByTarget_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function with given fields: correlationID
func (_m *MockPendingStore) Remove(correlationID string) *guide.PendingRequest {
	ret := _m.Called(correlationID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 *guide.PendingRequest
	if rf, ok := ret.Get(0).(func(string) *guide.PendingRequest); ok {
		r0 = rf(correlationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*guide.PendingRequest)
		}
	}

	return r0
}

// MockPendingStore_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockPendingStore_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - correlationID string
func (_e *MockPendingStore_Expecter) Remove(correlationID interface{}) *MockPendingStore_Remove_Call {
	return &MockPendingStore_Remove_Call{Call: _e.mock.On("Remove", correlationID)}
}

func (_c *MockPendingStore_Remove_Call) Run(run func(correlationID string)) *MockPendingStore_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPendingStore_Remove_Call) Return(_a0 *guide.PendingRequest) *MockPendingStore_Remove_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPendingStore_Remove_Call) RunAndReturn(run func(string) *guide.PendingRequest) *MockPendingStore_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function with no fields
func (_m *MockPendingStore) Stats() guide.PendingStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 guide.PendingStats
	if rf, ok := ret.Get(0).(func() guide.PendingStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(guide.PendingStats)
	}

	return r0
}

// MockPendingStore_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockPendingStore_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockPendingStore_Expecter) Stats() *MockPendingStore_Stats_Call {
	return &MockPendingStore_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockPendingStore_Stats_Call) Run(run func()) *MockPendingStore_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPendingStore_Stats_Call) Return(_a0 guide.PendingStats) *MockPendingStore_Stats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPendingStore_Stats_Call) RunAndReturn(run func() guide.PendingStats) *MockPendingStore_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPendingStore creates a new instance of MockPendingStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPendingStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPendingStore {
	mock := &MockPendingStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
