// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	guide "github.com/adalundhe/sylk/agents/guide"
	mock "github.com/stretchr/testify/mock"
)

// MockRouteCache is an autogenerated mock type for the RouteCacheService type
type MockRouteCache struct {
	mock.Mock
}

type MockRouteCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRouteCache) EXPECT() *MockRouteCache_Expecter {
	return &MockRouteCache_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function with no fields
func (_m *MockRouteCache) Cleanup() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockRouteCache_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockRouteCache_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
func (_e *MockRouteCache_Expecter) Cleanup() *MockRouteCache_Cleanup_Call {
	return &MockRouteCache_Cleanup_Call{Call: _e.mock.On("Cleanup")}
}

func (_c *MockRouteCache_Cleanup_Call) Run(run func()) *MockRouteCache_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRouteCache_Cleanup_Call) Return(_a0 int) *MockRouteCache_Cleanup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRouteCache_Cleanup_Call) RunAndReturn(run func() int) *MockRouteCache_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// Clear provides a mock function with no fields
func (_m *MockRouteCache) Clear() {
	_m.Called()
}

// MockRouteCache_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockRouteCache_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
func (_e *MockRouteCache_Expecter) Clear() *MockRouteCache_Clear_Call {
	return &MockRouteCache_Clear_Call{Call: _e.mock.On("Clear")}
}

func (_c *MockRouteCache_Clear_Call) Run(run func()) *MockRouteCache_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRouteCache_Clear_Call) Return() *MockRouteCache_Clear_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouteCache_Clear_Call) RunAndReturn(run func()) *MockRouteCache_Clear_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function with given fields: input
func (_m *MockRouteCache) Get(input string) *guide.CachedRoute {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *guide.CachedRoute
	if rf, ok := ret.Get(0).(func(string) *guide.CachedRoute); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*guide.CachedRoute)
		}
	}

	return r0
}

// MockRouteCache_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRouteCache_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - input string
func (_e *MockRouteCache_Expecter) Get(input interface{}) *MockRouteCache_Get_Call {
	return &MockRouteCache_Get_Call{Call: _e.mock.On("Get", input)}
}

func (_c *MockRouteCache_Get_Call) Run(run func(input string)) *MockRouteCache_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRouteCache_Get_Call) Return(_a0 *guide.CachedRoute) *MockRouteCache_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRouteCache_Get_Call) RunAndReturn(run func(string) *guide.CachedRoute) *MockRouteCache_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with no fields
func (_m *MockRouteCache) GetAll() []*guide.CachedRoute {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*guide.CachedRoute
	if rf, ok := ret.Get(0).(func() []*guide.CachedRoute); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*guide.CachedRoute)
		}
	}

	return r0
}

// MockRouteCache_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockRouteCache_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *MockRouteCache_Expecter) GetAll() *MockRouteCache_GetAll_Call {
	return &MockRouteCache_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *MockRouteCache_GetAll_Call) Run(run func()) *MockRouteCache_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRouteCache_GetAll_Call) Return(_a0 []*guide.CachedRoute) *MockRouteCache_GetAll_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRouteCache_GetAll_Call) RunAndReturn(run func() []*guide.CachedRoute) *MockRouteCache_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Invalidate provides a mock function with given fields: input
func (_m *MockRouteCache) Invalidate(input string) {
	_m.Called(input)
}

// MockRouteCache_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type MockRouteCache_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
//   - input string
func (_e *MockRouteCache_Expecter) Invalidate(input interface{}) *MockRouteCache_Invalidate_Call {
	return &MockRouteCache_Invalidate_Call{Call: _e.mock.On("Invalidate", input)}
}

func (_c *MockRouteCache_Invalidate_Call) Run(run func(input string)) *MockRouteCache_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRouteCache_Invalidate_Call) Return() *MockRouteCache_Invalidate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouteCache_Invalidate_Call) RunAndReturn(run func(string)) *MockRouteCache_Invalidate_Call {
	_c.Run(run)
	return _c
}

// InvalidateForAgent provides a mock function with given fields: agentID
func (_m *MockRouteCache) InvalidateForAgent(agentID string) {
	_m.Called(agentID)
}

// MockRouteCache_InvalidateForAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateForAgent'
type MockRouteCache_InvalidateForAgent_Call struct {
	*mock.Call
}

// InvalidateForAgent is a helper method to define mock.On call
//   - agentID string
func (_e *MockRouteCache_Expecter) InvalidateForAgent(agentID interface{}) *MockRouteCache_InvalidateForAgent_Call {
	return &MockRouteCache_InvalidateForAgent_Call{Call: _e.mock.On("InvalidateForAgent", agentID)}
}

func (_c *MockRouteCache_InvalidateForAgent_Call) Run(run func(agentID string)) *MockRouteCache_InvalidateForAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRouteCache_InvalidateForAgent_Call) Return() *MockRouteCache_InvalidateForAgent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouteCache_InvalidateForAgent_Call) RunAndReturn(run func(string)) *MockRouteCache_InvalidateForAgent_Call {
	_c.Run(run)
	return _c
}

// Set provides a mock function with given fields: input, result
func (_m *MockRouteCache) Set(input string, result *guide.RouteResult) {
	_m.Called(input, result)
}

// MockRouteCache_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockRouteCache_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - input string
//   - result *guide.RouteResult
func (_e *MockRouteCache_Expecter) Set(input interface{}, result interface{}) *MockRouteCache_Set_Call {
	return &MockRouteCache_Set_Call{Call: _e.mock.On("Set", input, result)}
}

func (_c *MockRouteCache_Set_Call) Run(run func(input string, result *guide.RouteResult)) *MockRouteCache_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*guide.RouteResult))
	})
	return _c
}

func (_c *MockRouteCache_Set_Call) Return() *MockRouteCache_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouteCache_Set_Call) RunAndReturn(run func(string, *guide.RouteResult)) *MockRouteCache_Set_Call {
	_c.Run(run)
	return _c
}

// SetBulk provides a mock function with given fields: routes
func (_m *MockRouteCache) SetBulk(routes []*guide.CachedRoute) {
	_m.Called(routes)
}

// MockRouteCache_SetBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBulk'
type MockRouteCache_SetBulk_Call struct {
	*mock.Call
}

// SetBulk is a helper method to define mock.On call
//   - routes []*guide.CachedRoute
func (_e *MockRouteCache_Expecter) SetBulk(routes interface{}) *MockRouteCache_SetBulk_Call {
	return &MockRouteCache_SetBulk_Call{Call: _e.mock.On("SetBulk", routes)}
}

func (_c *MockRouteCache_SetBulk_Call) Run(run func(routes []*guide.CachedRoute)) *MockRouteCache_SetBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*guide.CachedRoute))
	})
	return _c
}

func (_c *MockRouteCache_SetBulk_Call) Return() *MockRouteCache_SetBulk_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouteCache_SetBulk_Call) RunAndReturn(run func([]*guide.CachedRoute)) *MockRouteCache_SetBulk_Call {
	_c.Run(run)
	return _c
}

// SetFromRoute provides a mock function with given fields: input, targetAgentID, intent, domain
func (_m *MockRouteCache) SetFromRoute(input string, targetAgentID string, intent guide.Intent, domain guide.Domain) {
	_m.Called(input, targetAgentID, intent, domain)
}

// MockRouteCache_SetFromRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFromRoute'
type MockRouteCache_SetFromRoute_Call struct {
	*mock.Call
}

// SetFromRoute is a helper method to define mock.On call
//   - input string
//   - targetAgentID string
//   - intent guide.Intent
//   - domain guide.Domain
func (_e *MockRouteCache_Expecter) SetFromRoute(input interface{}, targetAgentID interface{}, intent interface{}, domain interface{}) *MockRouteCache_SetFromRoute_Call {
	return &MockRouteCache_SetFromRoute_Call{Call: _e.mock.On("SetFromRoute", input, targetAgentID, intent, domain)}
}

func (_c *MockRouteCache_SetFromRoute_Call) Run(run func(input string, targetAgentID string, intent guide.Intent, domain guide.Domain)) *MockRouteCache_SetFromRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(guide.Intent), args[3].(guide.Domain))
	})
	return _c
}

func (_c *MockRouteCache_SetFromRoute_Call) Return() *MockRouteCache_SetFromRoute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouteCache_SetFromRoute_Call) RunAndReturn(run func(string, string, guide.Intent, guide.Domain)) *MockRouteCache_SetFromRoute_Call {
	_c.Run(run)
	return _c
}

// Stats provides a mock function with no fields
func (_m *MockRouteCache) Stats() guide.RouteCacheStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 guide.RouteCacheStats
	if rf, ok := ret.Get(0).(func() guide.RouteCacheStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(guide.RouteCacheStats)
	}

	return r0
}

// MockRouteCache_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockRouteCache_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockRouteCache_Expecter) Stats() *MockRouteCache_Stats_Call {
	return &MockRouteCache_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockRouteCache_Stats_Call) Run(run func()) *MockRouteCache_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRouteCache_Stats_Call) Return(_a0 guide.RouteCacheStats) *MockRouteCache_Stats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRouteCache_Stats_Call) RunAndReturn(run func() guide.RouteCacheStats) *MockRouteCache_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRouteCache creates a new instance of MockRouteCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRouteCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRouteCache {
	mock := &MockRouteCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
