// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockSubscription is an autogenerated mock type for the Subscription type
type MockSubscription struct {
	mock.Mock
}

type MockSubscription_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscription) EXPECT() *MockSubscription_Expecter {
	return &MockSubscription_Expecter{mock: &_m.Mock}
}

// IsActive provides a mock function with no fields
func (_m *MockSubscription) IsActive() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsActive")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockSubscription_IsActive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsActive'
type MockSubscription_IsActive_Call struct {
	*mock.Call
}

// IsActive is a helper method to define mock.On call
func (_e *MockSubscription_Expecter) IsActive() *MockSubscription_IsActive_Call {
	return &MockSubscription_IsActive_Call{Call: _e.mock.On("IsActive")}
}

func (_c *MockSubscription_IsActive_Call) Run(run func()) *MockSubscription_IsActive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSubscription_IsActive_Call) Return(_a0 bool) *MockSubscription_IsActive_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubscription_IsActive_Call) RunAndReturn(run func() bool) *MockSubscription_IsActive_Call {
	_c.Call.Return(run)
	return _c
}

// Topic provides a mock function with no fields
func (_m *MockSubscription) Topic() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Topic")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockSubscription_Topic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Topic'
type MockSubscription_Topic_Call struct {
	*mock.Call
}

// Topic is a helper method to define mock.On call
func (_e *MockSubscription_Expecter) Topic() *MockSubscription_Topic_Call {
	return &MockSubscription_Topic_Call{Call: _e.mock.On("Topic")}
}

func (_c *MockSubscription_Topic_Call) Run(run func()) *MockSubscription_Topic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSubscription_Topic_Call) Return(_a0 string) *MockSubscription_Topic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubscription_Topic_Call) RunAndReturn(run func() string) *MockSubscription_Topic_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function with no fields
func (_m *MockSubscription) Unsubscribe() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubscription_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockSubscription_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
func (_e *MockSubscription_Expecter) Unsubscribe() *MockSubscription_Unsubscribe_Call {
	return &MockSubscription_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe")}
}

func (_c *MockSubscription_Unsubscribe_Call) Run(run func()) *MockSubscription_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSubscription_Unsubscribe_Call) Return(_a0 error) *MockSubscription_Unsubscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubscription_Unsubscribe_Call) RunAndReturn(run func() error) *MockSubscription_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscription creates a new instance of MockSubscription. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscription(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscription {
	mock := &MockSubscription{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
